### ISSUE TITLE
Always call event.preventDefault on onInputKeyDown?

### ISSUE THREAD

**Issue by stream7** [moroshko/react-autosuggest#10]
Hello!

I have a use case where when enter is clicked in order to select one suggestion the form is submitted. I think that it might be a good idea to expose the event onSuggestionSelected

```
function onSuggestionSelected(suggestion, event) {
  console.log('Suggestion selected: [' + suggestion + ']');
}
```

See https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L181

**Comment by moroshko** [comment]
@stream7 Thanks for #11! I think it's probably not a good idea to **always** call `preventDefault()` as users might want to submit a form when suggestion is selected. User should be in control whether to submit a form or not, and this is why you want the `event` object, right? You basically want to call `event.preventDefault()` inside `onSuggestionSelected()`, right?

**Comment by stream7** [comment]
>  You basically want to call event.preventDefault() inside onSuggestionSelected(), right?

@moroshko yes that is correct

**Comment by stream7** [comment]
thanks!

**Comment by moroshko** [comment]
Thank you for the contribution! Hopefully, I'll publish a new version on npm in the next day or two.

**Comment by moroshko** [comment]
It's in v1.10.0 now, enjoy!

**Comment by stream7** [comment]
@moroshko Thank you! :)

**Comment by w35l3y** [comment]
So should it be possible to call `event.preventDefault()` after this merge ?

I just tried to call it inside `onSuggestionSelected` and still the option was selected.

I am using version 9.3.2

**Comment by moroshko** [comment]
@w35l3y Could you create a new issue with a Codepen that demonstrates the issue?
