### ISSUE TITLE
onChange is fired when the value is changed by higher order component

### ISSUE THREAD

**Issue by kromit** [moroshko/react-autosuggest#100]
`onChange` should only be fired when the `value` of the component was changed, but not if the `props.value` given from the higher order component was changed. Since the component is controlled, there should be no state to be changed or at least the state has to be resetted when new props are incoming.

**Comment by moroshko** [comment]
@kromit I think this is fixed in 3.0. Have a look at this [example](http://codepen.io/moroshko/pen/BjLqXe), and let me know if you think that it still doesn't behave as expected.
