### ISSUE TITLE
Fails in IE10

### ISSUE THREAD

**Issue by sconnelley** [moroshko/react-autosuggest#110]
First of all, your component is great. I noticed though it fails in IE10 with this error:
```
Unable to get property 'theme' of undefined or null reference
```

Seems like `this.props` is `undefined` [here](https://github.com/moroshko/react-autosuggest/blob/master/src/AutosuggestContainer.js#L106).

**Comment by moroshko** [comment]
@sconnelley @cheapsteak Could you confirm please that the error has gone in IE10?

**Comment by sconnelley** [comment]
yes no errors.  FYI...I was also able to get it to work also by loading a `getPrototypeOf` polyfill.

**Comment by moroshko** [comment]
@sconnelley Thanks!
