### ISSUE TITLE
How to use Autosuggest inside a scrollable container without the suggestions expanding the container?

### ISSUE THREAD

**Issue by MrLeebo** [moroshko/react-autosuggest#112]
Hello there!

If I have an Autosuggest inside a container with a `max-height` and `overflow-y: scroll`, how can I prevent the suggestions container from expanding the scrollable container?

Via the theme, I tried setting `position: absolute` on `suggestionsContainer`, but it had no effect. Putting `position: absolute` on `container` causes the input textbox to become absolute too.

Here's a CodePen to the Basic sample inside a scrollable container:
http://codepen.io/anon/pen/WrdLMM?editors=0110

**Comment by moroshko** [comment]
Good question :)
[I tried to help](http://stackoverflow.com/q/35007733/247243) by checking how this can be achieved outside of react-autosuggest, but no luck. 
I feel like it's a generic CSS question, not a react-autosuggest specific issue. 
If you find a solution outside of react-autosuggest context, please share and we'll revisit this again. Closing for now.

**Comment by MrLeebo** [comment]
@moroshko Thanks for the effort! :) I ended up using jquery-ui's position method to set the position of the menu, which is a somewhat serviceable hack for the time being. Only drawback is that it goes out of alignment if the user scrolls the window while the menu is visible.

Here is an example Gist of my Typeahead control using react-autosuggest with the props slightly reworked to play better with redux-form fields: https://gist.github.com/MrLeebo/db40779fecffda785d85

**Comment by danieloprado** [comment]
I think this is a react-autosuggest problem, take a look at the https://material.angularjs.org/latest/demo/autocomplete dialog example, to avoid this problem, angular material add the container at the end of the page outside the input context. This is not a css only problem.
