### ISSUE TITLE
Method if no suggestion selected

### ISSUE THREAD

**Issue by istarkov** [moroshko/react-autosuggest#113]
Sometimes we need to make some additional work on result if no suggestion was selected. 
For example: suggestion engine did not find anything, but user entered some string and pressed enter.
(_for such situation I can execute more powerful search engine than autocomplete_)

The problem that simply intercepting just `onBlur` and `onKeyDown(ENTER_PRESSED)` is not enough, I need to be sure that `onSuggestionSelected` has not been called so I could use "powerful search engine".

For now using your control I intercepts `onBlur` and `onKeyDownCapture` on input (`inputProps`) and just check inside `setTimeout 0` interval was or not call to `onSuggestionSelected`

```javascript
onSuggestionSelected () {
   this.counter_++;
}
onKeyDownCapture(e) {
  if (e.key === 'Enter') {
    const callCounter = this.counter_;
    setTimeout(() => {
      if (this.counter_ !== callCounter) {
         console.log('onSuggestionSelected CALLED')
      } else {
        // RUN "powerful search engine" 
      }
    }, 0);
  }
}
```

IMHO this is not rare situation when autosuggestion service returns nothing, but search engine can return something. Look at google search for example.

So the idea is to add some new method to your control like `onSuggestionNotSelectedButWasBlurOnInputOrUserHasPressedEnter` :-) and call this method inside your `onBlur` and `onKeyDown` interceptors if no suggestion was selected.

Or just call onSuggestionSelected with some additional like `reason` property.

**Comment by moroshko** [comment]
@istarkov You can achieve this by wrapping the Autosuggest with a `form`, and running the "powerful search engine" in its `onSubmit`. Have a look at this [Codepen](http://codepen.io/moroshko/pen/xZWXJZ?editors=0110).

**Comment by istarkov** [comment]
Wow!!! Super!! Thank you!
