### ISSUE TITLE
How i can add `ref` for input element?

### ISSUE THREAD

**Issue by andreychev** [moroshko/react-autosuggest#114]
![http://img.parcsis.net/i/14a366604513ce7b4d30963872f7ffdf.png](http://img.parcsis.net/i/14a366604513ce7b4d30963872f7ffdf.png)

In 2.x version, i could have written something like this: `ReactDOM.findDOMNode(this.refs.input).select();`.

**Comment by moroshko** [comment]
@andreychev Starting from version 3.4.0, the input is accessible on Autosuggest instance, so you can do:

    <Autosuggest ref={autosuggest => autosuggest.input.select()} ... />

**Comment by andreychev** [comment]
@moroshko :+1:
