### ISSUE TITLE
Hot load theming

### ISSUE THREAD

**Issue by KyleAMathews** [moroshko/react-autosuggest#115]
Is there something special I have to get this to work? I'm passing inline styles in but I'm only seeing changes after a hard-reload.

**Comment by moroshko** [comment]
@KyleAMathews I haven't tried hot reloading yet, but I wonder if it's related to [react-themeable](https://github.com/markdalgleish/react-themeable). cc @markdalgleish 

Any chance you could provide a repo that demonstrates the issue?

**Comment by moroshko** [comment]
Closing for now.

**Comment by moroshko** [comment]
@KyleAMathews This should be resolved in 3.5.0

**Comment by KyleAMathews** [comment]
:+1:
