### ISSUE TITLE
Possible to get the id of an Autosuggest Container

### ISSUE THREAD

**Issue by BigPrimeNumbers** [moroshko/react-autosuggest#116]
Hi there,
  Is it possible to get the id of an autosuggest container that is calling a function? For instance, I have multiple autosuggest containers on a page, and would like to have just one version of each function (e.g. onSuggestionsUpdateRequested, etc.) that have logic within them to act accordingly (set the appropriate property in state, etc) by checking which autocorrect container is invoking the function. 

  I'm somewhat new at this, so maybe this is already possible, or perhaps there is a better way of handling this issue that I haven't thought of. Thanks!

**Comment by moroshko** [comment]
@BigPrimeNumbers Could you please provide a real world use case for this, with a  code example (use [this example](http://codepen.io/moroshko/pen/LGNJMy) as a starting point)? I'd like to better understand your motivation.

**Comment by BigPrimeNumbers** [comment]
I'm trying to build a form that has multiple autocomplete inputs. Instead of having multiple similar functions such as _onSuggestionsUpdateRequested_ and _getSuggestionValue_ for each container, I was attempting to insert logic into a single version of these functions that could determine which container was calling the function. 

My (pseudo-ish) code is here: [](http://codepen.io/BigPrimeNumbers/pen/mVLzvm?editors=0010)

**Comment by BigPrimeNumbers** [comment]
Incidentally, I have a couple of other questions:

1. How would one get multiple Autosuggest components on the same line? They all seem to render as divs, and so they appear underneath each other as opposed to side-by-side.
2. How would one use Autosuggest with forms? I'd like to use this in conjunction with a custom form component that includes validation, such as [tcomb-form](https://github.com/gcanti/tcomb-form), but am not quite sure how that would work. 

Thanks again for your input and hard work!

**Comment by moroshko** [comment]
@BigPrimeNumbers I can't see a clear benefit of doing what you are trying to do. I'd just create 2 separate components: FirstNameAutosuggest and LastNameAutosuggest. They could still share some common logic if you need:

```js
// FirstNameAutosuggest.js
import commonLogic from 'common-logic-file';
getSuggestions(value) {
  // use `commonLogic` here
}

// LastNameAutosuggest.js
import commonLogic from 'common-logic-file';
getSuggestions(value) {
  // use `commonLogic` here
}
```
I think it's much easier to reason about your app this way rather than having one component that is doing everything.

To have 2 Autosuggests side by side just give containers `display: inline-block;`. [Example](http://codepen.io/moroshko/pen/adKwBv?editors=0100)

Integrating with other 3rd party components/libraries could be tricky and need to be handled case by case. There is no way I could guarantee easy integration with all 3rd party libraries. Try and see what exactly do you need from react-autosuggest for that integration, and come back with more specific questions.

**Comment by BigPrimeNumbers** [comment]
Okay thanks for the input; it'll make the code slightly more verbose, but I'll work around it.
As for integration into a 3rd party component, I'm specifically trying to use [tcomb-form](https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#customizations). I can't seem to get the two to play nicely, so any thoughts you'd have for getting the two cooperating would be great (the component supports custom templates for libraries, so it should be possible, but I'm having trouble getting it to work).

**Comment by moroshko** [comment]
Sorry, I probably can't help you with tcomb-form integration unless you have a more specific question / non-working runnable example.

**Comment by BigPrimeNumbers** [comment]
No problem at all. I've got it figured out; if anyone else needs help with this particular setup, feel free to contact me. Thanks for doing what you could with this one!

**Comment by braindrained** [comment]
@BigPrimeNumbers can you share your solution with tcomb-form? I tried the example that gcanti gived to you on the tcomb-form repo but it won't work properly.
Thanks in advance.

**Comment by BigPrimeNumbers** [comment]
We actually abandoned tcomb-form months ago in favor of just making our own custom forms, so I can't remember exactly what I was doing to make it all work, but here's some of the (modified) code from commits back then:

"FormTemplate.js"
```javascript
import React from 'react'
import T from 'tcomb-form'
import Autosuggest from './AutosuggestComponent.js'

export default class AutosuggestFormTemplate {

	getTemplate(options) {

	    function renderInput(locals) {
	        const value = locals.value || '' // react-autosuggest doesn't like null or undefined as value]
	        const suggestions = options.suggestions
	        const label = locals.label
	        const temp = new Autosuggest(suggestions, label)
			return temp.getAutosuggestComponent(
				value,
				locals.attrs.placeholder,
				(evt, { newValue }) => {locals.onChange(newValue)}
			)
	    }
	    return T.form.Form.templates.textbox.clone({ renderInput })
	}
}
```

"Form.js"
```javascript
...
import T from 'tcomb-form'
import AutosuggestTemplate from './AutosuggestFormTemplate.js'
...

// TCOMB FORM STUFF
const Form = T.form.Form
const item = T.struct({
  name: T.String,
  company: T.String,
});
const options = {
    fields: {
        name: {
            attrs: {
                placeholder: 'Type item name'
            },
            template: getTemplate(names),
            error: <i> Please enter an item name</i>
        },
        company: {
            attrs: {
                placeholder: 'Type company name'
            },
            template: getTemplate(companies),
            error: <i> Please enter a company name</i>
        }
    }
}

function getTemplate(suggestions = []) {
    let autocompleteTemplate = new AutosuggestTemplate()
    return autocompleteTemplate.getTemplate({suggestions})
}

export default class Form extends React.Component {

    createAutosuggestComponent(suggestions, value, placeholder, onChange, label) {
        let autosuggestComponent = new Autosuggest(suggestions, label)
        return autosuggestComponent.getAutosuggestComponent(value, placeholder, onChange)
    }

...

    render() {
        return (
            <div>
                    <span>
                           {this.createAutosuggestComponent(
                                    names,
                                    this.state.name,
                                    "Enter an item name",
                                    this.onChange,
                                    "name")}
                        <span>{this.controls()}</span>
                    </span>
            </div>
        )
    }
```

Hope this helps!

**Comment by braindrained** [comment]
I'll give it a try! Thanks!
