### ISSUE TITLE
Breaking API change on minor version

### ISSUE THREAD

**Issue by ThibWeb** [moroshko/react-autosuggest#119]
First of all thanks for writing this component, it works very well and is very accessible.

While developing my project I noticed that my autocompletion code broke between two `npm install` – namely the `onSuggestionUpdateRequested` callback. The reason is quite simple: an API change was introduced in https://github.com/moroshko/react-autosuggest/commit/ef0934bea7429aea3e5b85bb53b05825f16daebf.

It might seem like a minor change to switch the function signature from `onSuggestionsUpdateRequested(value)` to `onSuggestionsUpdateRequested({value, reason: 'string'}` but it's more than enough to break the code that relies on this. If this project follows [semver](semver.org), such changes should be reflected by a major version bump so that people updating their dependencies can expect forward compatibility issues.

I don't think there is a particular fix for this instance of the issue. Version `3.2.0` was short-lived so it's mostly bad luck on my side to happen to download that particular one. I'd just advise caution for future updates.

**Comment by moroshko** [comment]
@ThibWeb Thanks for this issue. I completely agree, and aware of semver. I was hoping that no one will be affected by this "short lived breaking change". This is a good lesson for me :) I'll try to do a better job in the future following semver.

**Comment by ThibWeb** [comment]
:+1: it didn't cause much harm in the end, I figured it out quite quickly.

Thank you for your work!
