### ISSUE TITLE
Move cursor to the end of the input during onFocus={true}

### ISSUE THREAD

**Issue by Pierrebleroux** [moroshko/react-autosuggest#121]
I am currently using the onFocus={true} on my inputProps for this component, how can I go about setting the cursor to the end of the auto-suggest input?

It is currently focusing on the input of the autosuggest component once the component has been added to the DOM, but it is placing the cursor at the start of the input.

**Comment by moroshko** [comment]
To get the input field see [this example](http://codepen.io/moroshko/pen/WryOMP). Then, use `inputProps.onFocus` to move the cursor to the end. [This](http://stackoverflow.com/a/19568146/247243) StackOverflow question may help. Closing this issue as it seems more like a generic Javascript question than a react-autosuggest question.
