### ISSUE TITLE
Render suggestions on first focus

### ISSUE THREAD

**Issue by jbasrai** [moroshko/react-autosuggest#122]
I'd like to show suggestions when the input is focused for the first time.  If I define

```javascript
shouldRenderSuggestions: function(value) {
    return true;
}
```

, suggestions are only displayed after the input value is first changed.  If this is intended, then is there a solution to force a paint bound to the `onFocus` event?

**Comment by moroshko** [comment]
@jbasrai Make sure that the function that calculates the suggestions returns a non-empty list of suggestions when the input value is blank.
If it doesn't help, could you create please a Codepen that demonstrates the issue?

**Comment by jbasrai** [comment]
My mistake, the suggestions weren't being populated until the later.  Thanks for the insight!
