### ISSUE TITLE
Best way to focus text input from outside

### ISSUE THREAD

**Issue by kuy** [moroshko/react-autosuggest#124]
I wanted to focus `<input>` of `AutosuggestContainer` from other react component.
As a hacky solution, I wrote following code to realize it.

```
import Autosuggest from 'react-autosuggest';

export default class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.saveSuggest = this.saveSuggest.bind(this);
    this.onClick = this.onClick.bind(this);
  }

  saveSuggest(suggest) {
    if (suggest) {
      this.suggest = suggest;
    }
  }

  onClick() {
    if (this.suggest && this.suggest.input) {
      ReactDOM.findDOMNode(this.suggest.input).focus();
    }
  }

  render() {
    return (
      <div>
        <button onClick={this.onClick}>Focus input</button>
        <Autosuggest
          ref={this.saveSuggest}
          // ...
        />
      </div>
    );
  }
}
```

**Question**: Is there other way without hack? Because of `react-autosuggest` is self-contained component, I couldn't emit `INPUT_FOCUSED` action from outside. Thanks in advance :smiley:

**Comment by jbasrai** [comment]
I missed this earlier too, the answer is available in the [FAQ](https://github.com/moroshko/react-autosuggest/blob/master/FAQ.md):

> The input field is available on the Autosuggest instance as `input`

So you can save the `ref` of the Autosuggest component and extract the `input` field from there

**Comment by kuy** [comment]
@jbasrai Thanks for pointing! I missed it.
