### ISSUE TITLE
Submit form

### ISSUE THREAD

**Issue by aganglada** [moroshko/react-autosuggest#125]
I have a city auto completable in my form and I want this to be required, I setted inputProps with a required attribute but it doesn't really work as I expect.

What I want is the user to not be able to submit the form till the city_id selected in the input as a value.
Also if the user deletes just one letter of the city, the value of the input will be reseted.

Is there any way to do that?
Thanks in advance.

**Comment by moroshko** [comment]
@aganglada Sounds like you want to have a hidden `city_id` field that will be set based on what user types or selects from the Autosuggest. It is possible to achieve this, but it's up to you to implement this. This is not part of `react-autosuggest`.

Making the Autosuggest a `required` field shouldn't be a problem. [Codepen example.](http://codepen.io/moroshko/pen/QyRaPG)

If you don't want to allow users to submit a free text, you'll have to intercept the form submission in Javascript and check the `city_id` there. `react-autosuggest` designed to be a progressively enhanced component, i.e. it should degrade gracefully if Javascript is disabled. Normally, if Javascript is disabled, you'd still want users to be able to use your site. This is why `react-autosuggest` allows free text.

I hope this helps.

**Comment by aganglada** [comment]
It´s a solution :+1: a nice one. I will try doing that, thank you!

**Comment by moroshko** [comment]
Closing for now.
