### ISSUE TITLE
An optional prop to render as textarea

### ISSUE THREAD

**Issue by ntgn81** [moroshko/react-autosuggest#127]
Hello,

First, thanks for this component. It works great for me!

Now I need it to work on a textarea. If I went and changed react-autowhatever to render textarea instead of input, it would gets me quite close to what I need, bare the quirks with arrow up/down keys inside textarea - https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L233

Would it be possible to have `autowhatever` accept an optional prop - `useTextarea`?

One place I can think of is that prop can be passed through `autosuggest` as part of inputProps.

Thanks!

**Comment by moroshko** [comment]
@ntgn81 Could you explain your use case with textarea? Why input is not good enough?

**Comment by ntgn81** [comment]
For sure.

I have a list of text items that can be long, simple input does not have enough space to show the lengthy text, so I have to use textarea to show more text for each entry.

I also need to show users possible matches as they type something new, giving them the option to reuse an existing item instead of entering a new one.

Was that a clear enough definition?

**Comment by moroshko** [comment]
@ntgn81 Sounds reasonable, but I never saw an autosuggest component with a textarea. Do you know any examples online that implement a similar behaviour to what you want?

**Comment by ntgn81** [comment]
I couldn't find anything similar from my searches. It is definitely not a common use case. I do need it to be a textarea though.

I would still like to use this awesome component for that with minimum hacking/modifications. A pass through prop for `autowhatever` would do that for me, I believe.

**Comment by moroshko** [comment]
@ntgn81 Your requirement sounds like an edge case. I don't think at this stage that it's a good idea to add a support for a textarea in `react-autosuggest` because of the complexity it brings with regards to accessibility (e.g. Up/Down navigation). I'd encourage you to find a more common solution to the problem you are trying to solve, or, if you absolutely have to, to fork `react-autosuggest` and implement the behaviour you want. Sorry.

**Comment by ntgn81** [comment]
Not a problem. I totally agree it's a very weird edge case. I'll try to work around it. Thanks alot for responding :D

**Comment by christophercurrie** [comment]
Following up on this old closed issue. One use case for rendering for (a subset of) a text area is for implementing Facebook-style `at-references`, where the the suggestion component renders a list of friends that match the name you're typing into a status update textarea (or other contenteditable block). I can envision a very complex implementation to handle this as-is, where a hidden input is rendered to mirror the text in the textarea being used as the suggestions source. But it would be nice if the suggestion framework itself didn't depend on the source of the suggestion text.
