### ISSUE TITLE
Search full text, not just beginning characters

### ISSUE THREAD

**Issue by davedawson** [moroshko/react-autosuggest#128]
I'd like to be able to set this field to use the search term to match against the full text of the source, not just the begginning of the source. For example:
### Search term: 
`the one`

### Results:

- Neo is **the one** who was...
- **the one** time I ate at Chipotle...

Currently, only the item that begins with the `the one` text will appear. Is there an option to switch to search the full text?

**Comment by jbasrai** [comment]
You can change the logic that you're currently using to set `suggestions`. Forked the Basic Codepen example to illustrate: http://codepen.io/anon/pen/pgXmNP

**Comment by davedawson** [comment]
Oh that's great. I was looking for an option on the component. But this works too. Thanks for that!
