### ISSUE TITLE
Order of execution of onSuggestionSelected option

### ISSUE THREAD

**Issue by jstejada** [moroshko/react-autosuggest#13]
I have a use case where I need the function I pass in as the `onSuggestionSelected` option to be called after the autosuggest has completely re-rendered the list of suggestions, i.e. after it has successfully removed/cleared the list of suggestions.

@moroshko , do you think this would be a good idea to implement?

**Comment by moroshko** [comment]
@jstejada It sounds like `onSuggestionSelected` is not what you need. Could you describe a bit more what's your use case?

**Comment by jstejada** [comment]
So basically my use case is the following:

When a suggestion is selected 1 of 2 things should happen (depending on its type):
  - It should be added to a collection of objects in another view, or
  - It should render a new list of suggestions. These new suggestions are corequisites of the original one, i.e. the user cannot add the initial suggestion to his collection unless he also adds one of the newly rendered suggestions also.

My initial approach to accomplish this for the second case was to manually set the suggestions of my `Autosuggest` when a suggestion is selected via `setSuggestionsState` (since these are independent of the input value).

The problem is that when a suggestion is selected, the suggestions are cleared by setting the state to  `null` asynchronously with `setState`, and then `onSuggestionSelected` is called. If I set any state inside `onSuggestionSelected`, it will be executed before the initial `setState` and re-render has completed.

I realize this use case is pretty specific. What I need is basically a way to manually set the list of suggestions without screwing up the state. That is why I was initially proposing to execute `onSuggestionSelected` only when the call to `setState({suggestions: null})` has completed, but I'm not sure if it would affect other use cases.

Let me know what your thoughts are on this.

Thanks a lot!

**Comment by moroshko** [comment]
@jstejada Sounds like you are implementing quite a complex interaction. I find it a bit confusing that user can still type in the input field after they selected the first tier suggestion. 

* Should the input affect the second tier suggestions in any way? If not, why the input has to be visible at all? I feel like it will confuse users.
* Have you considered to show the second tier items separately, i.e. not as Autosuggest suggestions?

**Comment by jstejada** [comment]
Yes it is a bit complex. To answer your questions: 

- No, the second tier suggestions are not affected by the input value. They are subsets of suggestions belonging to some of the first tier suggestions. My approach is to disable the input when this case occurs. I can show you a couple of screenshots of how it is supposed to work if you want.

- I have considered this actually, the thing is that I need all of the same interactions with the second tier suggestions, i.e. preview, adding, etc. So i wuld basically need to reimplement this stuff again.

**Comment by moroshko** [comment]
@jstejada I feel like what you are trying to achieve is beyond what `react-autosuggest` was designed for.

I don't mind to try and help you if you send me some screenshots, but maybe lets do this via email (michael.moroshko@gmail.com). What do you think?

**Comment by jstejada** [comment]
thanks @moroshko ! it is definitely not a common use-case, but using `react-autosuggest` will absolutely save me most of the work for searching and interacting with search results. Although I do realize the solution for this specific use case might be a little hackish.

I will email with the details and screenshots. Again, thank you so much for your help!

**Comment by moroshko** [comment]
@jstejada 
No worries, glad to help!
