### ISSUE TITLE
Turn off spellcheck on input field

### ISSUE THREAD

**Issue by sushant711** [moroshko/react-autosuggest#130]
Is there a way I can control attributes on input field?

**Comment by jbasrai** [comment]
Anything passed into `inputProps` will be propagated to the input element.

**Comment by sushant711** [comment]
Actually that didn't worked.
Instead this worked perfectl,
```
saveInputRef: function(autosuggest) {
   this.inputRef = autosuggest && autosuggest.input;
   if (this.inputRef) this.inputRef.spellcheck = false;
}

<Autosuggest ...... ref={this.saveInputRef} />
```

**Comment by moroshko** [comment]
@sushant711 Are you sure that adding `spellCheck: false` (note the capital C) to `inputProps` doesn't work? `spellCheck` is listed in the supported attributes in the [docs](https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes).

**Comment by sushant711** [comment]
@moroshko Ah, capital C worked. I should have referred documentation properly. My bad. Thanks for a clear simple solution and thanks for building this awesome library. I tried react-select and many more. None of them had a satisfactory API contract. react-autosuggest has a very minimal yet sufficient contract :)

**Comment by moroshko** [comment]
Thanks @sushant711 :+1:
