### ISSUE TITLE
Can add a tree view?

### ISSUE THREAD

**Issue by siarcarse** [moroshko/react-autosuggest#136]
The plugin is awesome, but tree view even more impressive.... 
something like:
 [rc-tree-select](http://react-component.github.io/tree-select/examples/basic.html)
With multi-selection...
My english is not the best, i am from Chile and i can help us if necessary.
kind regards!

**Comment by moroshko** [comment]
@siarcarse What is your use case for using the Autosuggest with a tree view. This sounds like out of scope for this project.

**Comment by siarcarse** [comment]
I need autocomplete data with subscripts... Apples with subscrips apple red, apple green...
Same for radiological studies like upper extremity, with subscripts arm, elbow, hand, etc...
Only for see the information more clear.
thanks!

**Comment by moroshko** [comment]
You can render multiple section like in [this example](http://codepen.io/moroshko/pen/qbRNjV), and potentially achieve what you want. If you really need the collapse/expand functionality, you'll have to look for another component. This is way beyond what Autosuggest is designed for. Sorry.

**Comment by JesperKihlberg** [comment]
@siarcarse I made a fork of this project, that adds the possibility to show a submenu, is this what you are looking for?
@moroshko Would you be interested in a pull request for this?
![image](https://cloud.githubusercontent.com/assets/4201521/14107277/5ef7f6be-f5b7-11e5-9a36-a3ae1c129fa7.png)

**Comment by moroshko** [comment]
@JesperKihlberg Do you have a demo page where I can see this in action?

**Comment by JesperKihlberg** [comment]
@moroshko yes: http://autosuggest.jesperkihlberg.dk/demo/dist/index.html
