### ISSUE TITLE
Sorting options for suggestion list?

### ISSUE THREAD

**Issue by bricejlin** [moroshko/react-autosuggest#137]
Any plans to add functionality for controlling sorting of suggestions?

**Comment by moroshko** [comment]
@bricejlin Suggestions ordering is completely up to the user. Autosuggest has no opinion on this. You pass it [`suggestions`](https://github.com/moroshko/react-autosuggest#suggestionsProp) which are sorted the way you want them, and Autosuggest will display them in the same order. Does this makes sense?

**Comment by bricejlin** [comment]
@moroshko Ah i see. thanks!
