### ISSUE TITLE
Get Title of MultiSection in onSuggestionSelected 

### ISSUE THREAD

**Issue by DonKanallie** [moroshko/react-autosuggest#139]
Hey, 
is there a way to get the sectionTitle of a selected Value in the onSuggestionSelected Function when multiSection is activated?

Thanks

**Comment by moroshko** [comment]
@DonKanallie At the moment, there is no way to know which section the selected suggestion belongs to.  The only thing you can probably do is to look up the selected `suggestion` in your `suggestions`.

We can add `sectionIndex` to the info that `onSuggestionSelected` provides:
```js
function onSuggestionSelected(event, { suggestion, suggestionValue, sectionIndex, method })
```

Would that solve the problem for you?

**Comment by DonKanallie** [comment]
The string would be better, but index would also do the trick. At the moment i have loaded columns of a db and these are my titles and the content my values. I'm just trying to build a WHERE statement for the next query out of the selected Values, therefor i need the Column names.

**Comment by moroshko** [comment]
@DonKanallie Autosuggest has no knowledge of section titles (i.e. the strings that you want). It's totally up to you how you implement [`renderSectionTitle()`](https://github.com/moroshko/react-autosuggest#renderSectionTitleProp). So, the only reasonable thing would be to provide `sectionIndex`, as I suggestion above.

**Comment by DonKanallie** [comment]
ok, yeah index would do it. Thanks!

**Comment by moroshko** [comment]
[Enjoy!](https://github.com/moroshko/react-autosuggest/releases/tag/v3.7.0)
