### ISSUE TITLE
Please support input `valueLink`

### ISSUE THREAD

**Issue by colllin** [moroshko/react-autosuggest#142]
These `propTypes` validations prevent the use of the `valueLink` prop on the input:

https://github.com/moroshko/react-autosuggest/blob/16eae00bf1cc7377990410483cae6184f45198ac/src/AutosuggestContainer.js#L59

More about `valueLink`:

https://facebook.github.io/react/docs/two-way-binding-helpers.html

Please support `valueLink`, or consider delegating to a real `<input>` somewhere if you're not already, so that you don't need to re-implement or wrap native React functionality.

**Comment by moroshko** [comment]
I'm going to pass on this one because [`valueLink` is deprecated since React 15.0](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#new-deprecations-introduced-with-a-warning).

**Comment by colllin** [comment]
Lucky timing.  Probably still a worthwhile suggestion not to re-implement input properties yourself.  You could just pass them through.

**Comment by moroshko** [comment]
@colllin What input properties are we talking about. Autosuggest passes `inputProps` to the `<input>` element.
