### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by adack123** [moroshko/react-autosuggest#143]
Hey dudes,

Really enjoy what you guys have done here. I did have a quick question / feature request. Do you all have plans to include functionality for a combobox? As in, when the input is focused display all the results of the suggestions container in the dropdown.

**Comment by moroshko** [comment]
@adack123 You can achieve the behaviour that you want if you provide `suggestions={<all suggestions>}` to Autosuggest when `inputProps.value` is blank.

**Comment by adack123** [comment]
@moroshko Thanks for the reply! I'm not sure I completely understand, excuse my naivety. Taking the example code from readme Are you saying that when `inputProps.value` I'm going to pass the entire languages array to suggestions prop?

**Comment by moroshko** [comment]
Yes. All you need is to change:
```js
function getSuggestions(value) {
  ...
  return inputLength === 0 ? [] : ...
}
```
to:
```js
function getSuggestions(value) {
  ...
  return inputLength === 0 ? allSuggestions : ...
}
```

**Comment by adack123** [comment]
Hey @moroshko,

I went ahead and tried that out this morning. I'm not sure this is generating the desired effect I'm looking for. To double check I went ahead and also dropped that into one of the codepen examples and couldn't generate the desired effect. 

When I make this change on an initial click in the input or focus I still don't get a dropdown with the desired language options. Any thoughts?

```javascript

function getSuggestions(value) {
  const inputValue = value.trim().toLowerCase();
  const inputLength = inputValue.length;

  return inputLength === 0 ? languages : languages.filter(lang =>
    lang.name.toLowerCase().slice(0, inputLength) === inputValue
  );
}

```

**Comment by adack123** [comment]
Not sure if this is a hacky way of doing it but I did solve the problem I was having. 

Because the default for suggestions is to render when the input field is black... I overrode with this. 

```javascript
shouldRenderSuggestions(value) {
    return value.length >= 0;
  }
```
Having that plus returning the entire array when `inputLength === 0` gave me the combobox functionality I was looking for. Thanks for your help!
