### ISSUE TITLE
update peer dependency to react 15.0.0

### ISSUE THREAD

**Issue by tavelli** [moroshko/react-autosuggest#144]
getting error on npm install, doesn't seem to like the ^15.0.0-rc.1

**Comment by SwaroopH** [comment]
@tavelli I sent a PR - see if that resolves it for you?

https://github.com/moroshko/react-autosuggest/pull/145

**Comment by tavelli** [comment]
@SwaroopH yea that does the trick. thanks!

**Comment by moroshko** [comment]
@tavelli What `npm` version do you use?

**Comment by tavelli** [comment]
@moroshko  using node 4.2.4 and npm 2.14.12

**Comment by moroshko** [comment]
Fixed in [3.7.1](https://github.com/moroshko/react-autosuggest/releases/tag/v3.7.1)
