### ISSUE TITLE
Focus first matching item

### ISSUE THREAD

**Issue by CLL80** [moroshko/react-autosuggest#147]
Is there a way to focus the first matching item? For example, when typing 'react' with the suggestions 'angular', 'react', 'react autosuggest', and 'javascript', 'react' would be focused.

**Comment by moroshko** [comment]
@CLL80 At the moment, there is no API to do that. Do you know any examples online that implement this behaviour?

**Comment by CLL80** [comment]
The Combobox (Dropdown + Autosize): section [here](http://alexkuz.github.io/react-input-enhancements/) does it. It would essentially be focusing the first suggestion that is returned. I tried seeing if I could pass focusedItemIndex or focusedSuggestionIndex to the AutoWhatever component from the Autosuggest component but had no luck with this.

**Comment by mauriciosoares** [comment]
That's a nice feature request, I'd make use of that too...

**Comment by snakeyak** [comment]
Very useful feature, would be great. Especially useful when the user types the exact value as suggested, why should he need to click on top of typing
