### ISSUE TITLE
react-autowhatever dependency installs multiple react instances on npm2.

### ISSUE THREAD

**Issue by efegurkan** [moroshko/react-autosuggest#151]
Hello, 
Just a heads up.
Because of react-autowhatever dependency is declared as ^3.1.0 for version react-autosuggest@3.6.0, it installs react-autowhatever@3.2.1 as a dependency. Which has a peerDependency of react ^15.0.1.

On npm 2 peer dependencies auto installed, so if you still use react@0.14.x npm will install multiple instances of react.

As a workaround you can explicitly set react-autowhatever version on your package.json or use shrinkwrap.

**Comment by moroshko** [comment]
@efegurkan Could you please check if it is still an issue in 3.7.3?

**Comment by efegurkan** [comment]
@moroshko yep that looks like fixed. Thanks for fast response.
