### ISSUE TITLE
Force dropdown to open

### ISSUE THREAD

**Issue by mauriciosoares** [moroshko/react-autosuggest#152]
Hey!

Is there a way I can force the drowdown to open with the latest suggestions filled, without having to focus on the input?

My idea is to set the focus on the callback of another event...

Thanks!

**Comment by moroshko** [comment]
Yeah, setting the focus programatically should do the trick.

**Comment by mauriciosoares** [comment]
I see, I'll do some tests then...

I'll tell you later if I succeeded :)

Thanks

**Comment by mauriciosoares** [comment]
worked like a charm! thanks @moroshko

**Comment by dannybloe** [comment]
Maybe a silly question but how can I achieve this? I use the component as a combobox with a tiny arrows button superimposed on the component. I want to toggle the suggestions panel when the user clicks this button (similar to a select element). I'm not sure how to achieve this.

**Comment by mauriciosoares** [comment]
@dannybloe To be honest it's been a while since I've done it, and I'm not 100% sure the answer I'll give you is the correct one... But the idea is set a ref in the `AutoSuggest` component, and get the input DOM reference and triggering `.focus()` on it

```
<AutoSuggest ref="suggest" />


this.refs.suggest.getElementsByTagName('input')[0].focus()
```

That might do the trick

**Comment by moroshko** [comment]
@dannybloe Something like [this](http://codepen.io/moroshko/pen/LRQrqG?editors=0010)?

**Comment by dannybloe** [comment]
Ah, almost. I'd like the button to behave as a toggle: when it is expanded, it should collapse and vice-versa. I can't find a  way to close the suggestions container.

**Comment by moroshko** [comment]
@dannybloe Does [this](http://codepen.io/moroshko/pen/yaKqEg) help?

**Comment by dannybloe** [comment]
YES!! Thanks. You rock!
Maybe an idea to expose a method on the control to do this? Or something like this?

**Comment by moroshko** [comment]
I'll think about this.

**Comment by lorenzos** [comment]
@moroshko I need to force dropdown, but my case is quite different and your example do not work.

Simplifying my logic, I have an autosuggest input that fetches suggestion filtering a bigger state array. Let's say my state is like:

    { 
        allPossibleSuggestions: [],
        suggestions: [], // Filled by onSuggestionsFetchRequested, filtering the previous array with user input
    }

The fact is that `allPossibleSuggestions` changes asynchronously. How can I "force" `onSuggestionsFetchRequested` when this happens, considering that the user may be or may be not focusing the autosuggest field, with or without text already entered?
