### ISSUE TITLE
Patch to 2.X with support for React 15

### ISSUE THREAD

**Issue by cassiozen** [moroshko/react-autosuggest#154]
Hi, I'm the author of the "Pro React" book by Apress - In the chapter 6 of the book there is an exercise that uses react-autosuggest 2.x.
I'm updating all sample code to use React 15, but I'm having troubles with this specific exercise (since react-autosuggest 2.x requires React 0.14 as a peer dependency).

I created a fork of the project that builds on top of version 2.2.5 bringing React to 15.0 (and bumping other dependencies versions as well, such as Babel).

I think this would be useful not only to my specific case but for other developers and projects using the 2.x API and wanting to migrate to React 15. 

What are your thoughts on publishing a patch 2.3 version on NPM (without updating the latest, of course)?

**Comment by moroshko** [comment]
Have you considered to upgrade your example to react-autosuggest 3.0? I be happy to help you with the migration.

**Comment by cassiozen** [comment]
Hi @moroshko, thanks for your prompt response. I do use autosuggest 3 on other projects, and on future editions of the book I will certainly update the source to autosuggest 3. In this specific case, though I want keep the book sample codes unchanged (just the dependencies) - so it keeps easier for readers to follow up.

**Comment by moroshko** [comment]
There are no plans to keep maintaining 2.x. If upgrading to 3.x is not an option, you'll probably have to point readers to your fork. Sorry.
