### ISSUE TITLE
On change Method is defined but never used

### ISSUE THREAD

**Issue by vivinRajagopalan** [moroshko/react-autosuggest#156]
Hi ,

I am trying this for the first time and when i was trying to implement a simple auto complete, The onchange function that is used in the signature of input props always throguh an error saying that the method is defined but not used. what could be the reason ? Please let me know. Thanks

**Comment by moroshko** [comment]
Could you create a Codepen example that demonstrates the issue? [Some examples for reference](http://codepen.io/collection/DkkYaQ/)
