### ISSUE TITLE
How to use react-autosuggest in redux

### ISSUE THREAD

**Issue by appbank2020** [moroshko/react-autosuggest#159]
Hi,
I am gonna use autosuggest in redux.
autosuggest works very well in flux, but i need to wrap in redux form.
Can you help me?
Please give me example for redux.
Thank you very much.

**Comment by moroshko** [comment]
The is a link in the README to a bunch of [Codepen examples](http://codepen.io/collection/DkkYaQ/).
[One of them is what you want.](http://codepen.io/moroshko/pen/ZQLyNK)

**Comment by tonyxiao** [comment]
On a somewhat related note, I see that `react-autosuggest` creates a redux store internally to manage its own state. Is there any reason it's a purely internal store rather than allowing users to pass in a store to be used? @moroshko

**Comment by moroshko** [comment]
@tonyxiao What would you gain if you allowed to pass in a store to Autosuggest? Who would be responsible to update this store? Could you provide some code that illustrates your idea?

**Comment by tonyxiao** [comment]
More thinking along the lines of debugging purposes. Time travel for example would be able to apply to autosuggest. Autosuggest would export reducers / actions and update its own part of the state tree. http://redux-form.com/6.0.2/docs/GettingStarted.md/

**Comment by moroshko** [comment]
@tonyxiao Just wanted to let you know that `redux` and `react-redux` dependencies were removed in [v8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0).
