### ISSUE TITLE
closeOnSelect or selectMultiple option

### ISSUE THREAD

**Issue by jstejada** [moroshko/react-autosuggest#16]
hi @moroshko ! me again.

I was wondering what you thought of an option to prevent the `Autosuggest` from closing when a suggestion is selected. This would allow users to select more than one suggestion, and I believe it might be a common use case.

Let me know what you think. Thanks!

**Comment by moroshko** [comment]
@jstejada Sounds reasonable. However, it's going a bit to a direction of a custom multi-select dropdown (I mean something like [this](http://react.rocks/tag/Multiselect) or [this](https://www.npmjs.com/package/react-multiselect)).

The idea of Autosuggest component is to assist user to select an option. If you give user the ability to select multiple options, they'll probably also want an option to view/browse all the available options (without typing anything).

[Here](http://www.realestate.com.au/) you can see an example that allows user to select multiple items, which is effectively the same as assigning multiple tags to a question on StackOverflow. But, in both examples, the suggestions list is closed once you select a suggestion, and you have to start typing again to select another suggestion.

Do you know any live examples that implement the functionality that you are after? Is that something that you need in your project? (if yes, could you please describe the use case?)

**Comment by jstejada** [comment]
@moroshko thanks for your response!

Yes, all of your arguments are correct, it would definitely be going in the direction of a multi-select dropdown like the examples you shared, which maybe is a bit out of the scope of react-autosuggest, or may require too much work. 

The initial way I had imagined it is that `onSuggestionSelected` would be called every time a suggestion was selected, and it would be up to the developer to handle each call appropriately given his needs, and to decide wether or not to close the dropdown.

Specifically for my project, the use case I need is being able to prevent the dropdown from closing. As I've mentioned before, in my app users can add suggestions to a collection by selecting them. Sometimes suggestions may conflict with items that are already in the collection, so they can't be added. Users are able to observe the conflict because of the preview that is displayed when a suggestion is focused. If the user selects a conflicting suggestion it won't be added, but the problem is that the dropdown is closed regardless. If the suggestion can't be added, I would like to keep the dropdown open so that the user can keep browsing other suggestions without having to type the search query again.

Thanks!

**Comment by moroshko** [comment]
@jstejada UX-wise, I'd suggest not to show suggestions that can't be selected. IMHO it just pollutes the view and can set the wrong expectation. Can you filter out the previously selected suggestions?

**Comment by jstejada** [comment]
@moroshko yes, I totally agree. The thing is that in this specific use case, the suggestions are events that can be added to a weekly calendar (more specifically, they are courses from a college course catalog, which have events). When a suggestion is focused, it shows the preview of the event in the calendar, i.e. the times of the event and where it would be placed in the calendar.

When an even't can't be added it will be shown in the preview because it is conflicting with another event, so users are actually interested in seeing this; they want to know why they can't add that event. Also, if they don't see the suggestion they will get confused as to why it doesn't appear since they are expecting to see all results.

I know this because the app has been deployed for a while already and we know how our users use it, but we are reimplementing a new version of the front-end in React. It's called Academical, its a class schedule planner for college students. You can see the current (old) version at uniandes.academical.co if you are curious (it's in spanish though)

In any case, an option like closeOnSelect (which would default to true) would be incredibly helpful for this use case.

thanks again!

**Comment by moroshko** [comment]
@jstejada Thanks for the pointer to [uniandes.academical.co](http://uniandes.academical.co), it really helps to understand what you are trying to achieve! I couldn't figure out though how to add courses, so I never see any suggestions :(

One thing that I noticed in the video is that when suggestion is clicked, the value in the input is **not** changed, which is different from the current behaviour. Also, according to [WAI-ARIA guidelines](http://www.w3.org/TR/wai-aria-practices/#autocomplete):

> Press Enter to select the highlighted choice and close the drop-down list. This mimics the behaviour of the HTML select element.

It looks like you want a different behaviour, i.e. **not to close** the suggestions on Enter, which is contradicting to the above. I'm not sure what to do about this.

I start to wonder whether Autosuggest is the right type of component for you. Maybe you need something like multi-select dropdown?

I guess we could add `closeOnSelect="false"` option, but this would mean not to close the suggestions _every time suggestion is selected_. I can easily see someone else wants to implement an Autosuggest with "disabled" items, i.e. items that cannot be selected. The major difference though, is that "enabled" suggestions **should** close the suggestions list in this case. In other words, I think that `closeOnSelect="false"` is probably not a good idea.

Another option I thought of is not to close the suggestions list if `onSuggestionSelected` returns a specific value. But, I'm not sure if that would solve all your issues (especially the fact that the input value shouldn't change when suggestion is selected).

**Comment by jstejada** [comment]
@moroshko thanks for your comments!

Yes, the thing is that the old version you saw doesn't really use an autosuggest, just a regular list of results and an input. We are implementing the autosuggest for the new version.

Regarding your comments on the `closeOnSelect` option, you are right its probably not the best solution. The proper model would be to have a notion of disabled and enabled items, and only the enabled items would be selectable and thus close the suggestion list.

The option of returning a specific value in `onSuggestionSelected` sounds viable, but I'm not sure I follow the problem you mention that the input value shouldn't change when suggestion is selected?

**Comment by moroshko** [comment]
@jstejada Are you happy to close the suggestions list when an enabled item is added? If yes, than please ignore the problem I mentioned. 
Is the only thing that is missing for you at the moment is not allowing users to select certain suggestions (disabled ones)?

**Comment by jstejada** [comment]
Yes, exactly. I am happy to close the suggestion list when an enabled item is added, and what I need right now is not allowing users to select disabled suggestions.
Returning a specific value from `onSuggestionSelected` seems like a straightforward solution to determine if a suggestion is enabled or disabled.

**Comment by moroshko** [comment]
@jstejada Another option is to have a special key in suggestion objects, say `disabled`. If `suggestionObj.disabled === true`, then selecting this suggestion using mouse or keyboard will have no effect. Does this sound reasonable?

**Comment by jstejada** [comment]
@moroshko yes, that should work! do you want me to go ahead and create a pull request?

**Comment by moroshko** [comment]
@jstejada I feel like we are going too far here. The original purpose of react-autosuggest is to help users to fill in a certain field faster by typing less.

As far as I can see, what you are trying to achieve is a filter (or a search field), with results displayed below. The ultimate purpose of your users is not to fill in a certain field. They probably just want to see a list of available courses, and you are trying to help them to filter out the relevant courses based on their query. This is a search/filter functionality, not an autosuggest.

I don't want this component to become a big thing that can do everything. Disabled items don't really help users to fill in the field faster. I believe that an autosuggest component should not have disabled items at all. The fact that you need disabled items suggests that maybe autosuggest is not the best component for you. Sorry.

**Comment by jstejada** [comment]
@moroshko no worries! Thanks anyway for your attention!
