### ISSUE TITLE
Programmatically close suggestions-container

### ISSUE THREAD

**Issue by web2style** [moroshko/react-autosuggest#160]
Is it possible to close `.react-autosuggest__suggestions-container` programmatically?

```
this.refs.autosuggest.close()
```
Is there smth like this?

**Comment by moroshko** [comment]
Could you share your use case? What would you want to do that?

**Comment by web2style** [comment]
Thanks for the reply, I no longer need it.

**Comment by thomasbottonari** [comment]
I have a use case for this feature. I would like to wrap react-autosuggest in parent component that composes a button below the dropdown list that would allow you to add a suggestion if it doesn't exist in the list you are seeing. Currently, anytime you blur from the input it closes automatically, so it closes before you can press that button. I would like a closeOnBlur prop that I can set to false and then the ability to call this.refs.autosuggest.close() when I want.

**Comment by alex-shamshurin** [comment]
And how to open it programmatically?
