### ISSUE TITLE
Add focus() function to component

### ISSUE THREAD

**Issue by szyablitsky** [moroshko/react-autosuggest#167]
I'm using this component inside of https://github.com/olahol/react-tagsinput.
It's working great in general, but `react-tagsinput` calls `focus()` on input when user clicks anywhere inside control area. It would be great if we can pass this `focus()` call to the input of `react-autosuggest`.

**Comment by moroshko** [comment]
@szyablitsky You can [get the input field](https://github.com/moroshko/react-autosuggest/blob/master/FAQ.md#how-do-i-get-the-input-field) and then call `.focus()` whenever you need. Is that what you are after, or did I misunderstood your request?

**Comment by szyablitsky** [comment]
@moroshko thank you! That's exactly what I was looking for.
