### ISSUE TITLE
autofocus support?

### ISSUE THREAD

**Issue by spinus** [moroshko/react-autosuggest#17]
Hi, how I can add autofocus to input field?

I've tried something like:
```jsx
 <Autosuggest                                                          
              inputAttributes={{                                                  
               value: this.state.query || '',                                    
               autofocus: true,                                                  
               placeholder: this.props.placeholder}}                              
               suggestions={this.props.on_get_suggestions}/> 
```
but does not work.

**Comment by moroshko** [comment]
Have a look how it's done in [examples](http://moroshko.github.io/react-autosuggest). This works:

    <Autosuggest suggestions={getSuggestions}
                 inputAttributes={{ id: 'yourInputId' }}
                 ref={ () => { document.getElementById('yourInputId').focus(); } } />

You can also try this approach:

    <Autosuggest suggestions={getSuggestions}
                 ref="autosuggest"
                 ref={ () => { React.findDOMNode(this.refs.autosuggest.refs.input).focus(); } } />

Also, when you tried the `autofocus="true"` approach, did you put the `<Autosuggest>` inside a `<form>`?

**Comment by jstejada** [comment]
@spinus I believe that React supports autofocus as `autoFocus` , i.e. camelized: https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

Maybe that is your issue?

**Comment by spinus** [comment]
@moroshko I didn't put tag inside form, I wasn't doing a form, I'll try this anyway.
Thank you for example, I missed that.

@jstejada I'll try today and report.

**Comment by moroshko** [comment]
@spinus Any luck?

**Comment by spinus** [comment]
@moroshko: Sorry I forgot to report!
@moroshko, @jstejada inputAttributes={{autoFocus:true}} works like a charm. Thank you!
@moroshko I didn't try other stuff because I like this simple one :-)

**Comment by nickbouton** [comment]
Using the 2.0 branch right now, `autoFocus: true` in `inputAttributes` is not working for me -- it's not being passed through to the child input.

**Comment by denisnazarov** [comment]
`autoFocus: true` should go into `inputProps`:

```
<Autosuggest inputProps={{autoFocus: true}} />
```

**Comment by doubledherin** [comment]
This did not work for me: `<Autosuggest inputProps={{autoFocus: true}} />`

This does: `<Autosuggest inputProps={{autofocus: 'autofocus'}} />`

Then I get the React warning about camelcase. But using camelCase doesn't work I tried every variation I could think of. Other camelcasing in input props (such as onChange) works though.

**Comment by Bhush98** [comment]
Hi Guys,

I am using the latest version and autoFocus doesn't work. Please find the methods I tried below

1: inputProps={{ autoFocus : true }}
2: inputProps={{ autofocus : true }}
3: inputProps={{ autoFocus : 'autofocus' }}
4: inputProps={{ autoFocus : 'autofocus' }}

And when inspected the property autoFocus in VS code it requires a boolean value. so "autoFocus : true" should work but it's not working

**Comment by Bhush98** [comment]
> Have a look how it's done in [examples](http://moroshko.github.io/react-autosuggest). This works:
> 
> ```
> <Autosuggest suggestions={getSuggestions}
>              inputAttributes={{ id: 'yourInputId' }}
>              ref={ () => { document.getElementById('yourInputId').focus(); } } />
> ```
> 
> You can also try this approach:
> 
> ```
> <Autosuggest suggestions={getSuggestions}
>              ref="autosuggest"
>              ref={ () => { React.findDOMNode(this.refs.autosuggest.refs.input).focus(); } } />
> ```
> 
> Also, when you tried the `autofocus="true"` approach, did you put the `<Autosuggest>` inside a `<form>`?

This method worked for me and yes my AutoSuggest component is not inside a form tag
