### ISSUE TITLE
Handling user editing of selection and clear

### ISSUE THREAD

**Issue by pathsny** [moroshko/react-autosuggest#173]
When input props include type: 'search', the search box is rendered with a special "clear" button that allows the user to clear the input. However, when this happens, the "selectedValue" happens to remain the last selection that was made.

There is a similar issue when the user edits the text after a selection was made, but did not choose a selection, but this is probably less of an issue.

Whats the best way to handle something like this?

**Comment by moroshko** [comment]
Hey @pathsny,
I'm not sure what you mean by:
> However, when this happens, the "selectedValue" happens to remain the last selection that was made.

[Here](http://codepen.io/moroshko/pen/YqmNXE) is an example with `type: 'search'`. If I do:

1. Type 'c'
2. Click the clear icon

the input value is cleared, as expected.

Could you elaborate on the issue a bit more, and provide steps to reproduce?

**Comment by pathsny** [comment]
sure. To give you a bit more context, I'm using this component inside a form. The form is submitted only after the user fills in all fields. 
Steps
1) Type C
2) Select the first item in the suggestions
3) click the clear icon.

Now subsequently if the user submits, to the user the submitted value is "", whereas in actuality the selected value is something else that is not visible to them.

**Comment by moroshko** [comment]
@pathsny I still can't reproduce what you are describing. Have a look at [this pen](http://codepen.io/moroshko/pen/VaobRb). I do the following:

1. Click the input field to focus on it
2. Type `c`
3. Click on the first suggestion
4. Click the clear icon
5. Click the submit button

At this state, in the console I see that an empty value was submitted, which is exactly what users expect.

What am I missing?

**Comment by moroshko** [comment]
@pathsny Can I ask where do you use react-autosuggest?

**Comment by pathsny** [comment]
Hi @moroshko. I use react-autosuggest on an app that's not publicly available as of yet.
However, I have forked your pen to demonstrate the problem I was describing.
http://codepen.io/pathsny/pen/PNMywb?editors=1111

1. Click the input field to focus on it
2. Type `c`
3. Click on the first suggestion
4. Click the submit button, see console
5. Click the clear icon
6. Click the submit button again, see console

(A similar thing would happen if the user edited C++ to be C-- for example)

- Note that instead of using a ref, I have attached a handler to onSuggestionSelected and I save the selection in the state.  
- The submission is the actual selection and not the input box contents, and this includes the "year" for example. (in my actual use case, this includes the unique id of the selected object).

I suspect that the correct approach is to subscribe to onChange on the input and use that to set the selection in the state back to null, unless the text value of the input and the selection are identical

**Comment by moroshko** [comment]
@pathsny You're right. Just update the state in the `onChange` handler. Note that [you have access to `method` in the `onChange` handler](https://github.com/moroshko/react-autosuggest#inputprops-required), so you can know, for example, whether the change has occurred as a result of suggestion selection or not.

**Comment by pathsny** [comment]
makes sense, thanks!

**Comment by moroshko** [comment]
You're welcome!
