### ISSUE TITLE
Is the scroll functionality still broken?

### ISSUE THREAD

**Issue by TimCostrop** [moroshko/react-autosuggest#177]
When applied with a fixed height and overflow-y: scroll, it is possible to use the scrollbar with the mouse, but when using the arrow keys, the component does not scroll along?

**Comment by moroshko** [comment]
There is one known issue which #153 addresses.
Do you experience a different issue?
Note that the [Codepen examples](http://codepen.io/collection/DkkYaQ/) still use an old version of react-autosuggest, which doesn't have the scroll functionality.

**Comment by moroshko** [comment]
Closing this one for now.
