### ISSUE TITLE
Select section title

### ISSUE THREAD

**Issue by sophy-cat** [moroshko/react-autosuggest#179]
I would like to select both the suggestions and also the section title since my search is implemented to search for both.
I tried to achieve this using the `renderSectionTitle` like so:

```js
renderSectionTitle(section) {
  return (
    <span onClick={this.handleSectionClick}>{section.title}</span>
  );
}
```
and then I would do the necessary actions in the function `handleSectionClick`, but for some reason the click is never called.

Is there any way to do this?

**Comment by moroshko** [comment]
Good question!

The issue is that when the input is blurred we hide the suggestions, and this happens before your `onClick` is called. 

You can use `onMouseDown` instead. [Example](http://codepen.io/moroshko/pen/vKRZzL)

Does this help?
