### ISSUE TITLE
Best practice to show up value different from the internal

### ISSUE THREAD

**Issue by dmitry** [moroshko/react-autosuggest#18]
For example, I have a suggestions with the following JSON:

```json
[
  {"name": "John", "id": 1},
  {"name": "James", "id": 2}
]
```

How would I show up the `John` as a selected suggestion, but use `1` (id) as a value to post with a form?

I can think of only one solution, hide input with a `id` value, and show `name` in `span` or `div` tag.

How do you deal with following situations?

**Comment by moroshko** [comment]
@dmitry If that's what you want to do, I'd say that autosuggest is the wrong component for this task. You should probably use a select box (dropdown). With autosuggest users are allowed to type a free text (and submit it with the form), while you probably want to force user to select one of the presented options and not allowing them to submit a free text. Does this make sense?

**Comment by dmitry** [comment]
@moroshko yes, you are correct, something like dropdown with the autocomplete (and with ajax request for every input change) similar to https://select2.github.io/examples.html is a better match. But the same solution can be completed with `react-autosuggest`, but I found the only one way how to do that (described this method in the topic). What I like so far about the `react-autosuggest` - it's easy to read, customize and it uses BEM. :+1:

**Comment by moroshko** [comment]
@dmitry Glad you found an alternative that suits better your needs. Thanks for the kind words about `react-autosuggest`!
