### ISSUE TITLE
Example code seems to be broken

### ISSUE THREAD

**Issue by omanamos** [moroshko/react-autosuggest#181]
Seems like onChange method in the example code expects `newValue` to be a string, when it actually looks more like this: `Object {newValue: "c", method: "type"}`

Am I doing something wrong, is that just a typo?

**Comment by ThibWeb** [comment]
Are you referring to https://github.com/moroshko/react-autosuggest/blob/master/demo/src/components/App/components/Examples/components/Basic/Basic.js#L47?

```js
onChange(event, { newValue }) {
    this.setState({
      value: newValue
    });
  }
```

That syntax is ES6 destructuring, it would be the same as the ES5:

```js
onChange: function onChange(event, update) {
    this.setState({
      value: update.newValue
    });
  }
```
