### ISSUE TITLE
Pasting the exact value of suggestion does not trigger onChange

### ISSUE THREAD

**Issue by snakeyak** [moroshko/react-autosuggest#182]
Hi,

I noticed that if I paste the exact value of a suggestion into the input, onChange() from inputProps is not triggered. As a result, when I click the resulting suggestion (which is the same as the pasted value)  it will not work.

This is the case when used exactly as suggested in the examples:

```
render() {
    const { value, suggestions } = this.state;
    const inputProps = {
      placeholder: 'Type a programming language',
      value,
      onChange: this.onChange //this will not be triggered
    };

    return (
      <Autosuggest suggestions={suggestions}
                   onSuggestionsUpdateRequested={this.onSuggestionsUpdateRequested}
                   getSuggestionValue={getSuggestionValue}
                   renderSuggestion={renderSuggestion}
                   inputProps={inputProps} />
    );
  }
```

**Comment by moroshko** [comment]
@snakeyak By definition, `onChange` is supposed to be triggered when the value of the input changes. If you paste exactly the same value, there is no change, and therefore `onChange` is not triggered. 

What is the actual issue that you're experiencing?
