### ISSUE TITLE
Show suggestions at the top

### ISSUE THREAD

**Issue by Wikunia** [moroshko/react-autosuggest#183]
Is it possible to show suggestions above the input field?
Can some one provide a theme or would be nice if it's a simple prop for the component.
Thanks in advance!

**Comment by cpsubrian** [comment]
@Wikunia You should be able to use some combination of `transform: translateY(-100%)` and `margin-top: -[height of input field]px` in your css. Those would be on the `suggestionsContainer`.

**Comment by moroshko** [comment]
@Wikunia Autosuggest has no opinion on styling, but provides hooks to style it via [`theme`](https://github.com/moroshko/react-autosuggest#themeProp).
