### ISSUE TITLE
empty input, on click show auto suggest

### ISSUE THREAD

**Issue by Kepro** [moroshko/react-autosuggest#187]
i want to show on click on empty input a options that can user select, it's possible to show autosuggest on click? like chosen or other libraries?

because shouldRenderSuggestions doesn't fired onClick into input

**Comment by ducwings** [comment]
Related:
https://github.com/moroshko/react-autosuggest/issues/131

**Comment by tachang** [comment]
shouldRenderSuggestions doesn't seem to work even when I just do a return true;

**Comment by moroshko** [comment]
I created a [Codepen](http://codepen.io/moroshko/pen/BzAwkQ) that shows suggestions when input is empty. Does this help?

**Comment by moroshko** [comment]
Closing for now, but happy to reopen if you can demonstrate the issue you're experiencing.
