### ISSUE TITLE
Suggestion list disappears on scrolling when autosuggest is used in angular ui bootstrap modal

### ISSUE THREAD

**Issue by shreyabharadwaj** [moroshko/react-autosuggest#194]
The suggestion list rendered by the autosuggest component disappears on scrolling the suggestion list using the mouse left click when the autosuggest component is used in a angular ui bootstrap modal popup. This issue is replicated in Chrome, Firefox as well as IE11.

**Comment by ThibWeb** [comment]
This is rather specific, and I can't reproduce it readily with the examples on http://react-autosuggest.js.org/. Could you provide a running example of this behaviour?

**Comment by moroshko** [comment]
@shreyabharadwaj Any luck creating a minimal runnable example that demonstrates the issue?
