### ISSUE TITLE
webjars/requireJS script error

### ISSUE THREAD

**Issue by jehrlich** [moroshko/react-autosuggest#195]
Using ` "org.webjars.npm" % "react-autosuggest" % "3.7.3"` as an AMD module with RequireJS, requirejs tries to load react from the wrong location, ignoring the path in my requirejs.config

`   require.config({
        paths: {
            jquery: "../lib/jquery/jquery",
            bootstrap: "../lib/bootstrap/js/bootstrap",
            react: '../lib/react/react',
            reactdom: '../lib/react-dom/dist/react-dom',
            autosuggest: '../lib/react-autosuggest/dist/standalone/autosuggest'
        },
        shim: {
            bootstrap: {
                deps: ["jquery"]
            },
            reactdom: {
                deps: ["react"]
             },
    });` 

This results in a (failed) 'GET React' using the path of my normal js assets folder when autosuggest tells requirejs to load React as a dependency, though React has already been loaded as a lib. I believe this is due to a single-letter error in the webjars version of autosuggest.js. Specifically, line 5 below:

`(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("React"));
	else if(typeof define === 'function' && define.amd)
		define(["React"], factory);
	else if(typeof exports === 'object')
		exports["Autosuggest"] = factory(require("React"));
	else
		root["Autosuggest"] = factory(root["React"]);
})(this, function(__WEBPACK_EXTERNAL_MODULE_2__) {`

`define(["React"], factory);`
should be 
`define(["react"], factory);`

Perhaps I am misunderstanding requirejs or webjars, but making the R->r change solved the problem for me.

**Comment by moroshko** [comment]
Sounds like a [WebJars](http://www.webjars.org/) issue, rather than a `react-autosuggest` issue. I suggest you open a PR there.
