### ISSUE TITLE
smarter search

### ISSUE THREAD

**Issue by charliedotau** [moroshko/react-autosuggest#196]
Hi there,

I have a feature suggestion.

I am using AutoSuggest to provide a searchable list of Australian suburbs.     A search for 'Warandyte' would return suburbs 'Warrandyte', and 'Warrandyte South' but unfortunately not 'North Warrandyte'.      

My understanding is the component's search algorithm does not support this.   If so, would you consider adding this as a feature?

thanks. Love your work.

**Comment by moroshko** [comment]
react-autosuggest doesn't have any opinion on the search algorithm. It's totally up to you to implement it. Check out [autosuggest-trie](https://github.com/moroshko/autosuggest-trie)

**Comment by charliedotau** [comment]
ok. gotcha.    thanks for that.
