### ISSUE TITLE
Show suggestions on focus. 

### ISSUE THREAD

**Issue by arackaf** [moroshko/react-autosuggest#197]
I'm trying to show suggestions as soon as the input is focused.  After reading through the docs and experimenting, it seems as though 

`this.shouldRenderSuggestions = () => true`

is what I want, and that does seem to be just about perfect.  But, when I _right_ click on one of the suggestions, I wind up not being able to get rid of the suggestions. 

Is this a bug - you _can_ repro in the codepen demo.  Type C, right click a suggestion, then click away to kill the context menu, and no outside clicking will close the suggestions list

http://codepen.io/moroshko/pen/JGrGgy

**Comment by arackaf** [comment]
It appears as though the main trick for "always" showing suggestions (or at least showing them when the input has been focused) is to blur the input after something's been selected - otherwise the input stays focused, and clicking it again, after choosing an item does not re-show the suggestions (even if you've manually cleared the value).

This appears to be the best hack I can get working

setTimeout(() => this.input.blur(), 1);

with

`ref={el => { if (el && el.input){ this.input = el.input; } }}`

Which mainly leaves the right-click bug mentioned above.  Is that a known bug?

**Comment by arackaf** [comment]
Hm - it appears as though adding

`onContextMenu: onClick`

to line 1719 of autosuggest.js in `dist/standalone` (which *seems* to be from line 121 in autowhatever.js, though I'm seeing a touch event that's not there) has the decent workaround of setting the value clicked on, with the unfortunate side effect of still showing the context menu.  I think the event model of React makes this the best option available (since the bubbling can't be stopped from within React).

Would you take a PR adding this?  Just tell me where it goes if so.

**Comment by moroshko** [comment]
@arackaf Yeah, triggering the context menu confuses the Autosuggest. Clearly, looks like a bug. 

I don't think we have an issue for that. Do you mind to rename this issue to reflect the problem?

I'm not sure what is the best way to fix this yet, but will be happy to accept a PR.

By the way, I'm curious to know what's your use case for triggering the context menu for suggestion items?

**Comment by arackaf** [comment]
Gah - sorry, I missed this reply.

I don't remember why exactly I right-clicked my mouse when the menu was open - but that's how I noticed this.

I'll try to get you a PR, but terribly busy at the moment, sadly.

**Comment by moroshko** [comment]
Although it's a bug, it is very uncommon to right-click suggestions.
I'll close this issue for now.

**Comment by tmpg** [comment]
Is there any way to open this backup?

I am using this package for auto suggesting items in a search for the page to link to other parts of the site. Right-clicking to open in new tab would be a common action.

Let me know your thoughts.

Thanks.
