### ISSUE TITLE
Add aria-label or aria-labelledby

### ISSUE THREAD

**Issue by cristian-sima** [moroshko/react-autosuggest#198]
I have used this tool to test https://github.com/reactjs/react-a11y

It seems there is a problem:

![image](https://cloud.githubusercontent.com/assets/12199042/16774505/f2dbef2a-4864-11e6-95e5-cf00b1a11f92.png)

**Comment by moroshko** [comment]
Have you tried to add `aria-label` or `aria-labelledby` using `inputProps`?
Could you create a Codepen that demonstrates the issue? You can use [this one](http://codepen.io/moroshko/pen/LGNJMy) as a starting point.

**Comment by cristian-sima** [comment]
@moroshko Thanks I've done that. But I have a new one:

```
Autowhatever You have a click handler on a non-interactive element but no `tabIndex` DOM property. The element will not be navigable or interactive by keyboard users. http://www.w3.org/TR/wai-aria-practices/#focus_tabindex
```

And this one triggers when a hover any of the options.

It seems that each `li` should have a `tabIndex` set to `0`

**Comment by cristian-sima** [comment]
I will try to give it a shot now

**Comment by cristian-sima** [comment]
It seems that the problem is from `react-autowhatever`

**Comment by cristian-sima** [comment]
@moroshko Can you look at that. It seems there are no warnings now

**Comment by moroshko** [comment]
See [this](https://github.com/moroshko/react-autowhatever/pull/14#issuecomment-234182177)
