### ISSUE TITLE
Is focusFirstSuggestion working

### ISSUE THREAD

**Issue by avjpl** [moroshko/react-autosuggest#199]
By added focusFirstSuggestion: true break the selection. It only selects the first suggestion. Is there anything else apart from setting this to true that needs to be done?

This is the object I am paasing to autosuggest.

```javascript
   const autosuggestProps = {
      suggestions: [].concat(children || [], suggestions),
      getSuggestionValue: identity,
      shouldRenderSuggestions: () => true,
      renderSuggestion: this.renderSuggestion.bind(this),
      onSuggestionsUpdateRequested: this.onSuggestionsUpdateRequested,
      onSuggestionSelected: this.onSuggestionSelected,
      focusFirstSuggestion: true,
      theme: this.props.theme,
      inputProps: {
        onChange: this.onChange,
        onBlur: this.onBlur,
        onKeyPress: this.onKeyPress,
        value: displayInput,
        placeholder: this.props.placeholder,
      }
    };

   <Autosuggest {...autosuggestProps}/>
```

**Comment by moroshko** [comment]
@avjpl I'm not sure I understand the issue you are experiencing. 

[Here](http://codepen.io/moroshko/pen/AXxrEE) is a Codepen that demonstrates `focusFirstSuggestion={true}`. 

Could you please elaborate a bit more, and update the Codepen accordingly to demonstrate the problem?

**Comment by avjpl** [comment]
I apologise for not being clear, but I wasn't sure why the behaviour I was seeing was happening.

After seeing your Codepen, thank for that, I went back to my codebase and narrowed down what was causing the problem.

It was caused by this being set on the suggestions prop.

```javascript
[].concat(false || [], suggestions)
```

But I don't understand why.

[Here](http://codepen.io/avjpl/pen/VjyQkY) is a Codepen example.

**Comment by moroshko** [comment]
Thanks @avjpl, now I see that Up/Down doesn't work properly.

@rickhanlonii Could you have a look?

**Comment by rickhanlonii** [comment]
@moroshko @avjpl I'll take a look

**Comment by moroshko** [comment]
@rickhanlonii Any luck?

**Comment by rickhanlonii** [comment]
@moroshko not yet, last week was pretty busy. I'll take a look this week.

**Comment by fixpunkt** [comment]
I've just been hitting this problem, too.

If you take a look at `react-autosuggest/src/Autosuggest.js`:

    componentWillReceiveProps(nextProps) {
      if (nextProps.suggestions !== this.props.suggestions) {
        const {
          suggestions, inputProps, shouldRenderSuggestions,
          isCollapsed, revealSuggestions, lastAction
        } = nextProps;
        const { value } = inputProps;

        if (suggestions.length > 0 && shouldRenderSuggestions(value)) {
          this.maybeFocusFirstSuggestion();

          if (isCollapsed && lastAction !== 'click' && lastAction !== 'enter') {
            revealSuggestions();
          }
        }
      }
    }

This code is doing an identity comparison on the list of suggestions. So if you compute the `suggestions` prop dynamically in the parent component's `render()` method, this code path will run on every render and always set the focus to the first element, even if the list of suggestions has not actually changed.

This code should probably do a deep array comparison instead.

**Comment by fixpunkt** [comment]
On second thought, a deep comparison is probably wrong. What the code should actually do is if either nothing is selected or whatever is selected is no longer in the list of suggestions, and only in this case select the first element.

That's still in O(n) though, so it's not really faster than doing a deep array comparison.

**Comment by moroshko** [comment]
Probably makes sense to shallowly compare `suggestions` in `componentWillReceiveProps` instead of `===`. I'll fix this.

**Comment by moroshko** [comment]
This is fixed in [5.0.1](https://github.com/moroshko/react-autosuggest/releases/tag/v5.0.1) now.

**Comment by fixpunkt** [comment]
Can confirm, 5.0.1 fixes the issue for me. Thank you for fixing this so quickly!

**Comment by rickhanlonii** [comment]
Great diagnosis @fixpunkt!
