### ISSUE TITLE
onBlur event on the input

### ISSUE THREAD

**Issue by diridam** [moroshko/react-autosuggest#20]
Hello, 
Is there any way to trigger onBlur on the input box ?

i've tried this:
1) in the render function
```jsx
       const inputAttr = {
            id: 'someID',
            name: 'someName',
            placeholder: 'somePlaceholder',
            onBlur: this.blurCallback
        };
```

in component:
```jsx
   blurCallback: function(evt){
     console.log('something', e);
   },
```

the method called "blurCallback" is not triggered when i'm defocusing the input box.
Anyone can give me some hints on this issue ? am i missing something ? or this isn't implemented in moroshko's component?

thanks

**Comment by moroshko** [comment]
@diridam At the moment (v1.12.1), `<Autosuggest />` sets its own `onBlur` callback on the input. This is why your `onBlur` callback is ignored. In the next version, which will hopefully be out in the next couple of days, there will be a way to do what you want. Can you share what are you trying to achieve with `onBlur`?

**Comment by diridam** [comment]
I want to validate the fields with another component. (add a class if i don't have info inside or remove it if i have). 
I've tried with the events you've forged inside but there are some cases when they're not triggering.

**Comment by moroshko** [comment]
@diridam Not sure I understand which events you are talking about and when they are not triggering. Could you elaborate please?

**Comment by diridam** [comment]
http://moroshko.github.io/react-autosuggest/

1) press "a" in the input, then select an option with the "up" "down" arrows -> last event is "Suggestion selected:"
2) press "a" in the input, then select an option with the mouse -> last event is "Input changed:"

I tried of using "input changed" to do my validations, but because 2) is not ending in "suggestion selected" it's a problem, because all the logics/state inits made at the "input changed" will be re-intiated after a suggestion is selected. (it's some sort of a loop if i can call it like that)

**Comment by moroshko** [comment]
@diridam What you observe is the expected behaviour according to [WAI-ARIA spec](http://www.w3.org/TR/wai-aria-practices/#autocomplete). Input's value should change when using <kbd>Up</kbd> and <kbd>Down</kbd> keys, but not when hovering with mouse.

You should be able to use `inputAttributes.onChange` if you want to validate on every letter.

But, if you want to validate only when input loses focus, you'll have to wait until `inputAttributes.onBlur` is implemented.

**Comment by diridam** [comment]
@moroshko, that's exactly what i want to do, validate when input looses focus 
:+1: 

looking forward

btw. thanks for the component  :)

**Comment by moroshko** [comment]
@diridam Would it be ok not to call `onBlur` (meaning not to validate) when user clicks on a suggestion? As you can see, the input keeps the focus after click.

**Comment by diridam** [comment]
@moroshko, i think it's perfect. UX wise, is ok to have a validation at maximum the latest action a user has on that particular web element.

**Comment by moroshko** [comment]
@diridam `inputAttributes.onBlur` added in v1.12.2. Enjoy!

**Comment by diridam** [comment]
:+1:

**Comment by karthikvvs** [comment]
I have noticed that if I set the value of the autosuggest component (its in state) in onSuggestionSelected function to the value selected, its state is modified after the OnBlur function is called on the component. This is causing issues for my case as I want to pass the value selected to the backend when onBlur event is called on the input. Is this the intended behavior? If so, please let me know how can get the suggested value when onBlur event is called.

**Comment by moroshko** [comment]
@karthikvvs Could you please create a Codepen that demonstrates the issue?

**Comment by jehrlich** [comment]
I have a class which builds an autosuggest based on a set of initial suggestions passed as a prop. A parent component has 3 of these, and keeps state of 3 values. The initial suggestions for each of the 3 children is filtered from a parent library based on values for the other two children, so that changing one value should update the initial suggestions for the other 2 autosuggest components. Ideally this updating would only be done when focus moves to a new child.

**Comment by jackcarlisle** [comment]
@moroshko I'm having issues with the onBlur callback. I want to set the state of the component when the search bar is blurred but it doesn't seem to be triggering. 

Here are my input props: 
```js
const inputProps = {
      placeholder: placeholder,
      value,
      onChange: this.onChange,
      className: 'searchBox',
      type: 'search',
      onFocus: this.onFocus,
      onBlur: this.handleOnBlur
    };
```

And here is my handleOnBlur function:
```js
handleOnBlur (e) {
    this.setState({
      searchInFocus: false,
      placeholder: 'test'
    });
  }
```

Am I implementing it in the wrong way?

**Comment by moroshko** [comment]
@jackcarlisle [Here](http://codepen.io/moroshko/pen/OXwgqg?editors=0010) is a Codepen that demonstrates setting the state from the `onBlur` handler. 

Could you create a similar Codepen that demonstrates the issue you have?

**Comment by MasriNaser** [comment]
hallo, 
click on the suggestions by onClick dose not work, someone can help me?
thx
