### ISSUE TITLE
How to disable autofill suggestion value on input when navigate with Up/Down keys?

### ISSUE THREAD

**Issue by hieuhlc** [moroshko/react-autosuggest#200]
Just like facebook mention, I want to disable feature that autofill my input value with suggestion value when I navigate with Up/Down arrow key on suggestion list. How can I do it?

**Comment by moroshko** [comment]
This project follows the [accessibility standards](https://www.w3.org/TR/wai-aria-practices/#autocomplete) which suggest that:
> When a choice is highlighted using the arrow keys, the highlighted choice is displayed in the textbox.

If your requirements are different, you can always close the repo the update to the desired behaviour, or look for another project that allows you to do what you want. Sorry.

**Comment by Olliebaba** [comment]
I do not recommend this as a general rule but I needed to do such a thing for a form which was using `redux-form`

In case anyone needs to do this, I was able to prevent this by setting `getSuggestionValue={() => false}` and using `onSuggestionSelected` to handle the logic of applying the selected value instead.
