### ISSUE TITLE
Is there a proper way for setting value programmatically?

### ISSUE THREAD

**Issue by milushov** [moroshko/react-autosuggest#201]
Just a question :)

I want to use this component for search box, and new search update the browser history via `history.pushState()`. How can I set previous value for the component programmatically when user press the back button?

**Comment by moroshko** [comment]
Autosuggest is a controlled component whose value is set by providing `inputProps.value`. All you have to do is to make sure that `inputProps.value` is set to the previous value (you should know what it is) when the Back button is pressed. Does this answer your question?

**Comment by milushov** [comment]
ok, yep
