### ISSUE TITLE
Select option upon entering the exact value

### ISSUE THREAD

**Issue by snakeyak** [moroshko/react-autosuggest#203]
When the user enters a value that is **exactly** the same as one of the suggestions, it is expected that they don't have to click the suggestion to select the correct option.

Is there any way to achieve this with react-autosuggest? I've received several pieces of feedback on an app where I use the component that said this confused them

Thanks

**Comment by moroshko** [comment]
> Is there any way to achieve this with react-autosuggest?

What exactly are you trying to achieve?

**Comment by snakeyak** [comment]
Ok, say I have 3 options in the autosuggest - "apple", "banana", "orange"

When I type "banana" in the field and then "click away" (without clicking on the suggestion), I'd like to have "banana" selected, i.e. fire the same event as if I clicked the suggestion, since I typed the whole thing and there's no need for the suggestion anymore.

Hope I'm making more sense now?

Thanks

**Comment by moroshko** [comment]
You can provide `inputProps.onBlur` and check there if `inputProps.value` is equal to one of the `suggestions`. It's up to you to implement this logic. I don't believe it should be part of this library.
