### ISSUE TITLE
Is it any possibility to catch press enter event, when user focused on input

### ISSUE THREAD

**Issue by ilyabasiuk** [moroshko/react-autosuggest#205]
Hi. 

I have next case:
I provided to user possibilite to filter items by property values, and use autosuggest component to help user with entering filter value. 
And it works fine, if user select value from atosuggest dropdown list. 
But in the same time I want to give possibility to user just enter string and confirm his choice by pressing enter button.

Thanks

**Comment by ilyabasiuk** [comment]
I have adopted one of your samples 
http://codepen.io/ilyabasiuk/pen/zBWVwO

Only function onUserQueryChanged  was added (and some comments).

**Comment by moroshko** [comment]
To catch Enter you could wrap Autosuggest in a `<form>` and attach `onSubmit` to it. You could also try to provide `inputProps.onKeyPress` to Autosuggest.
Sounds like you found your way through, so closing for now.
