### ISSUE TITLE
how capture enter key

### ISSUE THREAD

**Issue by craigcosmo** [moroshko/react-autosuggest#208]
How would you capture enter key event?

The reasons and methods are not showing that I'm pressing enter while cursor focuses in text box.

forexample: type something, then press enter. I want detect that enter

**Comment by moroshko** [comment]
@craigcosmo [You could add `inputProps.onKeyDown`](http://codepen.io/moroshko/pen/mEjgyR?editors=0010)

**Comment by craigcosmo** [comment]
is it possible to get input value in `onKeyDown` ?

**Comment by craigcosmo** [comment]
ah nevermind, it's in the state. 👍

**Comment by jedrichards** [comment]
It works, but I'd like to be able to distinguish between an enter pressed to select a suggestion, vs enter being pressed when no suggestion is suggested. The callback in the codepen fires for both those scenarios ... any ideas?

**Comment by ematipico** [comment]
There's now way at the moment, as far as I understood

**Comment by moroshko** [comment]
@jedrichards [`onSuggestionSelected`](https://github.com/moroshko/react-autosuggest#onsuggestionselected-optional) exposes a `method` that is equals to `'enter'` when user selects a suggestion using Enter.
Is this enough to address your use case?

**Comment by ematipico** [comment]
@moroshko is there a way to distinguish the enter clicked while selecting a suggestion from the one clicked on the input box?

**Comment by moroshko** [comment]
@ematipico Could you describe your use case and what are you trying to accomplish?

**Comment by ematipico** [comment]
I'd like to fire an action (potentially a submit) when I click enter inside the input. I looked at previous issues and there was a suggestion of using a `form` and a `onSubmit` callback, which I tried. Although the callback gets fired  when I choose the suggestions via enter button and when I hit the enter button inside the input. The say happens if I try the `onKeyPressed` solution, I didn't find a way to distinguish the enter on the input and the enter when suggestion is selected.

**Comment by jacobweber** [comment]
Just ran into the same issue. I solved it using the method suggested in the last comment to #399.

**Comment by ematipico** [comment]
Nice workaround. Thanks! Although,  It would be nice to have a first class API

**Comment by ziedHamdi** [comment]
I have the same issue: the autosuggest is a search field where I the typed item can exist some 100 times (which I don't want to display in the list) or can even not exist. 

Pressing Enter when an element is selected means the user found what he was searching, I'm interested in the case where the user didn't select anything so the enter button will take him to a search result paginated page (as in google chrome). Additionally, there will be an add item button in that page

If I want to know if an item was selected, I have to hold a history in my state, which I don't really like...

**Comment by ziedHamdi** [comment]
> @ematipico Could you describe your use case and what are you trying to accomplish?

In my case, I described it just above
