### ISSUE TITLE
show suggestion on demand

### ISSUE THREAD

**Issue by craigcosmo** [moroshko/react-autosuggest#209]
Is there way to show suggestion on demand? For example, do something like calling showSuggestion() the suggestion will show up.

**Comment by moroshko** [comment]
Could you describe the user journey a bit more? Why would you want to programatically to reveal the  suggestions?

**Comment by craigcosmo** [comment]
what I want to do is rather weird case. First, you type 'hello world', there will be suggestions, so it's normal usage as expected. But If user presses enter after typing 'hello world'. I want to load a new set of suggestions from somewhere else (this suggestion is totally different from the one showed when typing)

What I could do already is, loading a new set of suggestion after user press enter (as set.state.suggestion = {new sug ob})

What I could not do programmatically is showing the new suggestions

I'm over coming this by doing this hack. When user press `enter`I `blur()` the input text, make it loses focus. After the new set of suggestion has been loaded into the state and into the DOM. I `focus()` the input text. This will make the suggestion show up.

**Comment by moroshko** [comment]
Sounds like this is a very weird use case. I don't think it should be part of this library. Sorry.
