### ISSUE TITLE
Support for contenteditable rather than just <input>

### ISSUE THREAD

**Issue by sahilamoli** [moroshko/react-autosuggest#210]
Feature request:

The ability to use contenteditable instead of just <input> would allow this component to be used for features such as @mentioning and other rich text auto-suggestions (in cases where we want rich text to be rendered in place of where the user was typing -- such as a link or image). Any plans on adding this support?

**Comment by moroshko** [comment]
Sorry, no plans for now.

**Comment by wilg** [comment]
Is there a way to use `renderInputComponent` to accomplish this?
