### ISSUE TITLE
Letters get erased when typing in IE 

### ISSUE THREAD

**Issue by nacho2487** [moroshko/react-autosuggest#211]
Hi,

To reproduce the issue go to this example http://codepen.io/moroshko/pen/ZQLyNK  on **IE**
Start typing "Clojure" and you can see that letters get erased. 

It can be seen on this gif when the "e"is erased at the end but it can happen at any letter as you type.
![react-redux-autosuggest](https://cloud.githubusercontent.com/assets/1712058/17380805/4a34e1e6-599f-11e6-926c-45a0f074f730.gif)

**Comment by LuckUY** [comment]
I have the same issue.  :(

**Comment by moroshko** [comment]
This is not an issue with `react-autosuggest` itself, but rather a react issue: https://github.com/facebook/react/issues/7027

**Comment by bbarnell** [comment]
It's fixed in React version 15.6.1
