### ISSUE TITLE
[Question] Autofocus prop?

### ISSUE THREAD

**Issue by sashashakun** [moroshko/react-autosuggest#214]
Hello.

First of all thanks for your work. I have a little question. What do you think about adding optional "autofocus" prop to input field? Something like
```
const inputProps = {
      placeholder: 'my placeholder',
      value,
      onChange: this.onChange,
      id: 'my-id',
      className: 'base-input',
      autofocus: 'true'
    };
```
I can make a PR also:)

Thanks.

**Comment by ThibWeb** [comment]
There's already an [autofocus attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autofocus) in HTML, named `autoFocus` when used as a React prop. In what way is your proposed attribute different?

**Comment by sashashakun** [comment]
@ThibWeb you are right, this is what i need, i missed this somehow, thanks!
