### ISSUE TITLE
Show all suggestions on focus?

### ISSUE THREAD

**Issue by ladz** [moroshko/react-autosuggest#217]
I'd like to mimic a <select/> with the the autosuggest component. The only thing that's missing is a possibility to show all suggestions when the input is focused, without further input by the user. Is there already a way to accomplish that?

**Comment by moroshko** [comment]
Check out the first example [here](http://codepen.io/collection/DkkYaQ/).

**Comment by lsenta** [comment]
Not the first example anymore: https://codepen.io/moroshko/pen/kXpapq

For those getting lost around here: use `shouldRenderSuggestions` and return always `true`
https://github.com/moroshko/react-autosuggest#should-render-suggestions-prop

**Comment by gabbloquet** [comment]
For people who search:
Add it on <AutoSuggest /> tag : shouldRenderSuggestions={() => true}

**Comment by doubledherin** [comment]
Another gotcha here might be if you forget to remove this piece of code, which is in the Readme example:

```
    if (escapedValue === '') {
      return []
    }
```
