### ISSUE TITLE
getSectionSuggestions passed undefined section param

### ISSUE THREAD

**Issue by ZebraFlesh** [moroshko/react-autosuggest#218]
It seems that in some asynchronous scenarios, the `getSectionSuggestions` function gets passed a section parameter that is undefined.  The issue seems to only present itself when you asynchronously update the suggestions from the `onChange` handler. One work around appears to be asynchronously updating the suggestions from the `onSuggestionsUpdateRequested` function.

CodePen showing onChange failure: http://codepen.io/anon/pen/VjgXQA?editors=0010#0
* using the DownArrow key to loop through the list, it typically fails when the focus cycles back around to the front of the list

CodePen showing work around via onSuggestionsUpdateRequested: http://codepen.io/anon/pen/PzVRZy?editors=0010#0
* you can hold down the DownArrow key all day without issue

I have absolutely no idea why this work around works, but I haven't dug into the AutoWhatever code. I should also say that in my own application, the failure scenario is slightly different: I get a null section right away when using the DownArrow key -- I don't need to loop through the list. Possibly it's because I'm doing additional things that change the behavior, but I figured I would mention it.

I'm seeing this behavior in react-autosuggest 3.9.0 as well as using the CodePen samples (which I assume using the latest release); both scenarios use React 15. I'm using Chrome 52 on both Mac and Windows; same results.

**Comment by moroshko** [comment]
@ZebraFlesh Could you please check if the issue still exists in v6.0.3, and if yes, update the issue (and the Codepen) accordingly? (`onSuggestionsUpdateRequested` was replaced with `onSuggestionsFetchRequested`)

**Comment by moroshko** [comment]
Closing for now, but happy to revisit in the future if the issue still exists.

**Comment by ZebraFlesh** [comment]
Confirmed, resolved under 6.0.4 using onSuggestionsFetchRequested semantics.

**Comment by moroshko** [comment]
Thanks for reporting back!
