### ISSUE TITLE
React to enter press when nothing is selected

### ISSUE THREAD

**Issue by samuliheljo** [moroshko/react-autosuggest#22]
I have following values available for autosuggest:
- value 1
- value 2
- value 3

Now, without doing any selection with arrows or mouse, I want to type "value 1" and hit enter. Currently, I can't seem to get any callback on this. Am I missing something?

**Comment by moroshko** [comment]
@samuliheljo Could you please describe what are you trying to achieve? What's your use case? What do you expect to happen when you press Enter?

**Comment by samuliheljo** [comment]
Sure.

Firstly, thanks for great component. For the most part it has worked perfectly for us.

So the case is that we are using autosuggest to find addresses that are stored on a server. It seems that some users just type their needed address to input field (e.g. "Mainroad 1") and press enter without actually selecting that specific value from autocomplete dropdown even when it is visible in dropdown. Now, what happens is that user types "Mainroad 1", hits enter, and nothing happens. 

What should happen when enter is pressed? It depends on the situation, but preferably "something". That "something" is what I want to implement. 

We have a working version where we use React ref callback function to catch autosuggest mount to dom something like this:
```
<Autosuggest 
      ref={this.handleAutoSuggestMount}
```
Then we find autosuggest input field through it's ref and attach keyup event listener to input like so:
```
handleAutoSuggestMount(autoSuggestComponent) {
  input = autoSuggestComponent.refs.input.getDOMNode()
  input.addEventListener('keyup', () => {...})
  ...
}
```
This way we can do some "extra stuff" when we notice the given situation occurs. This, however, feels quite dirty.

So:
1) Am I thinking this somehow backwards, is there easier way to react to enter press when nothing is selected, but still visible in dropdown?
2) If not, any plans on adding support for it?

**Comment by samuliheljo** [comment]
To give an extra example for "something"
1) User types "Mainroad" and hits enter
2) We want to search for "the first address that exist on Mainroad", and select coordinates for it

This way user can find at least some location on Mainroad easily

**Comment by moroshko** [comment]
@samuliheljo Thanks for the explanation!

Will this work?

    onFormSubmit() {
      // do your stuff
    }

    <form onSubmit={onFormSubmit}>
      <Autosuggest ... />
    </form>

**Comment by samuliheljo** [comment]
Yes, it does. Cheers! Closing this issue.

**Comment by jwilkinson** [comment]
What about if you want the first suggestion to be selected on enter? How do you get the data from the provided suggestions to pass to react-router?

**Comment by moroshko** [comment]
@JamieDixon Could you elaborate?

**Comment by jwilkinson** [comment]
Type Pinapple into the field.
Your Auto Suggest information only returns Apples.
User is looking for pineapples, so presses enter or hits a search button.
User should be taken to a search page with query pineapple.

The other use case is I want hitting enter to take the first suggestion and navigate to that. form onSubmit can handle the first case but not the second because I can't communicate back up to see what the first suggestion was to grab it's url to submit.

**Comment by moroshko** [comment]
@JamieDixon You supply suggestions to Autosuggest, so why can't you know the first suggestion? Another way to hook up to Enter is to add `inputProps.onKeyDown`, and check for `event.key === 'Enter'`, if that helps.

**Comment by JamieDixon** [comment]
I think you're referencing me @jamiedixon but meaning to refer to @jwilkinson :)
