### ISSUE TITLE
adding glyphicons on input field

### ISSUE THREAD

**Issue by ranleung** [moroshko/react-autosuggest#222]
Hello, great library!

I have been searching and unable to find a place to input glyphicons to either the beginning of the input of at the end of the input.

Here is how it would be done in bootstrap on the input field.

```
<div className="input-group">
  <input type="text" className="form-control" placeholder="Enter an address" autoFocus />
  <span className="input-group-btn">
    <button className="btn btn-secondary" type="button"><i className="fa fa-search"></i></button>
  </span>
</div>
```

thanks!

**Comment by moroshko** [comment]
Autosuggest just wraps the `<input>` element. Everything else you do outside of the `<input>` has nothing to do with Autosuggest - it's your app.
