### ISSUE TITLE
Suggestions behaviour breaks on right click

### ISSUE THREAD

**Issue by nvreez** [moroshko/react-autosuggest#224]
I just found a bug where if I right click on the opened suggestions on any of my browsers on Mac (using 10.11.6) it stops the onBlur behaviour and the suggestions stay open regardless where your focus is. Clearing the input does hide the suggestions, and it still updates the suggestions with what you type. 

I saw this behaviour both in my own product as well as on http://react-autosuggest.js.org/ 

Tested Mac browsers:
- Chrome - Version 53.0.2785.70 beta (64-bit)
- Safari - Version 9.1.2 (11601.7.7)
- Firefox - Version 47.0.1
- Opera - Version 39.0.2256.48

On Mac 10.11.6 (15G31)

I also saw it in my VM with Windows 8.1 using Chrome but a friend didn't see it on his Windows machine with Chrome, so I'm not sure if it's a Mac issue.

**Comment by moroshko** [comment]
Same as #197

**Comment by garimahans15** [comment]
Hi Team, I am still able to replicate a similar issue, if using the mouse middle button click and open the link to a new tab. Then clicking outside the suggestion is not closing the suggestion box. Suggestions remain open.
