### ISSUE TITLE
focusFirstSuggestion only focuses the first suggestion if the suggestions list changes

### ISSUE THREAD

**Issue by r-f-j-thomas** [moroshko/react-autosuggest#225]
When focusFirstSuggestion is set, it appears that the first suggestion is only focused when the suggestion list changes. If additional typing does not refine the suggestions list (most commonly when there is only one suggestion left), then the focus is removed.

For example on [this Codepen](http://codepen.io/anon/pen/WxqxJX), if you type 'j' then 'Java' is focused. If you type 'ja' then both 'Java' and 'Javascript' are displayed, but neither are focused.

**Comment by moroshko** [comment]
Thanks for reporting, this is clearly a bug. I'll have a look.

**Comment by moroshko** [comment]
This is fixed in [v5.1.2](https://github.com/moroshko/react-autosuggest/releases/tag/v5.1.2) now

**Comment by r-f-j-thomas** [comment]
Thank you for looking at this so quickly!

I believe it may have had an unintended side effect though. Now when focusFirstSuggestion is enabled, mouse hover does not change the highlighted item. The focus on the first suggestion seems to be overriding the mouse hover.

When there is a scrollbar, the mouse hover is also jumping the scroll point back to the top of the list.

**Comment by moroshko** [comment]
You're right, let me check.

**Comment by moroshko** [comment]
This is fixed in [v6.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.0) now.
