### ISSUE TITLE
autoscroll up?

### ISSUE THREAD

**Issue by snakeyak** [moroshko/react-autosuggest#226]
I've recently updated from 3.9.0 to 5.1.2. All works, apart from this strange self auto-scroll to the top of the suggestions list:

![auto-scroll](https://cloud.githubusercontent.com/assets/12460995/17969939/4903bf20-6acc-11e6-8692-ae4f083b5f9a.gif)

Is there something newly introduced that would be causing this? I can't figure out why this is happening

Thanks

**Comment by esseb** [comment]
Related to the last issue mentioned in https://github.com/moroshko/react-autosuggest/issues/225#issuecomment-242367755 perhaps?

**Comment by moroshko** [comment]
This is fixed in [v6.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.0) now.
