### ISSUE TITLE
Dropdown opens again after selecting suggestion when getting suggestions asynchronously

### ISSUE THREAD

**Issue by esseb** [moroshko/react-autosuggest#228]
Testcase:
http://codepen.io/Esseb/pen/YWomvQ

Expected result:
The input field should be focused and the dropdown should no longer be visible

Actual result:>
The dropdown closes but opens again immediately (I assume after the async result updates `this.state.suggestions` again)

Further information:
Regression between v5.1.0 and v5.1.1.

**Comment by moroshko** [comment]
Thanks, I'm aware of this unfortunate regression, and working on a fix.

**Comment by moroshko** [comment]
This is fixed in [v6.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.0) now.
