### ISSUE TITLE
Uncaught TypeError in onDocumentMouseDown

### ISSUE THREAD

**Issue by elmeister** [moroshko/react-autosuggest#230]
First of all - thanks for the great module!

There is a bit annoying error displayed in `onDocumentMousedown`, when [node is null](https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L128).
[Here is the fiddle] (https://jsfiddle.net/12a1gtma/), to reproduce error in console - please select any of react-select options.
Right after any option is picked, dropdown is destroyed, so `while (node !== document)` obviously can't reach document in [the parent chain](https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L139).
Everything works great, just will greatly appreciate, if `null` check will be added for node to remove red lines in console.

And thanks again for clean code and such a cool autosuggest component!

**Comment by moroshko** [comment]
Thanks for your kind words. [Enjoy!](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.2)

**Comment by mbeauchamp7** [comment]
@moroshko Hi, I had the same issue and I'm glad you fixed it but I was wondering why is the plugging being registered on the DocumentMouseDown event instead of individually on each suggestions?

**Comment by moroshko** [comment]
@mbeauchamp7 [`onDocumentMouseDown` was introduced](https://github.com/moroshko/react-autosuggest/commit/6b391779d9d9ba322ce51d216e95ce550a528910) to address an [issue in IE11 when suggestions container has a scroll bar](https://github.com/moroshko/react-autosuggest/issues/190). Hope this helps.
