### ISSUE TITLE
report open/closed state in renderSuggestionsContainer

### ISSUE THREAD

**Issue by ZebraFlesh** [moroshko/react-autosuggest#231]
Now that the suggestionsContainer is displayed all the time and we have more control over it, it would be nice to know if its being rendered in an open or closed state (that is, if a list of suggestions is visible). I'd like to use this function to render a custom logo at the bottom of the container, but it only makes sense to display the logo when suggestions are visible.  Right now I'm forced to this via CSS. Ideally I'd like to do something like:

```js
renderSuggestionsContainer({ children, isOpen, ...props }) {
  const { renderBranding } = this.props;
  const branding = renderBranding && isOpen ? renderBranding() : null;

  return (
    <div {...props}>
      {children}
      {branding}
    </div>
  );
}
```

**Comment by moroshko** [comment]
`isOpen` in this context is equivalent to `children !== null`. Have a look at [this](http://codepen.io/moroshko/pen/RGPjNk) Codepen.

In your case, you could do:
```js
renderSuggestionsContainer({ children, ...props }) {
  const { renderBranding } = this.props;
  const branding = (renderBranding && children !== null) ? renderBranding() : null;

  return (
    <div {...props}>
      {children}
      {branding}
    </div>
  );
}
```

**Comment by ZebraFlesh** [comment]
Huh, I hadn't thought of that.  Thank you!
