### ISSUE TITLE
enter causes form to submit

### ISSUE THREAD

**Issue by ZebraFlesh** [moroshko/react-autosuggest#232]
When using react-autosuggest in a `<form>` and the user presses the enter key to select a suggestion, the form is submitted. This seems undesirable from a usability perspective (particularly if you're using more than one instance of react-autosuggest on the same form).  (Supporting implicit submit -- form submittal via a button/input with `type="submit"` -- is important for accessibility reasons.) It seems like the enter key event should be contained to the react-autosuggest component and/or the event should be canceled. This would change would allow react-autosuggest to live nicely within a `<form>`.

Here's a codepen based on 6.0.2 that demonstrates the issue: http://codepen.io/anon/pen/XjAZxN?editors=0010

It's straight forward to solve this on the consuming application side:  add an `onSelect` callback that does the following:
```js
onSuggestionSelected(event, { suggestion }) {
  if (event && event.key === 'Enter') {
    const { getSuggestionValue, cInputText } = this.props;
     
    if (getSuggestionValue(suggestion) === this.state.value) {
      // If old and new values are the same, bail early and don't perform any
      // selection logic. This prevents double selections from the react-autosuggest
      // component when the user hits enter in the input field.
      return;
    }
     
    // If old and new values differ, proceed as normal -- except we might be
    // in a form, so prevent this enter keystroke from submitting the form.
    event.preventDefault();
  }

  // ... perform the rest of my selection logic
}
```

However, it seems like things would be better if every consuming application did not have to write this code.

**Comment by moroshko** [comment]
Is it basically comes down to calling `event.preventDefault()` from `onSuggestionSelected`?
```js
onSuggestionSelected = event => {
  event.preventDefault();
};
```
Is there any harm to always call `event.preventDefault()` from `onSuggestionSelected`?

**Comment by ZebraFlesh** [comment]
With the example shown, no, there would not be any harm. It would be inconvenient for consumers, but that's all.

In my more complex application, however, this does cause problems. So perhaps it's not actually a good idea. (Imagine synthesizing a "no match found" suggestion on the fly when the list of suggestions is empty. Combine that with `focusFirstSuggestion` and you need some selection logic to skip the synthetic element, but allow the key press event to go through. In a word: complicated.)

Closing this one.
