### ISSUE TITLE
Uncaught TypeError with async results and focusFirstSuggestion={true}

### ISSUE THREAD

**Issue by esseb** [moroshko/react-autosuggest#234]
**Testcase:**
http://codepen.io/Esseb/pen/GjRpqz

**Steps to reproduce:**
1. Open devtools console
2. Focus the input field and type <kbd>c</kbd>
3. Wait for suggestions to appear
4. Continue typing random letters and wait for the suggestions list to disappear
5. Press <kbd>Enter</kbd>

**Observed behaviour:**
`Uncaught TypeError: Cannot read property 'name' of undefined`

**Expected behaviour:**
Nothing should happen

**Comment by esseb** [comment]
Tested in Chrome Version 52.0.2743.116

**Comment by moroshko** [comment]
@esseb Thanks a lot for a perfectly submitted issue! This is fixed now in [v6.0.3](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.3).
