### ISSUE TITLE
Is it possible to have a dist folder for client side include?

### ISSUE THREAD

**Issue by max-favilli** [moroshko/react-autosuggest#236]
I saw #24 and #25 but seems /dist and /standalone are gone, I can't find them in the repo. The demo still refer to ../../dist/standalone/autosuggest.min.js but it doesn't seems to be there.

Is it possible to have them back?

**Comment by moroshko** [comment]
Although `dist` is ignored in the `master` branch, you should get it when you `npm install react-autosuggest`:

![](https://dl.dropboxusercontent.com/u/1893981/Screenshots/8pus.png)

**Comment by max-favilli** [comment]
@moroshko I was installing with bower. I installed it with npm and found it. But I still think it should be there in the master branch.
