### ISSUE TITLE
`Asynchronous` example is slightly wrong

### ISSUE THREAD

**Issue by liubko** [moroshko/react-autosuggest#238]
I think `asynchronous` example http://codepen.io/moroshko/pen/EPZpev is slightly confusing
```
  loadSuggestions(value) {
    this.setState({
      isLoading: true
    });
    
    setTimeout(() => {
      if (value === this.state.value) {
        this.setState({
          isLoading: false,
          suggestions: getMatchingLanguages(value)
        });
      } else {
        // Ignore suggestions if input value has changed
        this.setState({
          isLoading: false
          /*
             We don't need to do this. As our request with current search value might be still loading
          */
        });
      }
    }, randomDelay());
  }
```

current example, status updates too often:
![5](https://cloud.githubusercontent.com/assets/4257937/18242726/5e10117e-7360-11e6-95cb-d160da5f395f.gif)

if we remove `else` statement:
![2](https://cloud.githubusercontent.com/assets/4257937/18242725/5e0f3510-7360-11e6-91be-4ae11d190aa2.gif)

**Comment by moroshko** [comment]
What exactly do you find confusing?

[Here](http://codepen.io/moroshko/pen/dpPZdE) is a slightly modified version of this Codepen, which has a constant 2sec delay and does not have the `else` bit.

Without `else`, you can find yourself stuck in the `Loading...` state. For example:
1. Type `c`
2. Press <kbd>Backspace</kbd> before 2 seconds passes

**Comment by liubko** [comment]
ok, I see. What I suggested isn't a solution, but when request with **outdated query** get's resolved earlier than request with **latest query** it means that we are still **loading** necessary data.

**Comment by moroshko** [comment]
Could you please explain what do you mean by:
> it means that we are still **loading** necessary data

using the following diagram?

```
   +------------------------- 1. user types 'p'
   |
   |       +----------------- 2. user types 'e'
   |       |
   |       |     +----------- 3. suggestions for 'p' arrive,
   |       |     |               but they are not relevant anymore
   |       |     |
   |       |     |        +-- 4. suggestions for 'pe' arrive
   |       |     |        |

-- A ----- B --- C ------ D --------------------------------> time

           +--------------+
           | 'pe' request |
   +-------+-----+--------+
   | 'p' request |
   +-------------+

   +----------------------+
   |      Loading...      |
   +----------------------+
```

**Comment by liubko** [comment]
so currently at step `3. suggestions for 'p' arrive, but they are not relevant anymore` , we will set `isLoading: false`, which I think is wrong because we are still waiting for `pe` suggestions, which will arrive only at step 4

**Comment by moroshko** [comment]
Yeah, I see, you are right.

Have a look at [this modified Codepen](http://codepen.io/moroshko/pen/EPZpev) where I'm cancelling the previous request, if it exists.

Does this look better?

**Comment by wootencl** [comment]
Not trying to reopen this issue but did have a question regarding this. Sorry if this is a little dense on my part but how would this work for an actual async call? In the example you're mocking one with setTimeout which provides you with the ability to clear it on input change. With an actual ajax request I may not have the luxury of utility to cancel the request before it resolves (as with clearTimeout). Do I need to wrap my request in a timeout for this purpose? Any help would be greatly appreciated. Here's a general idea of what I'm trying to do (excuse my es7):

```
loadSuggestions(value) {
    // Not really sure how I would be able to cancel
    // the below pending ajax request.
    // if (this.lastRequestId !== null) {
    //  clearTimeout(this.lastRequestId); 
    // }
    
    this.setState({
      isLoading: true
    });
    
    try {
      const languages = await languageService.query();
      this.setState({
        isLoading: false,
        suggestions: languages
      });
    } catch (err) {
      console.log(err);
    }
  }
```

Outside of that, thanks for the excellent module! 

/cc @moroshko

**Comment by lukechilds** [comment]
@wootencl I just encountered this and you can actually solve it really simply by just saving two references to the Promise for the request, one in your component and one locally. Then inside your `then` you just check if the local reference is the same as the reference on your component.

e.g:

```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      value: '',
      suggestions: [],
      isLoading: false
    };

    this.latestRequest = null;
  }

  loadSuggestions(value) {

    this.setState({
      isLoading: true
    });

    // Make request
    const thisRequest = this.latestRequest = fetch(`/api?suggest=${value}`)
      .then(res => res.json())
      .then(res => { 

        // If this is true there's a newer request happening, stop everything
        if(thisRequest !== this.latestRequest) {
          return;
        }

        // If this is executed then it's the latest request
        this.setState({
          suggestions: res.suggestions
          isLoading: false
        });
      })
  }

   ...
```
