### ISSUE TITLE
onSuggestionSelected when you press 'tab'

### ISSUE THREAD

**Issue by dmytro-lymarenko** [moroshko/react-autosuggest#240]
Testecase
http://codepen.io/anon/pen/JRoBaO

Make this steps:
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear
  3. Press <kbd>Down</kbd> to select first suggestion
  4. Press <kbd>Tab</kbd>

  **Observed behaviour:** onSuggestionSelected is not called

  **Expected behaviour:** onSuggestionSelected must be called

The same situation when you use focusFirstSuggestion=true:
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear
  3. Press <kbd>Tab</kbd>

  **Observed behaviour:** onSuggestionSelected is not called

  **Expected behaviour:** onSuggestionSelected must be called

In my application I need to save the suggestion instead of the value. So I need onSuggestionSelected to be called correctly.

Thanks.

**Comment by moroshko** [comment]
What if we have a highlighted suggestion, and user blurs the field by not pressing <kbd>Tab</kbd>, e.g. clicking on some other element on the page, or maybe pressing <kbd>Shift</kbd>+<kbd>Tab</kbd>? Would you expect `onSuggestionSelected` to be called then?

You can get the focused/highlighted suggestion [onBlur](https://github.com/moroshko/react-autosuggest#inputpropsonblur-optional).

Will that be enough to support your use case?

**Comment by dmytro-lymarenko** [comment]
@moroshko thanks. It is really what I need. Yes, It is enough to support my case.
