### ISSUE TITLE
Selected suggestion is always visible

### ISSUE THREAD

**Issue by dmytro-lymarenko** [moroshko/react-autosuggest#241]
Is it possible to forbid leaving the container? I mean selected suggestion must always be. And when you try to press **up** when the first suggestion is selected let the last suggestion become selected. And when the last one is selected and you press **down** the first one becomes selected.

But now when the first one is selected and you press **up** the selected suggestion disappears.

**Comment by moroshko** [comment]
What you describe is against the [WAI-ARIA guidelines](https://www.w3.org/TR/wai-aria-practices/#autocomplete):
> Note that the arrows will wrap through the text box when the top or bottom of the list is reached. For example, pressing the down arrow when the last choice is highlighted will move focus back to the text box, pressing down again will move focus to the first item in the list. Likewise, with focus in the text box and the list displayed, pressing up arrow will move focus to the last item in the list.

Closing as "won't do".
