### ISSUE TITLE
Object value suggestion

### ISSUE THREAD

**Issue by rmlevangelio** [moroshko/react-autosuggest#243]
Hi, 

for example I have this object:
```js
const people = [
   { 
      postcode: 10021,
      suburb: 'Sydney'
   } 
];
```

Is it possible that if I search for '10021' or 'Sydney', I will get the same result? 

Thanks,
Rem

**Comment by moroshko** [comment]
Autosuggest has no opinion on the matching logic. It's totally up to you to define it.

For example, check out how `getSuggestions` is implemented in [this Codepen](http://codepen.io/moroshko/pen/RGPQYK).
