### ISSUE TITLE
Suggestions not matching validation regex from react-tagsinput

### ISSUE THREAD

**Issue by mbeauchamp7** [moroshko/react-autosuggest#244]
Hi,

I came across a special bug when using autosuggest with tagsinput. I was rendering suggestions from my database and it turned out that my validation regex props for react-tagsinput wasn't good so when I was hitting enter to add the tags, it wasn't adding anything but when I was clicking the suggestion to add the tag I was getting this error.

"Autosuggest.js:486 Uncaught TypeError: (valueBeforeUpDown || value).trim is not a function"

valueBeforeUpDown being null and value being 0.

[Here](https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L425-L427)
```
var renderSuggestionData = {
        query: (valueBeforeUpDown || value).trim()
};
```

Maybe check if either value are strings before trimming?

```
var renderSuggestionData = {
        query: (typeof valueBeforeUpDown === "string" || typeof value === "string") ? (valueBeforeUpDown || value).trim() : ""
};
```

Haven't tested this and don't know if this would actually work but I thought it was worth mentioning!

**Comment by moroshko** [comment]
Looks like `inputProps.value` is the number `0` in your case. If you make sure that `inputProps.value` is always a `String`, this error should disappear.
