### ISSUE TITLE
Uncaught TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by bbenezech** [moroshko/react-autosuggest#246]
https://github.com/moroshko/react-autosuggest/blob/a759a2527ae55cf2a9bf60fea606045161af108c/src/Autosuggest.js#L126

`event.detail` can be `undefined` with weird custom events.

Happened with [Trix editor](https://trix-editor.org/) when undoing with <kbd>CTRL</kbd>+<kbd>Z</kbd> while an autosuggest is present elsewhere.

Yep. Edge case.

Proposed fixes:
- find a "a better way to emulate this" 😜
- be more defensive 💂 
- act like we don't care 🙉

**Comment by moroshko** [comment]
Thanks for raising the issue! 

I went with "be more defensive 💂" for now.

**Comment by moroshko** [comment]
This is fixed in [v6.0.4](https://github.com/moroshko/react-autosuggest/releases/tag/v6.0.4) now. 

Thanks again 👍
