### ISSUE TITLE
value distinct from label

### ISSUE THREAD

**Issue by StokeMasterJack** [moroshko/react-autosuggest#249]
It would be nice if the value was distinct from what was displayed in the dropdown list or in the visible input.

So if we were displaying a list of people like this:

[{id: 1, name: 'Joe'},{id: 2, name: 'Dave'}]

value: {id: 23, name: 'Joe'}
render suggestion: <span>{value.name}</span>
inputDisplayValue: {value.name}

Alternatively, the value could could be just the id.

Here are a few reasons for allowing access to the value (as distinct from the display text):

1. Other parts of the app are already written expecting an id.
2. Writing code to go from "John Brown" to 437 is a pain in the butt when you already know the id.
3. select/comboboxes/autosuggest widgets have worked this way since the beginning of time. react-select works this way. MS Access from the 90's works this way. The html select element in react works this way. From the React docs:

```
<select value="B">
    <option value="A">Apple</option>
    <option value="B">Banana</option>
    <option value="C">Cranberry</option>
</select>

<select multiple={true} value={'A'}>
```

Thanks.

**Comment by moroshko** [comment]
Autosuggest is fundamentally different from a select/dropdown. Autosuggest is based on an `<input>` element which has "free text" at its core. Select/dropdown doesn't have a concept of "free text". 

Instead of jumping to a solution, could you start by explaining what are you trying to achieve?

Could you create a Codepen that demonstrates your issue? You can start from the [Basic example](http://codepen.io/moroshko/pen/LGNJMy).

**Comment by StokeMasterJack** [comment]
Here is my use-case: I want the user to type in the first few chars of a
vendor name. There could be thousands of vendors. After typing one or two
chars, a list pops up allowing the user to select the vendor. I want the
user to see the vendor name. But I, programmatically, want access to the
entire vendor object (which I am already returning in my list of
suggestions). Or, at the very least, I would like the vendor id without the
need to run an extra query to go from name to id.

GWT's SuggestBox worked this way. Very similar to your except it gave
access to the entire suggestion object (getValue() and getText()):

http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/client/ui/SuggestBox.html

Thanks.

**Comment by palumale** [comment]
@StokeMasterJack i think you are looking for the [onSuggestionSelected](https://github.com/moroshko/react-autosuggest#onSuggestionSelectedProp) method.

fired on user selection, you ll have access to the suggestion and other usefull data.

**Comment by StokeMasterJack** [comment]
Thanks

**Comment by moroshko** [comment]
Closing for now

**Comment by axeff** [comment]
Thanks. Had the same thing...
