### ISSUE TITLE
Getting active suggestion

### ISSUE THREAD

**Issue by olzraiti** [moroshko/react-autosuggest#251]
There doesn't seem to be any way to get the active suggestion.

I need this because I'd like the tabulator key to select the active suggestion.

Another solution for my use case would be adding some way to tell react-autosuggest which keys should select a suggestion, but adding a way to get the active suggestion would be more general and probably cover more use cases, since the users could implement their own logic for selecting suggestions.

A simple solution would be exposing Autosuggest to AutosuggestContainer with a ref-property.

**Comment by moroshko** [comment]
You can provide [`inputProps.onBlur`](https://github.com/moroshko/react-autosuggest#inputpropsonblur-optional) and get the focused suggestion in the callback.

**Comment by olzraiti** [comment]
Good point, thanks!
