### ISSUE TITLE
Title as a prop without multi-section?

### ISSUE THREAD

**Issue by kevinSuttle** [moroshko/react-autosuggest#255]
Just a quick question: is it possible to provide a title as a prop without multiple sections?

**Comment by necronet** [comment]
Can you be more specific?

**Comment by kevinSuttle** [comment]
First off, thanks for this. Really great component. Well thought out. 

As to my question, I figured it out actually, but it wasn't what I had expected. 
Sorry, I should have been more thorough.

http://codepen.io/moroshko/pen/RGPjNk 

My use case was a single list of suggestions with one title. 

I ended up wrapping this component and passing source list (#254) and a `heading` prop into a similar implementation as you have in your codepen.

**Comment by moroshko** [comment]
Thanks @kevinSuttle!

Autosuggest is a low level [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) component. Wrapping it with an uncontrolled component like you did is the way to go.

I'm closing this issue and #254 for now, but feel free to reopen if you have more questions.
