### ISSUE TITLE
Not closing on click

### ISSUE THREAD

**Issue by Harrisonl** [moroshko/react-autosuggest#256]
Basically the title. When I select a suggestion with the mouse or touch on phone, the selections don't hide, I have to press enter in order to get them to hide.

Not exactly sure how to reproduce, but here is my component:

```js
              <Autosuggest
                suggestions={this.props.services.services}
                onSuggestionsFetchRequested={this.getServices}
                onSuggestionsClearRequested={this.clearServices}
                getSuggestionValue={getServiceValue}
                renderSuggestion={renderFoundServices}
                inputProps={inputProps}
                focusInputOnSuggestionClick={true}
                onSuggestionSelected={this.suggestionSelected}
              />
```

I have tried a few things, such as changing suggestions to a state object and having it clear on suggestionsSelected but that still doesn't seem to work.

**Comment by Harrisonl** [comment]
Figured it out.

If anyone else runs into the issue, in my case it was caused by the onSuggestionSelected method, making a call to the backend and not reseting props.services to an empty array. So when the props came through for the next thing, services still had all the same values and the state got all the services again. 

**However, it is odd that this only happened on click/touch and not on enter press. **

I'll leave it up to the maintainers as to whether or not to close this one.

**Comment by moroshko** [comment]
Closing for now, but happy to review again if a reproducible example is presented.
