### ISSUE TITLE
Question - how not to close suggestions after a suggestion is selected?

### ISSUE THREAD

**Issue by ramstet3** [moroshko/react-autosuggest#259]
Use case : I type a couple of letters, see 5 suggestions, and want to select all 5. When I click the first one, it selects it but closes the suggestions list, I have to re-type again in the input box. How do I prevent the suggestions list to collapse, so that I can just click all 5 in one go?

I tried to make shouldRenderSuggestions always return true, but it doesn't do the trick, even when there is still a value in the input box.

**Comment by moroshko** [comment]
Have you tried [`alwaysRenderSuggestions`](https://github.com/moroshko/react-autosuggest#alwaysRenderSuggestionsProp)?

**Comment by ramstet3** [comment]
Yes, but after more investigation I found out that the problem is not that the suggestions are collapsed, but that the suggestions (state.suggestions) were set to an empty array after clicking a value in the list.

The reason is that I use this to filter the suggestions:

    onSuggestionsUpdateRequested({ value }) {
        this.setState({
            suggestions: this.getSuggestions(value)
        });
    }

And this triggers with value = displayProperty when an item is clicked, setting suggestions to an empty array. I'll see if I can fix it.

**Comment by moroshko** [comment]
Could you create a Codepen that demonstrates the issue? 
You could start from this [Basic example](http://codepen.io/moroshko/pen/LGNJMy).

**Comment by ramstet3** [comment]
Sure (I just added alwaysRenderSuggestions) : http://codepen.io/anon/pen/PGQYLg

In fact it's not an issue, just a different use case. What I would like is that if I type "C", and then see "C#" and "C++", I could click C# and the suggestions would stay the same and I could then click C++ without having to search again (I would capture what the user selected myself, using onSuggestionSelected).

What happens is that when I click a suggestion, onSuggestionsFetchRequested gets triggered with value being the clicked suggestion, so it narrows down the suggestions to what you clicked. Is there a way to prevent onSuggestionsFetchRequested to trigger when clicking an option?

**Comment by moroshko** [comment]
You could just leave `onSuggestionsFetchRequested` to do nothing. [Is this what you are after?](http://codepen.io/moroshko/pen/XjkVJx?editors=0010)

**Comment by ramstet3** [comment]
Yes! Thanks a lot, that was what I needed.
