### ISSUE TITLE
[Comment] Reusability aka Redux Dependency

### ISSUE THREAD

**Issue by ohager** [moroshko/react-autosuggest#260]
This not a bug, nor a feature request...just a comment. Discussions are welcome.

I decided not to use this component due to fact, that it uses redux as dependency. 
Don't get me wrong, Redux/Flux is an adequate _architectural solution_ for managing **application state**.

IMHO a _reusable_ component should isolate its behavior and should be agnostic to any architecture pattern. Using Flux to manage a components state is not a good design decision, as it 
1. breaks component isolation (how to deal with several mounted components?! - reinvent instance handling!)
2. introduces boilerplate
3. exposes implementation details 

I cannot see any good reason why react-autosuggest uses redux. 

Coincidentally, I wrote a [post about it ](https://devbutze.com/p/306) some months ago, because I tried to apply Flux to a custom suggestion input.

**Comment by Codii** [comment]
I agree. Redux should not be coupled with this component. 
It seems useless the way it is done, not even composable/modulable with other stores. Plus the dependency problem. You should probably get rid of it.

**Comment by thebigredgeek** [comment]
Yeah, and it causes a bug... `redux.createStore is not a function` etc etc.  Not really sure why this design decision happened.  Thinking about starting a fork @Codii @ohager

**Comment by thebigredgeek** [comment]
https://github.com/moroshko/react-autosuggest/issues/296

**Comment by moroshko** [comment]
@ohager @Codii @thebigredgeek Thanks for your feedback!

`redux` and `react-redux` dependencies were removed in [v8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0).

**Comment by ohager** [comment]
You're welcome. Awesome Work.
