### ISSUE TITLE
Debouncing is broken in IE

### ISSUE THREAD

**Issue by jbandi** [moroshko/react-autosuggest#262]
The "debouncing scenario" (async lookup of suggestions) is broken in Internet Explorer.
When you quickly type a word, some letters get "swallowed".
ie. You type "computer" but the input finally only shows "coputr".

I could easily reproduce the bug with the "official" plunkr:
http://codepen.io/moroshko/pen/KVaGJE

To make the bug more obvious, set the debounce time to 100 ms on line 113.

In my tests, the bug only appears in IE. I could not reproduce it in Chrome or Firefox.
I tested in IE 11.
I detected the bug in react-autosuggest@3.5.1.
I updated to react-autosuggest@6.0.4 and can still reproduce the bug.

**Comment by moroshko** [comment]
This is probably the reason: https://github.com/facebook/react/issues/7027 - this should be fixed in React 16.

I don't think we can do much in this library, so closing for now with the hope that React 16 will be released soon.
