### ISSUE TITLE
Unable to use code sample in README.md

### ISSUE THREAD

**Issue by fajarmf** [moroshko/react-autosuggest#266]
I was following your example code on README.md. However when running babel with this presets: `presets: ['es2015', 'react']`, it gives me this error: 
```

> 43 | onChange = (event, { newValue }) => {
     |          ^
  44 |     this.setState({
  45 |       value: newValue
  46 |     });

```

What did I do wrong? I am new to react and eager to learn :)

**Comment by moroshko** [comment]
To use [class properties](https://babeljs.io/docs/plugins/transform-class-properties/), like I do in the README, you also need:
```js
{
  "plugins": ["transform-class-properties"]
}
```
Alternatively, you could use the [stage-0](https://babeljs.io/docs/plugins/preset-stage-0/) preset [(that's what I do)](https://github.com/moroshko/react-autosuggest/blob/1057d193fc6f77a910a907f486780413e6663948/.babelrc#L2).

**Comment by moroshko** [comment]
Closing for now.

**Comment by fajarmf** [comment]
thank you 👍
