### ISSUE TITLE
announce the number of suggestions as user type

### ISSUE THREAD

**Issue by ndao** [moroshko/react-autosuggest#273]
I have a requirement that says VoiceOver must announce the number of suggestions available as the user type. is that a current feature of autosuggest?

**Comment by moroshko** [comment]
I don't actually know, but you are welcome to try and report back ;)

Do you know what exactly (aria attributes, or something else) causes VoiceOver to pronounce the number of suggestions? Do you have any relevant pointers to accessibility guidelines?

**Comment by ndao** [comment]
@moroshko, i made it work with adding a aria-live element and changes the text as the result changes.

**Comment by moroshko** [comment]
Do you mind to paste the relevant code from your implementation here?

**Comment by ndao** [comment]
basically this, as content inside the aria-live element changes, VoiceOver will announce that content.
```js
class AutoCompleteField extends Component {

  render () {
    return (
      <div>
        <Autosuggest
          id={id}
          ...
        />
        <div id={atHintId} hidden aria-hidden="false" aria-live="polite" role="status">
          {
            suggestions && suggestions.length > 0
              ? `${suggestions.length} suggestion${suggestions.length > 1 ? 's are' : ' is'} available, keyboard user use arrows to select.`
              : ''
          }
        </div>
      </div>
    )
  }

}
```

**Comment by moroshko** [comment]
Nice that you found a way to achieve this outside of Autosuggest.

I still think it would be nice to have this functionality built in, but struggle to find clear accessibility guidelines on this topic. I'll close this issue until someone can provide authoritative links.

P.S. If we decide to include this functionality in Autosuggest, the message will probably have to be configurable.
