### ISSUE TITLE
Use TextField from material-ui

### ISSUE THREAD

**Issue by artsx** [moroshko/react-autosuggest#274]
Hello,

It's possible to use TextField from material-ui like design for your input ?
http://www.material-ui.com/#/components/text-field

Best regards,

**Comment by moroshko** [comment]
I haven't tried to integrate material-ui's input, but you are welcome to try and report back. You'll probably need to use [`renderInputComponent`](https://github.com/moroshko/react-autosuggest#renderInputComponentProp).

**Comment by artsx** [comment]
Thx @moroshko it works perfectly : 
const renderInputComponent = inputProps => (
  ```
<TextField
    hintText="myHintText"
    floatingLabelText="my floating label"
    style={{
      width:'100%',
      fontSize:'16px'
    }}
    {...inputProps} />
);

```
