### ISSUE TITLE
Feature request: onSuggestionFocused callback

### ISSUE THREAD

**Issue by nhducit** [moroshko/react-autosuggest#276]
## Are you making a feature request?
- Please describe your use case from user journey point of view, e.g.:
  
  > In my application, when user highlights suggestions (using the mouse or keyboard), I'd like to display additional information about the highlighted suggestion in google map component.
- Provide the steps to reproduce the issue, e.g.:
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear
  3. Press <kbd>Down</kbd>
  
  **Observed behaviour:** 
  
  **Expected behaviour:** Support onSuggestionFocused

**Comment by moroshko** [comment]
Closing as #168 duplicate.
