### ISSUE TITLE
State handling

### ISSUE THREAD

**Issue by Halama** [moroshko/react-autosuggest#28]
Hi,
we have encountered issue with component state. The component hold current value of input in it's internal state, so when the property `inputAttributes.value` is changed the change is ignored by Autosuggest component.

Here is the demo https://jsfiddle.net/1y4v9pw6/3/ 

The fix is remove state from component https://github.com/keboola/react-autosuggest/commit/d13008c27e2148205855b0a2fea70dfdc03eaeef and let it behave as controlled component https://facebook.github.io/react/docs/forms.html#controlled-components

Here is the demo same demo but with patched Autosuggest https://jsfiddle.net/2cuf1mzu/1/

This fix BC break, maybe also component which only holds the state could be provided for BC compatiblity.

Our use case where we discovered this issue is form where the initial value of Autosuggest component is dependent on some select value which is used before autosuggest.

Also passing a value instead of event to handler `inputAttributes.onChange` is bit strange.
thanks.

**Comment by moroshko** [comment]
@Halama Thanks for the issue and the examples to illustrate it.

I guess you meant "...let it behave as **un**controlled component", right?
According to [React docs](https://facebook.github.io/react/docs/forms.html#controlled-components):

> An `<input>` that does not supply a value (or sets it to null) is an uncontrolled component. 

Just removing `value={this.state.value}` like [you suggested](https://github.com/keboola/react-autosuggest/commit/d13008c27e2148205855b0a2fea70dfdc03eaeef), will fail many tests, especially around keyboard interactions. For example, when the Down key is pressed, the value of the input should change to the next suggestion. This is according to [WAI-ARIA standards](http://www.w3.org/TR/wai-aria-practices/#autocomplete). Interestingly, it works in [your example](https://jsfiddle.net/2cuf1mzu/1/), but I think it is only because you specified `inputAttributes.value`. Try to clone the repo, delete `value={this.state.value}`, and run the examples (`npm start`). You'll see that things are broken.

Thanks for your comment about `inputAttributes.onChange`. I agree that it's a bit unexpected. It is only because I wanted to provide a more convenient way to work with it (`newValue` vs `event.target.value`). If it limits you doing certain things, let me know.

I'd be interested to know a bit more about your use case with the select that controls the initial value of the autosuggest. What type of data you deal with? If user interacts with select **after** they interacted with the autosuggest, would you be happy to reset autosuggest's value?

**Comment by leishman** [comment]
@moroshko 

How can i manually update the value attribute of the input field? I'm having a hard time resetting this input after submission. The value seems to be maintained in the state and I cannot figure out how to properly reset it.

**Comment by dnusca** [comment]
Hi,

I'm having what I think is a similar issue. I'm trying to set the value of the autosuggest externally.

I've tried using `React.findDOMNode(this.refs.autosuggest.refs.input).value = match;` where `match` is my string value I am wanting to set to no avail.

**Comment by dnusca** [comment]
@leishman This may help - https://github.com/moroshko/react-autosuggest/issues/14

**Comment by leishman** [comment]
@dnusca Thanks for that link, however that's not exactly what I'm looking for. I want the input to be cleared when a form is submitted. I'm using this in a search bar at the top of my site, so the search text was staying there after the search was submitted. I want the field to stay filled after the suggest selection, but cleared when the form is submitted. When i manually change the value of the input like this, it works, but once the new route re-render happens, the old value appears again. I fixed this by giving the search box a random key that changes whenever the render occurs, forcing a re-mount of this component.

**Comment by moroshko** [comment]
@leishman You should be able to set the value using:

    React.findDOMNode(this.refs.autosuggest.refs.input).value = event.target.value;

    <Autosuggest ref="autosuggest" ... />

Have a look at [this example](http://jsbin.com/qepoca/1/edit?js,output).

I'm not sure what you mean by:

> but once the new route re-render happens, the old value appears again

Could you please create JSBin that demonstrates the issue?

**Comment by moroshko** [comment]
@dnusca Where you able to solve your issue? If not, could you please create JSBin that demonstrates the issue? You could use [this one](http://jsbin.com/qepoca/1/edit?js,output) as a starting point.

**Comment by leishman** [comment]
@moroshko Thanks for the response. If I have time, I will try to make a JS Bin. But with your solution, this merely manipulates the DOM right? It does not update the actual value in the state of the Autosuggest component.

If you reset this value as you suggest, then the component re-renders, it seems that the state remains unchanged and contains the previous value, so on re-render the previous value will appear again. Perhaps I am wrong about this though.

**Comment by moroshko** [comment]
@leishman You are right! Indeed, `state.value` doesn't change using this technique.

What's the ideal API you would expect to be able to set the value?

**Comment by dmitry** [comment]
What about `this.refs.autosuggest.setState({value: value});`?

**Comment by leishman** [comment]
To me it would make more sense to explicitly pass the value as a property into the component. This would be the more "react" way of doing it in my opinion.

**Comment by idolize** [comment]
@leishman Agreed.

@moroshko Perhaps the `value` prop could be used to set the state on the initial render *as well as* on `componentWillReceieveProps`? That way it can still maintain the "intermediate" state as the user is typing, but also get a new value from the parent without having to resort to a very "un-React" methodology of using setter functions.

In my opinion, this would be the "expected" behavior for such a component.

If you want, I'm happy to work on a PR which includes this (it should be very straightforward).

**Comment by moroshko** [comment]
@idolize Sounds good. PR would be appreciated :+1:

**Comment by idolize** [comment]
Just submitted a PR. I've tested and it works.

A few notes:
1. I moved `value` out of `inputAttributes` as it is now not really `<input>` specific
    - This is a breaking change, so perhaps the major version number should be incremented
2. I created a `defaultValue` prop to mimic the old, uncontrolled behavior (this is the standard I've seen in many other React components)
3. If using both `value` and `onSuggestionSelected`, the `value` will only update when a new suggestion is selected (not in intermediary changes) — the parent can override this behavior by attaching their callback to the `onChange` callback of the `inputAttributes`
4. The suggestion list is not triggered when the `value` prop changed (but it still is when the user types something, obviously). This is to avoid opening the suggestion list when, for example, a react-router route changes and the `value` is updated without direct user input inside the text field.

**Comment by moroshko** [comment]
@idolize Thanks a lot for the PR! Watch for some comments [there](https://github.com/moroshko/react-autosuggest/pull/32).

**Comment by idolize** [comment]
@moroshko Any more progress on this (I'd love to use this code as soon as possible)? Just curious if you are planning to add the object mapping code/tests or if you would like me to.

Personally, I'd feel more comfortable with you handling that because I don't really understand it as well.

**Comment by moroshko** [comment]
@idolize I'm happy to do what's left for 2.0. I have a lot going on at the moment, but I'll try to find time to finish this. Are you able to use the 2.0 branch from GitHub (rather than npm) for now?

**Comment by tpievila** [comment]
Would this make sense for even more tightly controlled component?

**Comment by moroshko** [comment]
react-autosuggest 2.0 is out! It supports controlled behaviour.

**Comment by idolize** [comment]
@moroshko Awesome! You rock.
