### ISSUE TITLE
Are there anything wrong with updateFocusedSuggestion in onKeyDown handler?

### ISSUE THREAD

**Issue by nhducit** [moroshko/react-autosuggest#280]
Are there any thing wrong in this line

https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L351
```
updateFocusedSuggestion(newFocusedSectionIndex, newFocusedItemIndex, value);
```
I think it should be:
```
updateFocusedSuggestion(newFocusedSectionIndex, newFocusedItemIndex, newValue);
```
`newValue` instead of `value`

**Comment by moroshko** [comment]
You could answer your own question by changing `value` to `newValue` and running the tests ;)
You'd notice that tests start fail. So, the short answer, is no. It's not a mistake.

I think in this case the name `value` is somewhat misleading. This third parameter means "the value before Up/Down", not the `newValue`.

**Comment by nhducit** [comment]
Thank you for your response.
