### ISSUE TITLE
Different implementation of WAI-ARIA combobox pattern

### ISSUE THREAD

**Issue by Leimi** [moroshko/react-autosuggest#283]
Hi,

Thanks for react-autosuggest!

I understand that the autocomplete design pattern is based on the combobox design pattern. [Here](https://www.w3.org/TR/wai-aria-practices/#combobox), it is mentioned there that there are two possible patterns for the combobox:

* one where the input as the role *combobox* and owns the *listbox* - this is what react-autosuggest does
* another where the container as the role *combobox* and owns the *listbox*

On the Candidate Recommandation page of WAI-ARIA 1.1 though, **[only the second pattern is described](https://www.w3.org/TR/wai-aria-1.1/#combobox)**.

Since only the second one is mentioned on the CR page, maybe it would be better to follow it instead of the current one?

**Comment by moroshko** [comment]
I just quickly checked what Google, Bing, and Facebook do, and they all seem to have `role="combobox"` on the `<input>`. Are you trying to say that they all ignore best practices? ;)

**Comment by Leimi** [comment]
Hah :D I actually didn't say that at all, but I'm not sure that would be the greatest argument. Just spend a few minutes on any of those websites and you'll notice some color contrast problems for example. So yeah, sometimes they do ignore best practices :)

I'm saying [the recommendation has changed](https://www.w3.org/TR/wai-aria-1.1/#combobox) and that it may be better to follow it. I'm not sure why on the _Authoring Practices_ page they list both ways to make a combobox, but seeing the ARIA 1.1 spec it's clear that the pattern changed.

**Comment by haltersweb** [comment]
Check out the thread on issue 485 for weigh-in by Bryan Garaventa who is a member of the W3C's ARIA working group.  https://github.com/moroshko/react-autosuggest/issues/485

**Comment by Leimi** [comment]
Hey, thank you for letting us know.
