### ISSUE TITLE
Rendering empty sections

### ISSUE THREAD

**Issue by joshlevinson** [moroshko/react-autosuggest#284]
In my application, when user searches for suggestions in a `multiSection` autosuggest I'd like to display the sections even if they're empty. Would you consider allowing a prop that would display something if a section is empty?

**Comment by moroshko** [comment]
I'm curious to hear a bit more about your use case. Could you describe what type of data you display?

**Comment by joshlevinson** [comment]
Thanks for the reply. Contrary to documentation, sections render even when empty.
Design specs for my use case require a message to be displayed under each section when it lacks results.
