### ISSUE TITLE
Pass query as a property to renderSuggestionsContainer

### ISSUE THREAD

**Issue by joshlevinson** [moroshko/react-autosuggest#285]
In my application, when user is presented with suggestions, I'd like to display their query at the bottom of the suggestions container.
It doesn't appear that `renderSuggestionsContainer` is passed the user's search query.

**Comment by joshlevinson** [comment]
Actually just uncovered the query as `children.props.renderItemData.query`.
Do you think it's worth passing the query in a higher-order fashion?
Is `children.props.renderItemData` considered internal/private?

**Comment by moroshko** [comment]
`children.props.renderItemData` is definitely considered "private", and I don't recommend using it.

Can I ask what exactly are you trying to achieve by showing the query at the bottom? Isn't it clear to users that the displayed suggestions are based on their input? Feel free to add a picture if it helps to explain the reasoning behind this. Before we extend the API, I'd like to make sure that it makes sense from user experience point of view.

**Comment by joshlevinson** [comment]
I'm working with a form that allows users to submit a question for consideration of being published on the site as an (later answered) Q&A.

As the user types their question, previously-answered/published Q&As are suggested to them, to encourage users to read content that may already have their answer. Without selecting an existing Q&A, submission of the form redirects users to a full question submission form with their query prepopulated.

Going back a bit–at the bottom of the suggestions window, there is linked text like:
Search for: "{{ query }}"
Which is meant to encourage users to search the site using their query; when clicked, the link takes the user to a search page based on their query.

**Comment by joshlevinson** [comment]
Here's a preview:
![Preview](https://www.dropbox.com/s/vkazfprns3b2sjh/Screenshot%202016-11-11%2012.58.40.png?dl=1)

**Comment by moroshko** [comment]
Thanks @joshlevinson, it makes perfect sense now!

Thinking about how to extend the API, I feel like just passing `query` like this:
```js
function renderSuggestionsContainer({ children, query, ...rest })
```
is probably not a good idea, because those users who don't care about `query` would still need to destructure it, or otherwise React would complain with something like:
> Unknown prop `query` on `<div>` tag. Remove this prop from the element.

The only reasonable solution I can think about is to introduce a breaking change:
```js
function renderSuggestionsContainer({ children, query, containerProps })
```
What do you think?

**Comment by joshlevinson** [comment]
I couldn't think of a way around the breaking change apart from the deprecation-inducing alternative 🙁

**Comment by moroshko** [comment]
@joshlevinson PR is welcome ;)

**Comment by moroshko** [comment]
In v9.0.0, you can get `query` in `renderSuggestionsContainer`.
