### ISSUE TITLE
Theme merge props instead replace it

### ISSUE THREAD

**Issue by savelichalex** [moroshko/react-autosuggest#288]
This is feature request. 
Maybe merge theme props instead full replace? (I'm looking at code and now it is in defaultProps). This is allow to not overwrite all class names, just what you really need to overwrite

**Comment by savelichalex** [comment]
Looks like that it should be in `react-autowhatever`, sorry 😄

**Comment by moroshko** [comment]
I'll close this issue as it belongs to [react-autowhatever](https://github.com/moroshko/react-autowhatever), but you are always welcome to submit a PR there ;)

**Comment by savelichalex** [comment]
I'm just want to know what do you think about this feature, before do some PR)
