### ISSUE TITLE
accessiblity feature: scroll focused suggestion into view

### ISSUE THREAD

**Issue by joeybaker** [moroshko/react-autosuggest#29]
It would be great, if the focused suggestion could use `scrollIntoView` so that we could ensure it was visible. 

Two options I can see for how to implement this:

1. `onSuggestionFocused` could pass the full `focus` event as a second parameter so that users could use DOM APIs to implement this themselves.
2. Just have this lib call `scrollIntoView` on focus.

**Comment by moroshko** [comment]
@joeybaker We already have a [similar issue](https://github.com/moroshko/react-autosuggest/issues/21).

Thanks a lot for your suggestions! I adapted the `scrollIntoView` approach.

It's fixed in v1.14.1

**Comment by joeybaker** [comment]
Sorry for the dupe! Thank you!
