### ISSUE TITLE
Add label to Autosuggest for input fields

### ISSUE THREAD

**Issue by NickCain** [moroshko/react-autosuggest#290]
In the application I am working on, I require a label for input, it would be good to have a `label` element to be passed as a inputProp or something along these lines, so this can then be styled, updated etc. 

An example would be on: http://react-toolbox.com/#/components/autocomplete

**Comment by moroshko** [comment]
Label is not part of react-autosuggest, and to be honest, I don't see a good enough reason to include it. You can always add the label in your app.

**Comment by NickCain** [comment]
Ok fair enough. Thanks for getting back to me.

**Comment by mjoyce91** [comment]
WAVE picks this up an error, so I don't think it would be too out of the question to add this as a feature.

**Comment by vaibhav50596** [comment]
@NickCain were you able to add label for autosuggest input?

**Comment by ravshrestha9** [comment]
I am having the same issue. Tried adding labels outside autosuggest, but still getting that WAVE error.
