### ISSUE TITLE
Display a custom message when there is no suggestions

### ISSUE THREAD

**Issue by hielfx** [moroshko/react-autosuggest#291]
## Feature request

I think it would be great to display some custom message when the suggestions list is empty.

One example can be found on the video games web site [g2a.com](https://www.g2a.com/?___store=english).

I attatch a picture of the fuctionality.

![](https://i.gyazo.com/b5beb35b1878a108bdd63f576c26b825.png)

EDIT: if there is a way to do this in the current version I would be pleased if you tell me how to achieve this.

**Comment by moroshko** [comment]
"No results" message is not part of react-autosuggest. It's totally up to you how to implement it. 
[Here is one example.](http://codepen.io/moroshko/pen/wMRmmM)
Hope this helps.
