### ISSUE TITLE
Poor render performance on large list

### ISSUE THREAD

**Issue by DigitalMarc** [moroshko/react-autosuggest#292]
Hi,
I have a large list of suggestions. I was wondering if there is a way to show a maximum number of suggestions at any time to reduce the performance issue or any other performance trick.
Thanks for the help,
Marc

**Comment by moroshko** [comment]
To limit the amount of displayed suggestions, just limit whatever you pass to `suggestions={...}`.
For example, to display the first 5 suggestions, do:
```js
<Autosuggest suggestions={mySuggestions.slice(0, 5)} ... />
```
