### ISSUE TITLE
Full suggestions list to render when focusing on input

### ISSUE THREAD

**Issue by NickCain** [moroshko/react-autosuggest#294]
I was wondering if I could have some help regarding rendering the Suggestions List when I click to focus on the the input.

I have tired using the `renderSuggestion` prop but I cannot seem to get it to work.

My aim is when I focus on the input it shows the full list of suggestions until I start to type to filter it.

Is this possible?

Thanks in advance.

**Comment by moroshko** [comment]
It is possible. Check out [this example](http://codepen.io/moroshko/pen/kXpapq).

**Comment by NickCain** [comment]
Thank you for getting back to me, managed to resolve my issue with your example! Thanks again.
