### ISSUE TITLE
how to open the dropdown without focus on the input?

### ISSUE THREAD

**Issue by tahaykACF** [moroshko/react-autosuggest#295]
I have an input and the react-autosuggest component, both uses the same state as a value, I want to make the dropdown open when I write somthing in the input without focus on the autosggest input but I can't figure out a way to do it.
I have already tried, the value changes but the dropdown does not open.

**Comment by moroshko** [comment]
Check out [alwaysRenderSuggestions](https://github.com/moroshko/react-autosuggest#alwaysRenderSuggestionsProp). If you still can't figure it out, please create a Codepen that demonstrates the issue (you can use [this](http://codepen.io/moroshko/pen/LGNJMy) as a start).

**Comment by tahaykACF** [comment]
No It didn't work, 
You can check it in [Codepen](http://codepen.io/tahayk2/pen/wogWee#code-area)
I want the AutoSuggest's dropdown to open when I write something in the first input.

**Comment by moroshko** [comment]
If you want suggestions to change, you need to update them:
```js
handleChange = event => {
  const newValue = event.target.value;
    
  this.setState({
    value: newValue,
    suggestions: getSuggestions(newValue)  // You missed this!
  });
};
```
[Codepen](http://codepen.io/moroshko/pen/jVyBVd)

**Comment by tahaykACF** [comment]
Yes, that's what I was missing. Thank you very much @moroshko for your help.
