### ISSUE TITLE
First option does not get selected when tab is pressed

### ISSUE THREAD

**Issue by snakeyak** [moroshko/react-autosuggest#297]
Is seems the selecting an option with a tab key does not work without moving up or down in the suggestion box (`focusFirstSuggestion` enabled). This makes it a bit weird, as chances are the first option is the one the user wants to select.

Steps to reproduce:
1) http://codepen.io/snakey/pen/QGqVeM
2) Type "clo"
3) Hit <kbd>tab</kbd>
4) "Clojure" is NOT selected, even though it has been highlighted

**Comment by moroshko** [comment]
By default, blurring the input does nothing. 

[Here](http://codepen.io/moroshko/pen/WoXQeg) is an example of how you could update the input value to be the highlighted value when input is blurred.

**Note:** this solution doesn't take into account **how** the input was blurred. So, if you blur it by clicking outside the input, it would have the same effect as if you hit <kbd>tab</kbd>.

**Comment by snakeyak** [comment]
@moroshko Perfect, thank you!
