### ISSUE TITLE
Using non-suggested value

### ISSUE THREAD

**Issue by dmitry** [moroshko/react-autosuggest#30]
Is it possible to use not suggested value, by inputing `enter`? 

From the source it looks impossible to have such behaviour: 
https://github.com/moroshko/react-autosuggest/blob/54aae81c907948109eb13e22a6e83a3660f63e9c/src/Autosuggest.js#L231

**Comment by moroshko** [comment]
@dmitry What do you want to happen when you hit `Enter`?

**Comment by dmitry** [comment]
@moroshko to invoke some callback similar to `onSuggestionSelected`. Right now I don't believe it's possible to have such behaviour, except to use `onKeyUp` callback in `inputAttributes` props.

**Comment by moroshko** [comment]
@dmitry Note that input's value changes when user interacts with the Up/Down keys. I feel like you should be updating your search results either `onSuggestionSelected` or on `inputAttributes.onChange`. When user hits Enter, we just close the suggestions list. Could you explain please why would you want to update the results only when user hits Enter?

**Comment by dmitry** [comment]
@moroshko for example, I have a location input, when I type I would like to see suggested cities and countries. But some of them might be not in our suggester database, and still we would like to give a user possibility to choose his value (not in auto-suggest listing).

Right now I found only one possibility of doing that by getting `input` `value` of `autosuggest` component through `findDOMNode` while the form `onSubmit` callback invoked:

```javascript
React.findDOMNode(this.refs.autosuggest.refs.input).value
```

What do you think, is there might be a better practice of doing that?

**Comment by moroshko** [comment]
@dmitry I think using form's `onSubmit` is indeed what you want. See also #22.

If you intercept form's submission, and perform an AJAX request, then getting input's value using `findDOMNode`, as you specified, should do the trick. If you feel like you expect a better/simpler API from Autosuggest, let me know your wildest dream ;)

**Comment by dmitry** [comment]
After living for some time with the current solution I believe it's the best way to make it work as I want to. @moroshko thank you for your help, again! :+1:
