### ISSUE TITLE
How to theme state-dependent child elements with inline styles?

### ISSUE THREAD

**Issue by josiahsprague** [moroshko/react-autosuggest#301]
I'm trying to use inline JS styles to style my Autosuggest component, but I'm running into a pretty basic problem. I can't figure out how to style a child component based on the state of the Autosuggest. Basically, I want the suggestions container to be hidden unless the container's state is "open". I want to target what is by default `.react-autosuggest__container--open .react-autosuggest__suggestions-container`, but without using classes. 
I tried what I would expect to work, with no luck:
```js
var theme = {
  suggestionsContainer: {
    display: 'none'
  },
  containerOpen: {
    suggestionsContainer: {
      display: 'block'
    }
  }
};
```

How can I do this?

**Comment by prasadsilva** [comment]
I'm running into this as well. @josiahsprague Did you figure out a solution?

**Comment by moroshko** [comment]
@josiahsprague Inline styles are limited. They don't support nesting.

v9.0.0 adds few extra keys to `theme` to help with inline styles. Check out [this Codepen](http://codepen.io/moroshko/pen/OpPqxY).

If you need a better control over styling, you should probably use something like CSS Modules, Radium, etc.

Hope this helps.
