### ISSUE TITLE
Warning after updating to version 7.0.2

### ISSUE THREAD

**Issue by fabiozaffani** [moroshko/react-autosuggest#307]
Currently, in development, I'm receiving the following warning after updating to version 7.0.2:

> Warning: Failed context type: Invalid context `storeSubscription` of type `Subscription` supplied to `Connect(Autosuggest)`, expected instance of `Subscription`.

Rolling back to 7.0.1 fixed the issue.

**Comment by rohozhnikoff** [comment]
same issue
at first look - it doesn't affect any features

**Comment by moroshko** [comment]
Probably related to https://github.com/reactjs/react-redux/pull/579

**Comment by moroshko** [comment]
`redux` and `react-redux` dependencies were removed in [v8.0.0](https://github.com/moroshko/react-autosuggest/releases/tag/v8.0.0). 

Could you please upgrade and verify that the issue is gone?
