### ISSUE TITLE
Dropdown closes on focus lost, but does not re-open on focus gained

### ISSUE THREAD

**Issue by pathsny** [moroshko/react-autosuggest#31]
Specifically the way this manifests is when I switch to a different window and return the dropdown should re-open. Instead I end up in a state where the textbox has text and is selected but the dropdown is not open.

The component should listen to onfocus and re-open.

**Comment by moroshko** [comment]
@pathsny I agree. I'll have a look at fixing this when I have some spare time, but feel free to submit a Pull Request to speed up things ;)

**Comment by moroshko** [comment]
@pathsny It is fixed in 1.16.1 now. Enjoy!

**Comment by pathsny** [comment]
Thank you
