### ISSUE TITLE
CSS module classes not showing up on components

### ISSUE THREAD

**Issue by oyeanuj** [moroshko/react-autosuggest#310]
Hi @moroshko! Firstly, thank you for creating this super-useful library! :)

I had an issue while trying to theme using CSS Modules. Using the example in the readme, I couldn't get up the css-modulified class names to show up on autosuggest components. Here is the code that I have:

```jsx
import theme from 'theme/autosuggest.scss';
... 
//and within render
<Autosuggest theme = {theme} ... />
```

The theme object looks like the following:
```js
console.log(theme);
{
  react-autosuggest__container: "react-autosuggest__container___JJ3wa",
  react-autosuggest__container--open: "react-autosuggest__container--open___1BXdq",
  react-autosuggest__input: "react-autosuggest__input___LvY0-",
  react-autosuggest__suggestion: "react-autosuggest__suggestion___LnVYk",
  react-autosuggest__suggestion--focused: "react-autosuggest__suggestion--focused___DmV9h",
  react-autosuggest__suggestions-container: "react-autosuggest__suggestions-container___1PcFV",
  react-autosuggest__suggestions-list: "react-autosuggest__suggestions-list___3WDDP"
}
```

If I manually add those as classes to each of those inner components, then styling shows up.

Unfortunately, I wasn't sure how to set up a simple codepen for this, but I am hoping that the details above will help you guide me towards the possible problems.

Thank you!

**Comment by moroshko** [comment]
`theme` keys should be `container`, `input`, etc (not `react-autosuggest__container`, `react-autosuggest__input`, etc).

**Comment by oyeanuj** [comment]
Ah, I didn't understand the Readme properly then. That fixed it - appreciate the quick response! :)

**Comment by dsaw** [comment]
I am having the same issue, except that when I log the theme it comes up as an empty object. The scss file contains the classes given in docs (`container, input`). I guess scss needs to be set up with css modules for this to work? The create-react-app by default doesn't support this I suppose.

**Comment by dsaw** [comment]
I got the solution to this, seems you only need to replace the filename with `filename.module.scss` and it works right out of the box. [https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/)
