### ISSUE TITLE
Force onSuggestionsFetchRequested, forcing dropdown show or refresh if needed

### ISSUE THREAD

**Issue by lorenzos** [moroshko/react-autosuggest#319]
I have an autosuggest input that fetches suggestion filtering a bigger array, which is in the component's state too. Let's say my state is like:

    { 
        allPossibleSuggestions: [],
        suggestions: [], // Filled by onSuggestionsFetchRequested, filtering the previous array with user input
    }

The fact is that `allPossibleSuggestions` changes asynchronously. How can I "force" a call to `onSuggestionsFetchRequested` when this happens, considering that the user may be or may be not focusing the autosuggest field, with or without text already entered?

Calling `.focus` do not help, because I don't wont to force focus if user is doing something else.

**Comment by moroshko** [comment]
Autosuggest calls `onSuggestionsFetchRequested` to notify you that you should probably update `suggestions`. You cannot "force" a call to it.

Can't you just update the state:
```js
this.setState({
  suggestions: ...
});
```
whenever `allPossibleSuggestions` changes?

If this doesn't help, please create a Codepen to demonstrate the issue.

**Comment by lorenzos** [comment]
@moroshko Yeah, setting the state is what I currently do. The fact is that it gets a little tricky because in case of multiple autosuggest input you have to manually track focus in order to pass the correct value the the filter function. This is what my code looks like now after `allPossibleSuggestions` changes because of an asynchronous request:

```javascript
this.focusedInput: null, // A ref to currently focused <input>

asyncRequestEnd: (response) => {
    this.setState({
        allPossibleSuggestions: response.data
    }, () => {

        // Force autosuggest to re-fetch suggestions
        if (this.focusedInput !== null) {
            this.onSuggestionsFetchRequested({ value: this.focusedInput.value || '' });
        }

    });
},

render: () => {
    const inputProps = {
        onFocus: (target) => this.focusedInput = target,
        onBlur: (target) => if (this.focusedInput == target) this.focusedInput = null },
        // ...
    };
    return (
        <p>
            <Autosuggest ... inputProps={inputProps} />
            <Autosuggest ... inputProps={inputProps} />
            <Autosuggest ... inputProps={inputProps} />
        </p>
    );
}
```

It would be nice to be able to remove all of that logic with a `Autosuggest` component method that forces suggestions refresh. I think this can be a simple call to `onSuggestionsFetchRequested` with the correct value, done only if the input is currently focused and `shouldRenderSuggestions` is true.

**Comment by moroshko** [comment]
Sorry, I really struggle to understand the issue. Not sure which filter function you are talking about. Also, it doesn't feel right to me to pass the same `inputProps` to all Autosuggests (how are they different?).

**Comment by lorenzos** [comment]
@moroshko What I called the *filter function* is the implementation for `onSuggestionsFetchRequested`, it filters `state.allPossibleSuggestions` into `state.suggestions` depending on input's value. 

My app need more than one input, the number can vary dynamically, but they all share the same list of possible suggestions and same props. There's no difference, just the user can enter multiple values.

As I said, I found a way to make it work like I need, only feels more complicated than it should be to me. If you have understood what's the request here, but you still think it shouldn't be implemented inside the `Autosuggest` component, no problem.

**Comment by moroshko** [comment]
Happy to hear that you found a solution. 
I tried to help, but I still can't say that I understand the problem. 
I'll close the issue for now, but if you feel strongly that the Autosuggest API can be improved, please  open a new issue and provide a minimal working Codepen that demonstrates the idea.
