### ISSUE TITLE
IOS - One extra space when delete content of the input field.

### ISSUE THREAD

**Issue by paulailincai** [moroshko/react-autosuggest#321]
IOS
1. Type in a word in the input field (or type 'c')
2. Delete the word.

After delete the last letter (the first letter of the word), there is still one empty space left to delete. Noticed that on your main website too(http://react-autosuggest.js.org/), viewing on iphone.

**Comment by VictorChenLi** [comment]
set `autoComplete="off"` and `autoCorrect="off"` seems fix the issue for me

**Comment by moroshko** [comment]
[`auto-correct` is a non-standard attribute.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocorrect) Therefore, I think it should not be part of `react-autosuggest`.

You can always add it using `inputProps`.
