### ISSUE TITLE
calculation of suggestions onFocus

### ISSUE THREAD

**Issue by jehrlich** [moroshko/react-autosuggest#325]
I have an application using a chain of Autosuggest inputs for which each input's suggestions depend on values in the other inputs. Calculating suggestions is a bit costly, and users may select inputs in any order, so it is desirable to calculate suggestions just-in-time when an input receives focus. I thought that triggering recalculation of suggestions with `onFocus()` would do this, but no.

I also want the inputs to display suggestions immediately when they receive focus, and was  mystified that it did not happen , but I could trigger display of suggestions by typing a space. It was because initial suggestions were empty, so that was easily solved by calculating initial suggestions at loading.

The problem seems to be that suggestions triggered by `onFocus()` are too late to be displayed in that rendering. Triggering a re-render (e.g. by typing space) shows the suggestions calculated by the onFocus of the previous render. 

 I'm following the action with console.log statements, and this behavior seems to be consistent - suggestions generated from the onFocus event are not displayed in that rendering cycle. The render associated with the onFocus event uses suggestions as they existed before the OnFocus event.

This seems not correct to me, and is a problem in my situation. Is there a fix or workaround?

Thanks!

**Comment by moroshko** [comment]
Sorry, I'm not sure I understand your problem. 

The calculation of suggestions is your application concern. Autosuggest just gets the calculated suggestions and renders them.

If you want to display some suggestions when the input is empty, check out [shouldRenderSuggestions](https://github.com/moroshko/react-autosuggest#shouldrendersuggestions-optional).

**Comment by jehrlich** [comment]
I'm sorry, Misha. It turns out to be my error. I was failing to pass the callback which recalculates suggestions to onFocus.

**Comment by jehrlich** [comment]
My `onSuggestionsFetchRequested` method uses a prop (call it X) along with the input value to calculate the  array stored to state.suggestions. I pass autosuggest a callback as an onFocus prop to update the X prop which then triggers `onSuggestionsFetchRequested` which updates state.suggestions. The suggestions that are rendered, though, reflect state.suggestions **before** the onFocus callback, so have not been updated for the new X prop. If I then type a space or other character, `onSuggestionsFetchRequested` is called again, and the suggestions **after** that update are rendered.

For my purposes, it would be desirable for autosuggest to read and render the suggestions array **after** the function passed as the onFocus prop returns, rather than before.

**Comment by moroshko** [comment]
Why do you specify `onFocus` in the first place?

**Comment by jehrlich** [comment]
I want to have suggestions show immediately when the user clicks on the input, and I want to calculate them just-in-time because they depend on other inputs which may be filled in a random order and may generate an ajax call.

**Comment by moroshko** [comment]
Have a look at this [Codepen](http://codepen.io/moroshko/pen/pRmXQG?editors=0010). 

It has two "connected" Autosuggests which shows suggestions when input is focused and also calculates suggestions "just in time".

Note that I didn't use `onFocus`.

Feel free to adjust the Codepen to your needs to demonstrate the issue you are experiencing.

**Comment by jehrlich** [comment]
Thank you. My problems are fixed by calculating my prop (called X above) directly from the render method. "Leave calculations and conditionals to the render function." was a useful rule in this case. This was a React problem, not an autosuggest problem.
