### ISSUE TITLE
multiple search parameters?

### ISSUE THREAD

**Issue by henryhardy** [moroshko/react-autosuggest#326]
Is there currently a way to do multiple search parameters, which each based on an auto complete? 

I am trying to rebuild something similar to pinterests search functionality where you can search for objects that match multiple parameters.

Thanks, and love the component so far =]

**Comment by moroshko** [comment]
Could you elaborate a bit, and provide some examples of what are you trying to achieve?

**Comment by henryhardy** [comment]
So an example would be.. 

I type in part of a word, and some suggestions come up - i select the suggestion i want either by clicking or hitting enter, then hit space and start typing a new word. This then starts doing search on  the new work I am typing. I was just wondering if this functionality is already in there before I start adding it in myself.

thanks!

**Comment by moroshko** [comment]
Nope. Autosuggest doesn't support this. Maybe have a look at [react-tags](https://github.com/i-like-robots/react-tags).

**Comment by giko45** [comment]
You can fix this with a regexp

```
suggestionsFilter={(opt, val) => {
          var p = val.toLowerCase().replace(/  +/g, ' ').trim().split(' ')
          var searchIn = opt.name.toLowerCase()
          var all_match = p.every(x => searchIn.indexOf(x) !== -1)
          return all_match
        }}

```
