### ISSUE TITLE
setting the type of the input

### ISSUE THREAD

**Issue by pathsny** [moroshko/react-autosuggest#33]
Is it possible to set the type of the input? For example, setting input type=search, creates an automatic "clear" button which is pretty useful.

**Comment by moroshko** [comment]
@pathsny At the moment, it is not possible. If you set `inputAttributes={{ type: 'search' }}`, Autosuggest will override it with `type='text'`. Feel free to submit a PR. Should be easy :)

**Comment by moroshko** [comment]
@pathsny Starting from version 1.17.0 you are able to change input's type:

    inputAttributes={{ type: 'search', ... }}

Enjoy!
