### ISSUE TITLE
Fire onSuggestionSelected when Tab key is pressed

### ISSUE THREAD

**Issue by Jackleberry** [moroshko/react-autosuggest#332]
I would like to add the ability to fire onSuggestionSelected when the Tab key is pressed. At the moment it only fires on pressing Enter or clicking.

This is the PR: https://github.com/moroshko/react-autosuggest/pull/333

**Comment by Jackleberry** [comment]
I've made a PR with the change I suggested above as well as the right arrow selection.
The onSuggestionSelected will now fire as well when tab or right arrow are pressed.

@moroshko how do you feel about merging in this functionality?

**Comment by bbarnell** [comment]
@moroshko Please merge this into the master and update the UMD build.

**Comment by rituvesh** [comment]
Hi,

Could you please confirm that the selection from tab is is merged ? If yes then please let me know which version I should install.

With regards,
Rituvesh

**Comment by bbarnell** [comment]
@rituvesh The tab key is working on the UMD build for the 9.3.2 version.

**Comment by rituvesh** [comment]
Thanks a lot!

**Comment by rituvesh** [comment]
Hi,
 I can see the tab was implemented https://github.com/moroshko/react-autosuggest/pull/333/files?diff=split
but when I see the new code now only 'enter' and 'click' is used. 'tab' is removed
`onKeyDown: (event, data) => {
        const { keyCode } = event;

        switch (keyCode) {
          case 40: // ArrowDown
          case 38: // ArrowUp
            if (isCollapsed) {
              if (shouldRenderSuggestions(value)) {
                onSuggestionsFetchRequested({
                  value,
                  reason: 'suggestions-revealed'
                });
                this.revealSuggestions();
              }
            } else if (suggestions.length > 0) {
              const {
                newHighlightedSectionIndex,
                newHighlightedItemIndex
              } = data;

              let newValue;

              if (newHighlightedItemIndex === null) {
                // valueBeforeUpDown can be null if, for example, user
                // hovers on the first suggestion and then pressed Up.
                // If that happens, use the original input value.
                newValue =
                  valueBeforeUpDown === null ? value : valueBeforeUpDown;
              } else {
                newValue = this.getSuggestionValueByIndex(
                  newHighlightedSectionIndex,
                  newHighlightedItemIndex
                );
              }

              this.updateHighlightedSuggestion(
                newHighlightedSectionIndex,
                newHighlightedItemIndex,
                value
              );
              this.maybeCallOnChange(
                event,
                newValue,
                keyCode === 40 ? 'down' : 'up'
              );
            }

            event.preventDefault(); // Prevents the cursor from moving

            this.justPressedUpDown = true;

            setTimeout(() => {
              this.justPressedUpDown = false;
            });

            break;

          // Enter
          case 13: {
            // See #388
            if (event.keyCode === 229) {
              break;
            }

            const highlightedSuggestion = this.getHighlightedSuggestion();

            if (isOpen && !alwaysRenderSuggestions) {
              this.closeSuggestions();
            }

            if (highlightedSuggestion !== null) {
              const newValue = getSuggestionValue(highlightedSuggestion);

              this.maybeCallOnChange(event, newValue, 'enter');

              this.onSuggestionSelected(event, {
                suggestion: highlightedSuggestion,
                suggestionValue: newValue,
                suggestionIndex: highlightedSuggestionIndex,
                sectionIndex: highlightedSectionIndex,
                method: 'enter'
              });

              this.justSelectedSuggestion = true;

              setTimeout(() => {
                this.justSelectedSuggestion = false;
              });
            }

            break;
          }

          // Escape
          case 27: {
            if (isOpen) {
              // If input.type === 'search', the browser clears the input
              // when Escape is pressed. We want to disable this default
              // behaviour so that, when suggestions are shown, we just hide
              // them, without clearing the input.
              event.preventDefault();
            }

            const willCloseSuggestions = isOpen && !alwaysRenderSuggestions;

            if (valueBeforeUpDown === null) {
              // Didn't interact with Up/Down
              if (!willCloseSuggestions) {
                const newValue = '';

                this.maybeCallOnChange(event, newValue, 'escape');

                if (shouldRenderSuggestions(newValue)) {
                  onSuggestionsFetchRequested({
                    value: newValue,
                    reason: 'escape-pressed'
                  });
                } else {
                  this.onSuggestionsClearRequested();
                }
              }
            } else {
              // Interacted with Up/Down
              this.maybeCallOnChange(event, valueBeforeUpDown, 'escape');
            }

            if (willCloseSuggestions) {
              this.onSuggestionsClearRequested();
              this.closeSuggestions();
            } else {
              this.resetHighlightedSuggestion();
            }

            break;
          }
        }

        onKeyDown && onKeyDown(event);
      }
    };`

**Comment by rituvesh** [comment]
Looks like PR was closed https://github.com/moroshko/react-autosuggest/pull/333

@moroshko I agree with the first point, and I see what you're saying with the second. I think I have a general frustration about the default tab functionality, however what you've said is they way it should work. I'll close the PR.
--

**Comment by aberezkin** [comment]
Close it for the same reason #333 was closed.
