### ISSUE TITLE
Do you plan to implement the multi select feature like react-select?

### ISSUE THREAD

**Issue by bibobibo** [moroshko/react-autosuggest#336]
In my application, I need to implement the feature to support multi options inside the input box, like multi-select of http://jedwatson.github.io/react-select/. Since it doesn't support customize suggestion, we plan to switch to react-autosuggest.
React-autosuggest is really very cool. I wondered that do you consider to support multi-select or customize input box in the future?

**Comment by bibobibo** [comment]
Just found the renderInputComponent, it is quite awesome! I like the interface design of autosuggest.

**Comment by slavab89** [comment]
Could you please share how did you manage to achieve that?
Meaning, how did you render the input component?

**Comment by pravinbashyal** [comment]
Did anyone figure out how to implement multiselect?

**Comment by mariohdez** [comment]
@pravinbashyal I created a custom 'selected' component where every time the user selects a value, I add to the custom selected component.

**Comment by animesh-sharama** [comment]
@mariohdez Could you share that?
