### ISSUE TITLE
How to set default value?

### ISSUE THREAD

**Issue by araneta** [moroshko/react-autosuggest#337]
## Are you reporting a bug?
no

Is it possible to set the default value and default label? here is my render function

    return (<Select.Async value={value} valueKey="code" labelKey="name"  onChange={this.onChange}  loadOptions={this.getNationalities2} backspaceRemoves={this.state.backspaceRemoves} />)

**Comment by moroshko** [comment]
Are you sure you posted the question in the right repo?
This repo is for `Autosuggest`, I', not sure what `Select.Async` is.
The default value in Autosuggest is simply the initial value of the `value` prop you pass to it.
