### ISSUE TITLE
tree render

### ISSUE THREAD

**Issue by giko45** [moroshko/react-autosuggest#338]
hi,

Is it possible to render items as an en hiarchical ul/li list according to
https://jsfiddle.net/6wwan1fn/2/

**Comment by moroshko** [comment]
Only one level of nesting is supported by [multiSection](https://github.com/moroshko/react-autosuggest#multiSectionProp). 

But, since you have full control over suggestions rendering (see [renderSuggestionsContainer](https://github.com/moroshko/react-autosuggest#renderSuggestionsContainerProp) and [renderSuggestion](https://github.com/moroshko/react-autosuggest#renderSuggestionProp)), you have a lot of freedom, and I suspect it is possible to achieve deep nesting (I haven't tried that though).

**Comment by giko45** [comment]
Hi,

I tried you suggestion  with react-chips (see attached code 
[custom.txt](https://github.com/moroshko/react-autosuggest/files/833380/custom.txt)

).
However  a whole subtree is identified as one item and as such a whole subtree is selectable and not each branch.

**Comment by anandthanki1** [comment]
Hey @moroshko, with react-autosuggest is it possible to show suggestions with deep nesting ?

For e.g. 

```
let suggestions = [
{
    title: 'abc',
    suggestions: [
        {
             title: 'def',
             suggestions: [
                 'I think we can do it',
                 'Is it possible?'
             ]
        }
    ]
}


]
```

I want to show above suggestions array as: 

```
abc :                                                 <---- Section Title
   def :                                                <---- Sub Section Title
          'I think we can do it'                <----- Suggestions
           'Is it possible?'
```

Can you give your opinion on how can I achieve this behavior ?

Thank you for your time.

**Comment by wesleyicarros** [comment]
> Hey @moroshko, with react-autosuggest is it possible to show suggestions with deep nesting ?
> 
> For e.g.
> 
> ```
> let suggestions = [
> {
>     title: 'abc',
>     suggestions: [
>         {
>              title: 'def',
>              suggestions: [
>                  'I think we can do it',
>                  'Is it possible?'
>              ]
>         }
>     ]
> }
> ]
> ```
> 
> I want to show above suggestions array as:
> 
> ```
> abc :                                                 <---- Section Title
>    def :                                              <---- Sub Section Title
>           'I think we can do it'              <----- Suggestions
>            'Is it possible?'
> ```
> 
> Can you give your opinion on how can I achieve this behavior ?
> 
> Thank you for your time.

Hey @anandthanki1 
I had the same problem you commented here. My solution was transform the array that needed to be rendered recursively into a flatted one (maintaining the order I wished  before). The next step is use a property that indicates the type of object you're dealing with, and using it you can manually add a margin-left (at **renderSuggestion**), for example, to keep the tree render appearance.

This way react autosuggest works perfectly. 



To do it, I used this piece of code:

```js
const flatChildren = (items) => {
  const flat = [];

  items.forEach((item) => {
    flat.push(item);
    if (Array.isArray(item.children) && item.children.length > 0) {
      flat.push(...flatChildren(item.children));
      delete item.children;
    }
    delete item.children;
  });

  return flat;
};


```
