### ISSUE TITLE
How to using createClass?

### ISSUE THREAD

**Issue by alexanderbahmatov** [moroshko/react-autosuggest#340]
Hello, can  you help me?
I'm trying to use your project to make component using React.createClass. Can you show me the example of this creating?

**Comment by moroshko** [comment]
[You should be using JavaScript classes instead of `React.createClass`.](https://facebook.github.io/react/blog/#migrating-from-react.createclass)

Check out this [Basic Example](http://codepen.io/moroshko/pen/LGNJMy).
