### ISSUE TITLE
Autosuggest does not work with Infefno.js

### ISSUE THREAD

**Issue by AlgoTrader** [moroshko/react-autosuggest#341]
Due to performance reasons I have to use Inferno.js. Autosuggest "almost" work there. There is a single stuff that breaks normal work. this is method storeReferences:

```
 storeReferences = autowhatever => {
    if (autowhatever !== null) {
      const { input, itemsContainer } = autowhatever;

      this.input = input;
      this.suggestionsContainer = itemsContainer;
    }
  };
```

You rely on the assumption that autowhatever is fully initialized when ref func is called. That's true in React but not in Inferno. Can you please store autowhatever ref itself and dereference it in componentDidMount? autowhatever object properly passed, but it has no input property yet.

On selecting any value from dropdown, there is the follwing error:
```
Autosuggest.js:660 Uncaught TypeError: Cannot read property 'focus' of undefined
    at Object.onSuggestionClick [as onClick] (Autosuggest.js:660)
    at Item._this.onClick (Item.js:74)
    at dispatchEvent (inferno.node.js:426)
    at dispatchEvent (inferno.node.js:437)
    at HTMLDocument.docEvent (inferno.node.js:463)
```
I have to branch Autosuggest for now and patch it locally.

**Comment by AlgoTrader** [comment]
I made it working in inferno.js:

![image](https://cloud.githubusercontent.com/assets/1556262/23950244/5b628b10-099b-11e7-8225-d8f916a063d5.png)

I moved autowhatever dereferencing to componentDidMount

**Comment by AlgoTrader** [comment]
PR is there https://github.com/moroshko/react-autosuggest/pull/342

**Comment by moroshko** [comment]
@AlgoTrader Thanks for this!
I haven't had a chance to play with Inferno yet.
Do you mind creating a Codepen (similar to [this one](http://codepen.io/moroshko/pen/LGNJMy)) that uses Inferno and your patched version so I could play with it?

**Comment by AlgoTrader** [comment]
I tried without any success. I use babel with plugins and webpack, no success with dist versions. I cannot understand how to use "prebundled" versions.

**Comment by AlgoTrader** [comment]
Inferno 1.4.0 is not properly packaged - https://github.com/infernojs/inferno/issues/934
Have to wait for fix

**Comment by AlgoTrader** [comment]
I implemented Codepen example. http://codepen.io/AntonZ/pen/LWBXOL
It was tricky to do.

**Comment by moroshko** [comment]
Could you test please [v9.0.1](https://github.com/moroshko/react-autosuggest/releases/tag/v9.0.1) and let me know if it works as expected?

**Comment by AlgoTrader** [comment]
I have tested the 9.0.1 and it works without any problems. I switched back to npm autosuggest version

**Comment by moroshko** [comment]
Thanks for confirming 👍
