### ISSUE TITLE
Keep autosuggest text search in focus even when user deletes search text

### ISSUE THREAD

**Issue by glorp47** [moroshko/react-autosuggest#345]
I've noticed that for some reason, whenever I'm using the text search function for Autocomplete, the component ceases to be in focus and the text cursor disappears if I delete the last character from the search bar. However, this doesn't seem to happen in the Codepen examples, so I've been trying to debug this to no avail. It doesn't seem like I can set a ref to the input field and then use the .focus() method on it either, so I'm a bit at a loss. Thanks.

**Comment by moroshko** [comment]
Which browser/OS did you observe this behavior?

**Comment by glorp47** [comment]
In both Firefox and Safari.

**Comment by glorp47** [comment]
My bad, I found the bug. I was stupidly setting the key for the component to a random number which was inducing component re-rendering. Fun times.
