### ISSUE TITLE
React native usage

### ISSUE THREAD

**Issue by vongohren** [moroshko/react-autosuggest#346]
Im considering to use this in react native, since im using redux and stores and everything on this platform. And since I saw that one can render its own input, meaning I can try to use <TextInput> which is react native component and bridge all the methods/props.

But my question is, has anyone tried or thought about this?

**Comment by vongohren** [comment]
Didnt end up using this

**Comment by phil-andrews** [comment]
I've been wondering if this would work with react-native. What did you end up going with?

**Comment by vongohren** [comment]
I ended just up making my own, it was a simple thing we needed

**Comment by rohozhnikoff** [comment]
when i port web to native app, i developed own component, which is api-compatible
not 100% all api methods, but i hope, you will find this piece valuable for your app

https://gist.github.com/rohozhnikoff/b0e8868c7dfb440ffd43266688a05ad1
