### ISSUE TITLE
on press Enter in input field or suggestion is not triggering onChange handler 

### ISSUE THREAD

**Issue by rumanhassan** [moroshko/react-autosuggest#348]
Even in Demo codePen has the same issue.

http://codepen.io/moroshko/pen/OpPqxY

When i am typing C and pressing enter key its not triggering OnChange handler, "Up", "Down", "Escape" and "Click" is working fine.

Any help is really appreciated.

Thanks.

**Comment by moroshko** [comment]
I assume you are pressing Enter when you have a highlighted suggestion. If so, the input value is not changing (it stays the same). This is why `onChange` is not triggered. `onChange` is triggered only when the input value **changes**. 
Is [onSuggestionSelected](https://github.com/moroshko/react-autosuggest#onSuggestionSelectedProp) what are you looking for?

**Comment by rumanhassan** [comment]
I was looking for an event from input field, when a user press enter without selecting any string. 

I am looking the functionality for following usecase: 
User type a string and selected the suggestion from suggestion list. After selecting suggestion he will be pressing enter key to filter data based on the selected string. 

Something similar to keyCode=13 on press enter event from input field. Is that something i can get it from this library?.

Thanks.

**Comment by moroshko** [comment]
If your Autosuggest is inside a `<form>` you could just add `onSubmit` to the form.
Otherwise, you could add `inputProps.onKeyDown` and check the key code there.

**Comment by rumanhassan** [comment]
Thanks it worked :) . Appreciate your help.
