### ISSUE TITLE
Support React@15.5

### ISSUE THREAD

**Issue by taylor-smith** [moroshko/react-autosuggest#351]
A number of deprecation warnings were added in React 15.5.0. Can react-autosuggest support the new recommended APIs?

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by moroshko** [comment]
Submit a PR?

**Comment by taylor-smith** [comment]
Will do! Thanks

**Comment by moroshko** [comment]
Solved in [v9.0.1](https://github.com/moroshko/react-autosuggest/releases/tag/v9.0.1)
