### ISSUE TITLE
<tr> cannot appear as a child of <li>. See Item > li > td.

### ISSUE THREAD

**Issue by mattdell** [moroshko/react-autosuggest#355]
In my application, when user sees suggestions they should be in a tabular format.

Basically, because each suggestion is tightly bound to being an item in a list, I can't make it so that my header is my `<th>` and my suggestions are `<tr>`. 

Ideal code sample would be like so:
```
export interface IMappingProps {
    from: string;
    label: string;
}

const renderSuggestion = (suggestion: any, mapping: [IMappingProps]) => {
    return (<tr>{mapping.map(map => <td>{suggestion[map.from]}</td>)}</tr>);
};

const renderSuggestionsContainer = ({ containerProps, children }: any, mapping: [IMappingProps]) => {
    console.log('children is', children);
    return (
        <div {...containerProps}>
            <table>
                <tbody>
                    { mapping.map(map => <th>{map.label}</th>) }
                    // don't render ul / li here
                    {children}
                </tbody>
            </table>
        </div>
    );
};
```

**Comment by moroshko** [comment]
> In my application, when user sees suggestions they should be in a tabular format

Why is this important to you to have `<tr>` and `<td>` instead of the default `<ul>` and `<li>`?

I never seen an Autosuggest implemented using a table...

**Comment by mattdell** [comment]
To display tabular suggestions. In my scenario I want to be able to search by an id and show some data about that key as well. Unfortunately I can't be explicit due to the nature of my project, but let's say I want to search for a product based on its name and show a price and category for that product.

If I have suggestions as 
```
[
  {
    name: "television",
    category: "electronics"
    price: 499.99
  },
  {
    name: "telescope",
    category: "electronics"
    price: 299.99
  },
  {
    name: "telephone",
    category: "electronics"
    price: 29.99
  },
]
```

Then I want as I type "tele" in the box I want the following to be displayed in the autosuggest

```
Name            Category             Price
telephone       electronics          29.99
telescope       outdoors             299.99
television      electronics          499.99
```

Most importantly, I want the headings of each column to line up with the items below. I could do this by placing spans in divs and setting their width, but the best solution for tabular data is a table.

**Comment by moroshko** [comment]
I see your point, but not sure how to address it. 
This is the first time that someone asks for tabular suggestions, and I'm concerned about bloating the Autosuggest API to support this use case.

If you have any ideas how to update the API to support your use case, let me know. Some pointers:
[`react-autowhatever`](https://github.com/moroshko/react-autowhatever) is responsible for rendering the suggestions. `<ul>` is rendered [here](https://github.com/moroshko/react-autowhatever/blob/e9419080af2fe2895713fc1082a638f6cdd86c78/src/ItemsList.js#L44) and `<li>` is [here](https://github.com/moroshko/react-autowhatever/blob/e9419080af2fe2895713fc1082a638f6cdd86c78/src/Item.js#L75).

I'm also keen to see tabular Autosuggest examples online. If you know any, could you provide links please?

**Comment by lopis** [comment]
@mattdell I'm sure you can achieve the same layout using any number of css techniques such as grids, flex, floats, table layout. They are probably also more flexible and responsive solutions.

![image](https://cloud.githubusercontent.com/assets/2715751/25740875/ae08261c-3188-11e7-8eb0-fabdaa910bff.png)

**Comment by mattdell** [comment]
That's not tabular, though. I literally want to display the suggestions as table rows like so...

```
| Name       | Category    | Price  |
|------------|-------------|--------|
| Telephone  | Electronics | 29.99  |
| Telescope  | Outdoors    | 299.99 |
| Television | Electronics | 499.99 |
```

And, ideally, keep the table header as you scroll down. I've actually been able to achieve this by removing `{ children }` from `renderSuggestionContainer` and calling `renderSuggestion` directly from there.

This, of course, has other drawbacks but it seems to work for my needs.

**Comment by mattdell** [comment]
I suppose since this isn't an issue and I've been able to get around it, I might as well close this.

Thanks for your help, though, @moroshko. Fortunately I have a simpler autosuggest application elsewhere in my app so I can use this more as you intended.

**Comment by lopis** [comment]
Glad you to around it. I was only showing that you can show the info in whatever shape you want in my example.
