### ISSUE TITLE
problem with theme on a vanilla "create-react-app" project

### ISSUE THREAD

**Issue by diligiant** [moroshko/react-autosuggest#359]
Hi,

I'm a total react newbie so I started with create-react-app. I then did the necessary steps and I therefore have a working Autosuggest.

My problem lies with the them'ing.

I added
```
import theme from './theme.css';
and theme={theme}
```

like in your sample. As it wasn't working, I dug in the debugger and found a noticeable difference in the source code that I can't explain. You might. I'll pray to that ;)

thank you.

Your sample is compiled into
`var _theme = __webpack_require__(316);`

"file" 316 being
`module.exports = {"container": … }`
so at runtime _theme is what you expect, a JS dictionary of the css

my vanilla compiles into
`var _theme = __webpack_require__(/*! ./theme.css -> style-loader */ 289);`
289 being
`var content = __webpack_require__(/*! css-loader */ 290);`
and 290 being 
`exports.push([module.id, ".container {\n  position: … ", ""]);`
so at runtime, _theme is not what you expect.

**Comment by moroshko** [comment]
`create-react-app` doesn't support CSS Modules out of the box.
Try using inline styles, like in [this example](http://codepen.io/moroshko/pen/OpPqxY).

**Comment by diligiant** [comment]
thank you. I'm gonna get rid of this crappy helpers ;)
