### ISSUE TITLE
Automatic scrolling with highlighted

### ISSUE THREAD

**Issue by mads-thines** [moroshko/react-autosuggest#361]
### Hi!
Overall the autosuggest works great, though I have one issue which I don't know if configurable.
When I scroll through the list which wrapper have been given a max-height, I would expect the highlighted (focused) item to stay in the frame and automatic scroll if going below the max-height fold. 

**I've added a gif to illustrate my problem.**

![autosuggest scrolling with highlighted](https://cloud.githubusercontent.com/assets/16097850/25576051/81cde390-2e5c-11e7-99b7-1d226a6639e0.gif)

Is there a setting somewhere I have to set, or a specific way to do the styling? 

Thanks,
**Mads**

**Comment by moroshko** [comment]
Hmm... weird. The scrollbar should move when you press <kbd>Up</kbd>/<kbd>Down</kbd>. See [this example](http://codepen.io/moroshko/pen/XRgbxR?editors=0110).
Could you create a Codepen that demonstrates your issue?

**Comment by mads-thines** [comment]
@moroshko, thanks for getting back!
**I found the problem**.
In the stylesheet, the max-height was on the `<ul>` instead of the `<div>` container which caused the problem.
Now it's working perfect.

– **A new problem occurred though.**
I can see that the highlighter doesn't work for Æ Ø Å (Danish characters) and they doesn't get in a separate span. Do you have any suggestions on how to fix this?

Also, sorry for not adding a codepen, but my component is quite complex with many depending props so it would take a long time for me to set it up. I hope you understand.

**Comment by pxhoang1992** [comment]
i set max-height and overflow-auto in react-autosuggest-list and scrollbar not working when i press up/down key. this is my code?
 .react-autosuggest__suggestions-container {
    display: none;
  }
  .react-autosuggest__suggestions-container--open {
    display: block;
  }
  .react-autosuggest__suggestions-list {
    max-height: 400px;
    overflow-y: auto;
    position: absolute;
    top: ${props => props.top}px;
    width: 500px;
    list-style: none;
    margin-top: 0;
    margin-right: 10px;
    padding-left: 0;
    object-fit: contain;
    box-shadow: 0px 5px 14.7px 1.3px rgba(0, 0, 0, 0.17);
    background-color: #ffffff;
  }
please help me?
Thank,
Hoang

**Comment by sanchezcarlos1986** [comment]
I need to solve a similar issue but when I have multiselect, I need to have separated lists with individual scroll bar but I couldn't reach that behavior yet. If some one can give me hand with that, I'll appreciate it. Thanks

**Comment by JordanDDisch** [comment]
This was a css issue for me that was fixed by moving the `position: absolute; overflow-y: auto; max-height: 250px;` and other custom dropdown styling from the 'ul' class to the results container opened class `react-autosuggest__suggestions-container--open`. 

See this example: https://codepen.io/moroshko/pen/XRgbxR?editors=0110
