### ISSUE TITLE
Using a variable that holds suggestions from parent component 

### ISSUE THREAD

**Issue by autohub7** [moroshko/react-autosuggest#367]
I fetched data from database and stored in Redux. Then, the variable(suggestlist) passed down with props from parent component. Instead of using languages variable from langauges.js, I want to use suggestlist. (I've tested with languages.js, it worked okay. However, I couldn't achieve with suggestlist). How do I make 'suggestlist' available in getSuggestions?
 

![image](https://cloud.githubusercontent.com/assets/10937668/26188938/f6f4a044-3b56-11e7-80d0-2ad25e7ef3c9.png)
![image](https://cloud.githubusercontent.com/assets/10937668/26188946/03a479f4-3b57-11e7-8acb-76c8029467c6.png)

**Comment by moroshko** [comment]
Can't you just replace `languages` with `this.props.suggestlist`?

**Comment by autohub7** [comment]
I added a button to test whether this.props.suggestlist will be available in the same Component. 

It shows okay with
![image](https://cloud.githubusercontent.com/assets/10937668/26214305/c24a5884-3bb0-11e7-97b8-839341a35202.png)
![image](https://cloud.githubusercontent.com/assets/10937668/26214448/4d58a4f8-3bb1-11e7-837b-0ff6d70a9d49.png)





I couldn't get this.props.suggstlist in getSuggestions function. 
![image](https://cloud.githubusercontent.com/assets/10937668/26214471/5cfbec30-3bb1-11e7-8e36-5b868ab112f4.png)

**Comment by autohub7** [comment]
It works now after deleting line 58 and use this.props.suggestlist in getSuggestions. 
Thanks a lot!
