### ISSUE TITLE
[feature request] Various `renderSuggestion` shapes?

### ISSUE THREAD

**Issue by andrewmartin** [moroshko/react-autosuggest#369]
Hi there, love this plugin. Really incredible stuff, impressed with the flexibility. 

Sorry if I missed this somewhere, I scanned the docs and couldn't find anything relevant; I may chip in a PR, but I wanted to ask first. I have a pretty unique situation where I am using `multiSection` to render out a few groups.

The issue I'm running into is that `renderSuggestion` only accepts the `suggestion` itself, and I have a different object shape for the various groups of suggestions I have.

So, I'm doing some hacky stuff (basically, checking for keys that are unique to each suggestion group) and it's getting there, but I thinking maybe it makes sense to send the `section` object itself (or, just the section title, even) to the `renderSuggestion` function so it's accessible there.

A quick snippet of what I'm trying to do:

```
const OrgItem = org => <span>{org.address}</span>;

const UserItem = user => <span>{user.first_name}</span>;

const StoryItem = story => <span>{story.first_name}</span>;

const SuggestionItem = (item) => {
  if (item.address) {
    return <OrgItem {...item} />;
  }
  if (item.first_name) {
    return <UserItem {...item} />;
  }
  return (
    <StoryItem {...item} />
  );
};
...
```

I can provide more context if I'm not being clear.

**Comment by moroshko** [comment]
I see your point.

Even if we pass the section title or the section itself to `renderSuggestion`, you'll still have to query them to decide what to render. It doesn't feel much better IMHO.

I suggest you add a key like `type` to your suggestions, and render based on it, e.g.:

```js
const suggestions = [
  {
    title: 'Users',
    suggestions: [
      {
        type: 'user',
        first_name: 'Usain',
        last_name: 'Bolt'
      },
      ...
    ]
  },
  {
    title: 'Orgs',
    suggestions: [
      {
        type: 'org',
        name: 'Facebook'
      },
      ...
    ]
  }
];
```

**Comment by andrewmartin** [comment]
Ahh, this is a much safer solution. Didn't consider that. 

It's a small edge case, anyways. This thing works beautifully. Thanks!
