### ISSUE TITLE
Only Fetch Suggestions After Typing (not on Focus) 

### ISSUE THREAD

**Issue by BigPrimeNumbers** [moroshko/react-autosuggest#374]
Previously, `autosuggest` supported only fetching suggestions when certain reasons (methods of input) were used (when `onSuggestionFetchRequested` was named `onSuggestionsUpdateRequested`), e.g.

```
onSuggestionsUpdateRequested({ value, reason }) {
        if(reason === 'type'){
                this.debouncedLoadSuggestions(value)
        }
    }
```

but now I see no way to do this, e.g.

```
onSuggestionsFetchRequested({ value }) {
        // if(reason === 'type'){
        this.debouncedLoadSuggestions(value)
        // }
    }
```
Can I still accomplish this behavior somehow? I'm trying to minimize network requests, but want users to be able to tab through fields.

**Comment by SumeshDubey** [comment]
Even I'm facing the same issue where I don't want to fetch suggestions when a user focuses on input. Please let us know how we can stop this from happen

**Comment by jchapelle** [comment]
+1

**Comment by SumeshDubey** [comment]
Found a temporary solution, works for my application where I have commented some part in the library itself and it worked for me. If you guys want to try it out please comment  following line in below page :
 
**node_modules/react-autosuggest/dist/Autosuggest.js and comment line no. 329**

Please refer the below code :
var autowhateverInputProps = _extends({}, inputProps, {
        onFocus: function onFocus(event) {
          if (!_this2.justSelectedSuggestion && !_this2.justClickedOnSuggestionsContainer) {
            var shouldRender = shouldRenderSuggestions(value);

            _this2.inputFocused(shouldRender);
            _onFocus && _onFocus(event);

            if (shouldRender) {
              onSuggestionsFetchRequested({ value: value }); // This part needs to be commented
            }
          }
        },

This will be a temporary solution for me. I'm eagerly waiting for an option to fix this issue.

**Comment by moroshko** [comment]
https://github.com/moroshko/react-autosuggest/issues/382 should solve this.

**Comment by SumeshDubey** [comment]
How is it going to solve the issue? You have added a reason string with a reason input-focused. This should be user configured in there components itself. Or if I'm doing something wrong please let me know how to use it?

**Comment by moroshko** [comment]
@SumeshDubey Here is how you could avoid fetching suggestions when input is focused:

```js
onSuggestionsFetchRequested = ({ value, reason }) => {
  if (reason === 'input-focused') {
    return;
  }

  // fetch suggestions for `value`
};
```

**Comment by SumeshDubey** [comment]
It worked. Thanks a lot.

**Comment by vrover** [comment]
I also dont't want to fetch suggestion when input is blurred. Can anyone please tell me how to do that?
