### ISSUE TITLE
onChange: method never picks up on user pressing 'enter'

### ISSUE THREAD

**Issue by cindyzwang** [moroshko/react-autosuggest#375]
[Codepen](https://codepen.io/cindyzwang/pen/bWXEyM?editors=0011)

The docs state that onChange receives `method`, a string that has a possible value of 'enter'. It never gets set to enter and it also only gets set to 'escape' if you press it twice. I worked around not getting 'enter' by wrapping the Autosuggest component in a form but either the docs should be updated or this is a bug.

Thanks

**Comment by moroshko** [comment]
It's not a bug, and I agree that the docs can be improved to clarify things (PR is welcome!).

`onChange` is called **only when the input value changes**.

> It never gets set to enter

When you press <kbd>Enter</kbd>, `onChange` is not called at all! The only case I can think of when the input value changes after pressing <kbd>Enter</kbd> is when you hover on a suggestion and then press <kbd>Enter</kbd>. Try that, and you should see `method: 'enter'`.

> it also only gets set to 'escape' if you press it twice

Same here. After pressing <kbd>Esc</kbd> once, suggestions are closed, **but the input value stays the same**. `onChange` is not called at all. When you press <kbd>Esc</kbd> the second time, the input value is changed to empty string, and therefore `onChange` is called with `method: 'escape'`.

Does this make sense?
