### ISSUE TITLE
onClick handler

### ISSUE THREAD

**Issue by blake41** [moroshko/react-autosuggest#376]
Hi, 

This is somewhere between a feature request and a bug report.  First off, love this library.
What I'd like to do is show "recent searches" when you click into the input box but before you start typing.  None of the provided hooks allow me to do this, and for some reason I can't attach an onClick handler.  My onClick handler doesn't fire no matter what I do.  I tried wrapping the autosuggest element in a div and attaching my handler there, which works, but I need access to the state so the behavior can run only when the value of the autosuggest component is == ''.  I might be missing an obvious way to handle this but I can't think of something.

https://codepen.io/moroshko/pen/LGNJMy

**Comment by adack123** [comment]
Hey,

This should be doable without using your own onClick handler. If you only care about rendering when the input element is focused you could do something along these lines.

```javascript
const getSuggestions = value => {
  const inputValue = value.trim().toLowerCase();
  const inputLength = inputValue.length;

  return inputLength === 0 ? yourSliceOfRecentSearchesState : languages.filter(lang =>
    lang.name.toLowerCase().slice(0, inputLength) === inputValue
  );
};
```

```javascript
function shouldRenderSuggestion(value) {
   return value.length >= 0;
}
```

Granted, this is assuming that `yourSliceOfRecentSearchesState` has the same shape as `languages` because of `renderSuggestion`. Let me know how it goes!

**Comment by blake41** [comment]
Thanks so much for this suggestion.  There were a bunch of things I was misunderstanding about the library.  Most important of which being the (well documented, i later realized) functionality of shouldRenderSuggestion being the reason that getSuggestions doesn't fire on an empty input.  So totally my fault for not fully understanding the hooks you had provided.  I ended up doing something similar to this, but this is even cleaner!

**Comment by adack123** [comment]
Sweet, glad it works! 😀

**Comment by moroshko** [comment]
What @adack123 suggested [above](https://github.com/moroshko/react-autosuggest/issues/376#issuecomment-306874078) is the way to go.
