### ISSUE TITLE
Access highlighted suggestion from renderSuggestion 

### ISSUE THREAD

**Issue by mkaemmerer** [moroshko/react-autosuggest#383]
In my application, I use css-modules for styling. I also want to style highlighted suggestions differently from non-highlighted suggestions.

Unfortunately, I can't do this without breaking encapsulation, because the highlight class `react-autosuggest__suggestion--highlighted` is applied to a list item within `<Autosuggest>`, not to my `<Suggestion>` component.

I propose passing either `highlightedSuggestion`, or an `isHighlighted` flag to`renderSuggestion` as an additional argument. This way my `<Suggestion>` component would be able to style itself based on whether or not it was highlighted.

**Comment by mkaemmerer** [comment]
Another possible solution would be to allow users of react-autowhatever and react-autosuggest pass in an `onHighlightedItemChange` property. This way, the parent component could maintain its own state for `highlightedSuggestion`, and use this state within `renderSuggestion`.

**Comment by moroshko** [comment]
I like the idea of adding `isHighlighted` to `renderSuggestion`, so the signature becomes:

```js
function renderSuggestion(suggestion, { isHighlighted, query })
```

Would you like to submit a PR?

**Comment by mkaemmerer** [comment]
Yes, sounds good to me. I'll put together a PR soon.
