### ISSUE TITLE
Callback for when a suggestion is selected?

### ISSUE THREAD

**Issue by nthtran** [moroshko/react-autosuggest#4]
There should be a way to detect when a suggestion is selected. I was expecting some kind of `onChange` or `onSelected` handler.

**Comment by moroshko** [comment]
@nthtran We currently discuss the `onChange` option in [this Pull Request](https://github.com/moroshko/react-autosuggest/pull/3). You are welcome to contribute!

Also, could you please describe your use case for `onChange` or `onSelected` so we better understand what exactly you need?

**Comment by nthtran** [comment]
I mainly need `onSelected` for now. Currently I'm trying to use `react-autosuggest` for location suggestions. Upon selecting a suggestion (either via keyboard or mouse click) I want to be able to move the map to that location immediately. For this to work `onSelected` should be called with the selection string/object.

Also I can see myself using `onChange` and `onBlur` for validating or saving as you type.

**Comment by moroshko** [comment]
@nthtran Thanks for your feedback. I agree that it makes sense to add an `onSelected` option. 

Assuming [we add](https://github.com/moroshko/react-autosuggest/pull/3#issuecomment-92046212):

    inputAttributes {
      onChange: ...
      onBlur: ...
      onKeyDown: ...
    }

how would you feel about having `onSuggestionSelected` on the `<Autosuggest />` itself rather than having it inside `inputAttributes`?

**Comment by nthtran** [comment]
:+1: definitely makes more sense to have `onSuggestionSelected` on `<Autosuggest />` itself rather than `inputAttributes`!

**Comment by moroshko** [comment]
@nthtran Great! I'll add the `onSuggestionSelected` in the next day or two. Watch this space.

**Comment by moroshko** [comment]
`onSuggestionSelected` is available in version 1.9.0
