### ISSUE TITLE
Different Themes Applied to Individual Instances on Same Page

### ISSUE THREAD

**Issue by BigPrimeNumbers** [moroshko/react-autosuggest#401]
I'd like to pass different themes to individual instances of `autosuggest` on the same page (rendered from a single file). At the moment, it seems that the theme that is passed to the last instance of `autosuggest` gets applied to all instances declared in the file. 

Is there a way to accomplish multiple themes being applied on the same page? Perhaps some sort of component container factory?

**Comment by moroshko** [comment]
> it seems that the theme that is passed to the last instance of `autosuggest` gets applied to all instances declared in the file.

I can't see why would this happen.

Could you create a Codepen that demonstrates the issue?

**Comment by BigPrimeNumbers** [comment]
My mistake. I accidentally was modifying the theme object in my code in place, and didn't realize it. The component does support multiple themes on the same page, and is working as expected. Sorry about the false alarm!

**Comment by BigPrimeNumbers** [comment]
That said, another quick incidental question: Is it possible to pass in theming to descendants of `autosuggest`? I'm using [`autosuggest-highlight`](https://github.com/moroshko/autosuggest-highlight) to emphasize the characters that match in a suggestion, but have found the only way to customize style is to do so globally, or at the element definition level. I'd like to allow passing in a custom theme to `autosuggest` and have it applied to its descendants (i.e. the `autosuggest-highlight` element).

**Comment by moroshko** [comment]
Since you have full control over `renderSuggestion()` I'm not sure how would passing the theme down to the descendants work.

I'd just style it globally like in [this Codepen](https://codepen.io/moroshko/pen/GEPoQW).
