### ISSUE TITLE
Provide an option to not focus on field on clear

### ISSUE THREAD

**Issue by kosanna** [moroshko/react-autosuggest#405]
## Are you reporting a bug?
Not sure bug or feature.

* Provide the steps to reproduce the issue, e.g.:
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear
  3. Select any suggestion
  4. Click somewhere else so field looses focus
  5. Click clear on the field 

  **Observed behaviour:** Input field is focusing and thus invoking onFocus function

  **Expected behaviour:** Just clear the field, not focus. Could be just an opt-out prop in the component.

**Comment by mrmojica** [comment]
I'm trying to get the same expected behavior that @kosanna mentioned.  Any suggestions?

**Comment by kosanna** [comment]
@mrmojica turned out to be a problem on our end, so I'll close the issue. If your case is different please reopen and provide details.

We are calling `event.preventDefault() ` and focusing back on clearing intentionally.
https://developer.mozilla.org/en/docs/Web/API/HTMLElement/focus#Notes
