### ISSUE TITLE
Clicking outside does not emulate native behaviour of dropdowns

### ISSUE THREAD

**Issue by kosanna** [moroshko/react-autosuggest#408]
## Are you reporting a bug?
Yes

* Provide the steps to reproduce the issue, e.g.:
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear
  3. While suggestions are shown click (or hover) on some link on the page

  **Observed behaviour:** You are navigated to the respective page link (can hover the link)

  **Expected behaviour:** Suggestions should be closed, navigation should not happen (can't hover the link)

Perhaps, it should be a component's prop to opt-in/opt-out of that, but it feels like the default behaviour should be emulating the native one.

**Comment by moroshko** [comment]
> it feels like the default behaviour should be emulating the native one.

What's the reason for that? 
Could you provide a pointer to accessibility guidelines that suggest that this is the recommended behavior for autosuggest components?

Out of interest, I checked the autosuggests on google.com, facebook.com, and bing.com, and they all allow you to navigate to other links on the page.

[react-autocomplete](https://github.com/reactjs/react-autocomplete) and [react-select](https://github.com/JedWatson/react-select) components also behave similarly.

**Comment by kosanna** [comment]
Checkout any dropdown for example even on github. 
![screen shot 2017-07-26 at 5 25 46 pm](https://user-images.githubusercontent.com/15971854/28609336-9d92e706-7227-11e7-8b80-9cbfe6746a02.png)

First action clicks it away, and only on the second you can press anything. That's because you want people to easily close dropdown not forcing them to try and find an empty space on the screen (which plus might be visually empty, but there might be some other element there)

**Comment by moroshko** [comment]
I agree that this behavior is the norm for dropdowns, but not convinced this should be the case for autosuggests (where input field exists).

Can you find any **autosuggest** examples online that implement this behavior?

**Comment by kosanna** [comment]
Closing as agreed with Misha.

For those who wants a workaround here's a rough idea how you can do that

```
      <div>
        <ReactAutosuggest/>
        <div className={styles.autosuggestBackdrop}/>
      </div>
```

and style it as a sibling
```
.containerOpen + .autosuggestBackdrop
```
