### ISSUE TITLE
How may I mask the search bar underline ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [moroshko/react-autosuggest#413]
Hello, folks, 
Juste on simple question as title, I wonder whether I could mask the search bar underline by theme props ? 

Thx a lot.

**Comment by moroshko** [comment]
What do mean by "search bar underline"?

**Comment by be-next-hotdog** [comment]
I meant the underline beneath the input field.

**Comment by moroshko** [comment]
Could you share a screenshot?

**Comment by be-next-hotdog** [comment]
Sorry guy, I made a mistake, we used auto suggestion via material ui and in fact we should have configured their TextField ahead. So problem resolved. 

I closed this issue, thx all the same :) :)
