### ISSUE TITLE
SelectField fails on zero-labeled option

### ISSUE THREAD

**Issue by thetevikrant** [moroshko/react-autosuggest#415]
Hi, Thanks for the awesome library.

Found issue similar to [#214](https://github.com/mlaursen/react-md/issues/214). Instead of value, set the label to 0, selectField fails.

**Comment by moroshko** [comment]
Does this issue belong to `react-autosuggest`?

**Comment by thetevikrant** [comment]
Sorry wrongly created, btw great library (now react-autosuggest). :wink:
