### ISSUE TITLE
Access React context within renderSuggestionsContainer

### ISSUE THREAD

**Issue by goldmandrummer** [moroshko/react-autosuggest#416]
In my application, when the user is typing input and there is no matching suggestion in the data set, I would like to let them add a new item to the set. In my particular case, the data set is within the React component's `this.props` and thus to add items to the data I must use methods in the context of my React component. I am attempting to use `renderSuggestionsContainer` to add this extended functionality and would need to access the React component context within that function.

I can imagine two possibilities for achieving this: 
* directly using my React component context via `this.someReactComponentMethod()`
* utilizing arbitrary props on the `inputProps` to pass in the method (or component context`this`)

I have created a simplified example to demonstrate what I have in mind:
```
class App extends React.Component {
  // ... constructor ... //
  
  //** Method to access **//
  someReactComponentMethod() {
    return 0;
  }

  //** Attempting access **//
  renderSuggestionsContainer({ containerProps , children, query })   {
  
    // My direct need is accessing a method of App
    var accessAppContext = this.someReactComponentMethod();

    // An alternative could be arbitrary inputProps
    var accessArbitraryInputProps = this.inputProps.arbitrary;
  
    return (<div {... containerProps}>{children}</div>);
  }
  
  // ... onChange, onSuggestionsFetchRequested, onSuggestionsClearRequested ... // 

  render() {
    const { value, suggestions } = this.state;
    const inputProps = {
      placeholder: "Type 'c'",
      value,
      onChange: this.onChange,
      //** Example arbitrary prop to access **//
      arbitrary: "exampleValue"
    };

    return (
      <Autosuggest 
        suggestions={suggestions}
        onSuggestionsFetchRequested={this.onSuggestionsFetchRequested}
        onSuggestionsClearRequested={this.onSuggestionsClearRequested}
        getSuggestionValue={getSuggestionValue}
        renderSuggestion={renderSuggestion}
        renderSuggestionsContainer={this.renderSuggestionsContainer}
        inputProps={inputProps} />
    );
  }
}
```

Full code example on CodePen:  https://codepen.io/anon/pen/brVWea

I have found that within `renderSuggestionsContainer` the `this` keyword evaluates to the Window object, the `containerProps` holds nothing useful to me, and `inputProps` are not available. 

Perhaps there is a much simpler way of achieving the functionality I mentioned? I must admit I am new to React so there may be some solution I am unaware of.

**Comment by moroshko** [comment]
All you need is to bind `renderSuggestionsContainer`'s `this` to `App`'s instance:

```js
//                                                                  +---- magic
//                                                                  |
//                                                                  v
renderSuggestionsContainer = ({ containerProps , children, query }) => {
  // `this` is what you need here
};
```

[Codepen](https://codepen.io/moroshko/pen/qXOVQo?editors=0010)

Alternatively:
```js
class App extends React.Component {
  constructor() {
    super();
    this.renderSuggestionsContainer = this.renderSuggestionsContainer.bind(this); // magic
  }

  renderSuggestionsContainer({ containerProps , children, query }) {
    // `this` is what you need here
  }
}
```

**Comment by goldmandrummer** [comment]
Oh, I see. Thank you so much!
