### ISSUE TITLE
Props to disable autosuggest field

### ISSUE THREAD

**Issue by jerrylow** [moroshko/react-autosuggest#420]
## Feature Request

Have autosuggest take in a disabled prop (boolean) to disable the autosuggest field. This is useful for situations maybe when the field is pending other parts of the form to be completed or maybe just disabled for certain users.

**Comment by d-a-n** [comment]
Isn't this already supported?

```
const inputProps = {
    placeholder: 'Type a programming language',
    value,
    onChange: this.onChange,
    disabled: true
};
```

**Comment by gor181** [comment]
I can confirm that it's possible to pass the `inputProps.disabled` which achieves the result.

**Comment by AndyOGo** [comment]
hmh, it doesn't seem to be documented thought 🤔
