### ISSUE TITLE
Read only

### ISSUE THREAD

**Issue by gor181** [moroshko/react-autosuggest#422]
* Please describe your use case from user journey point of view, e.g.:

  > In our application in some cases we want to display the auto suggest list as read only. Which would mean that users shouldn't be able to delete or to search for new values. They should only be able to view the list of passed `suggestions`. Currently we are hacking this by passing `inputProps.disabled` however that still results in "Add" button to be visible to the user thus it's confusing.

* If you have ideas how to extend the Autosuggest API to support your new feature, please share!
> Add a `readOnly` property.

---
**EDIT**

If you feel that this feature could be taken in consideration I could spend some time creating a PR.

**Comment by moroshko** [comment]
Sorry, I don't quite understand what are you trying to achieve.
Do you want the input to be disabled, but at the same time to see the suggestions?
Also, what is the "Add" button you are referring to?
Could you share some screenshots to explain better the use case?

**Comment by gor181** [comment]
hey @moroshko,

Please ignore this one, closing as the issue  was internal :smiley:
