### ISSUE TITLE
Lost onSuggestionSelected by mouse click if the action changes page structure 

### ISSUE THREAD

**Issue by ghiaia** [moroshko/react-autosuggest#425]
## Description.
I have in the following order: 
 * an INPUT, 
 * a DIV,
 * an Autosuggest 

The Autosuggest is always showing an initial suggestions set (alwaysRenderSuggestions={true})
The INPUT onBlur close ("nullify") the DIV.

__See the [Codepen](https://codepen.io/ghiaia/pen/OjQYBL)__

## Steps:
  1. Focus on the first input field
  2. Click on a suggestion on the Autosuggest
  3. Look at Autosuggest: it does not receive the selected suggestion, while the intermediate DIV is gone.

Yes. The DOM tree is changed.

  **Expected behaviour:** The selected suggestion should be in Autosuggest input (and state.value)

## Use case

In my real application the first input and div group is an Autosuggest. The second Autosuggest changes its initial suggestions array depending on value from the first (via redux).
So, when I select the required value in the first Autosuggest the second show a new default suggestions set (input value===""), ready to be clicked.
If the user clicks on the second suggestions set, then the first blur closing its suggestions container.

Thanks!

**Comment by louh** [comment]
I might have a related issue.

If you have a `onSuggestionSelected()` method that logs the details of the selection, like so:

```js
onSuggestionSelected = (event, { method }) => {
    console.log(method)
}
```

Do you find that the `click` method is never logged, but the `enter` method will be?

**Comment by ghiaia** [comment]
I don't view any reaction from the method. 
Yes. I found the issue via logs (in a complex component wrapping Autosuggest).
 
I can not use enter because focus is on other input. 
The codepen is a super simplification/generalization based on the "Basic" example:
what happen if DOM change after click on a suggestion in an not focused Autosuggest ?

**Comment by OllieJennings** [comment]
I too am experiencing this now!

**Comment by ghiaia** [comment]
@OllieJennings  Without alwaysRenderSuggestions={true} I can not get an alway open suggestions list to click (when focus is in the first input field. See codepen). 

How do you get an open suggestions list when focus is out of the autosuggest input field ?

**Comment by ghiaia** [comment]
Adding console.log() to Autosuggest.js I observe:

* onDocumentMouseDown respond selecting the right suggestion DOM element.

* No activation of "React synthetic event" onClick. (bound to this.onSuggestionClick)

Maybe a React problem (or expected behaviour due to dom change "on the run") ?

**Comment by OllieJennings** [comment]
@ghiaia I cannot get this to work as well

**Comment by ghiaia** [comment]
Simple React page (without Autosuggest) show the same behaviour.

It is a "problem" (or my misunderstatement) about React. 

## see [Codepen](https://codepen.io/ghiaia/pen/XaqZBj)

**Comment by ghiaia** [comment]
@moroshko 

Looking around I found: https://stackoverflow.com/questions/35784671/why-does-a-react-components-onclick-event-handler-not-fire-when-the-display-a

> A click event is one mousedown followed by one mouseup, without leaving or changing the element.
>
>If the element moves before the mouseup, or you put something over the button before the mouseup, or the mouse moves before the mouseup, or you manually reset input.focus() before the mouseup, or...
>
>...anything else...
>
>Then there's no click.

Any idea ?

Tnx!

**Comment by OllieJennings** [comment]
I assume this is a bug that won't be fixed, if so surely the ReadMe should state this side-affect

**Comment by ghiaia** [comment]
This is not a react-autosuggest bug.
Read my previous comments and codepen.
