### ISSUE TITLE
[Bug] Suggestions not rendered when using onFocus for input in renderInputComponent

### ISSUE THREAD

**Issue by prajapati-parth** [moroshko/react-autosuggest#432]
## Are you reporting a bug?
Yes
* Please create a Codepen that demonstrates your issue. You can start from the [Basic example]
[CodePen link](https://codepen.io/daParth17/pen/NvorKd)

* Steps to reproduce the issue
  1. Focus on the input field
  2. Type `c`, and wait for suggestions to appear

  **Observed behaviour:** Suggestions does not open

  **Expected behaviour:** Suggestions should open

If you go ahead and remove the `onFocus` prop from the input(line 88) it would work as expected.

Thanks.

**Comment by prajapati-parth** [comment]
@moroshko Gentle reminder. Did you get a chance to look into this issue?

**Comment by lmuntaner** [comment]
I had a similar problem. I'd like to know whether you are going to address this issue or there is no plan on it.

**Comment by apandichi** [comment]
The bad news is: the same problem happens with onChange instead of onFocus.
The good news is: there is a workaround.

```
function renderInputComponent(inputProps) {
  return <input {...inputProps} onFocus={(ev, val) => {
      handleInputFocus();
      inputProps.onFocus(ev, val);
    }
   }/>
}
```

**Comment by prajapati-parth** [comment]
Closing this out as no response received from maintainers.

**Comment by JStrebeyko** [comment]
@apandichi the workaround works on my end - thanks a ton! :)
