### ISSUE TITLE
Display suggestions on click of a button overlaid on input box

### ISSUE THREAD

**Issue by rnagavel** [moroshko/react-autosuggest#440]
Hi,
We have a requirement to display suggestions on click of a button that is placed in input box (like a dropdown). What is the best way to achieve this?

**Comment by moroshko** [comment]
You could just set the `suggestions` prop when the button is clicked. Suggestions will be shown.

**Comment by aciuffreda** [comment]
Hi,
I am trying to do something similar by calling the onFocus() in the inputProps, but somehow when the autosuggest component is focused, it doesn't open. If I replace onFocus() with onClick(), it works fine however.

```
inputProps={{
          placeholder: this.props.placeholder,
          value: this.state.value,
          onChange: this.handleChange,
          onKeyDown: this.handleKeyPress,
          onFocus: () => this.props.openOnFocus &&
            this.setState({
              suggestions: this.getSuggestions((this.props.suggestionList[0].label.charAt(0))),
            }),
        }}
```

**Comment by neuhausneuhaus** [comment]
@moroshko Can you give an example of how that would look?

**Comment by moroshko** [comment]
@neuhausneuhaus You could do something like this: [Codepen](https://codepen.io/moroshko/pen/zROEPQ?editors=0110)
