### ISSUE TITLE
Passing custom props down to the final html input

### ISSUE THREAD

**Issue by KeithWoods** [moroshko/react-autosuggest#447]
If I declare a custom prop (for example a prop to support automation, `data-automation-some-id`) on an `Autosuggest` component I'm not seeing it as an attribute on the final HTML input box. 

## Are you reporting a bug? - Yes

* Please create a Codepen that demonstrates your issue.  
https://codepen.io/KeithWoods/pen/WZRXqm

* Provide the steps to reproduce the issue:
1. add a `data-automation-id='someid'` prop to an `Autosuggest` component

  **Observed behaviour:** `data-automation-id` attribute not rendered on the `Autosuggest`'s HTML input element 

  **Expected behaviour:** `data-automation-id` attribute should be rendered on the `Autosuggest`'s HTML input element 

I'm happy to do the work, just wanted to see if it's a known issue. I expect the fix is to simply add a `...rest` [here](https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L458) and pass it down when the component is rendered (i.e. `<Autowhatever   {...rest} />`). Might be some follow on work in  Autowhatever.

**Comment by moroshko** [comment]
If you want `data-automation-id` to be on the input element, you need to pass it to `inputProps`. [Example](https://codepen.io/moroshko/pen/OxWvOQ?editors=1010)

**Comment by KeithWoods** [comment]
Great thanks, will close this.
