### ISSUE TITLE
[Bug] Suggestion box get hidden by stepper

### ISSUE THREAD

**Issue by riwu** [moroshko/react-autosuggest#448]
https://codesandbox.io/s/mjy74qv98

The suggestion box gets hidden by stepper. Any way to fix this?

**Comment by blackdynamo** [comment]
@riwu I am not 100% sure, but I am assuming it has something to do with the overflow CSS properties applied by the stepper. The div elements that contain the autosuggest are clipping the contents because the clipper goes beyond the height of the container.

**Comment by riwu** [comment]
Yes i supposed this is material-ui v0.19 stepper's problem. In v1 it's replaced by mobile stepper which has very different UI.
