### ISSUE TITLE
highlightFirstSuggestion = true, Jumps on Keyboard DOWN to the second result

### ISSUE THREAD

**Issue by vkampouris** [moroshko/react-autosuggest#449]
Is there a way to have highlightFirstSuggestion true, but on key board arrow Down get to the first result again?

If there was a way that onChange to manipulate the index or at least check the index, that i believe could potentially solve the problem.

Thanks in advance,
VK

**Comment by moroshko** [comment]
Why would you want to do that?

**Comment by vkampouris** [comment]
Because I now by experience, that some users either will press enter to their search box, or press down on keyboard to go to the first result and iterate the results slowly. There is other reason other than user experience.

**Comment by vkampouris** [comment]
I found out that my problem actually Is that my first result is not properly hightlighted at the dropdown. Maybe a CSS issue?  I also use match from 'autosuggest-highlight/match'; parse from 'autosuggest-highlight/parse'; . Thanks for the great work.
