### ISSUE TITLE
Show suggestions on focus (even if input value is empty)

### ISSUE THREAD

**Issue by gl0gl0** [moroshko/react-autosuggest#450]
Is there a way to show a suggestions list onFocus, even if the input value is empty? It shows them only after entering at least a letter.

I tried using the _shouldRenderSuggestions_ method, but won't work either.

I was wondering if this is supported or not.

Thanks!

**Comment by moroshko** [comment]
See this example: https://codepen.io/moroshko/pen/kXpapq
