### ISSUE TITLE
Multi Section, Title repeating for each result

### ISSUE THREAD

**Issue by vkampouris** [moroshko/react-autosuggest#452]
I am trying to use fetch with Multisection but it seems that i fail to make it work. I made it work with single and it works like a charm (fantastic work you guys) But I am not sure on what i miss with the multisection. Thanks in advance. VK
```
import * as React from 'react';
import 'isomorphic-fetch';
import * as Const from '../Const';
import Autosuggest from 'react-autosuggest';
import { CustMaster } from '../interfaces/Merchant';
import match from 'autosuggest-highlight/match';
import parse from 'autosuggest-highlight/parse';

interface Results {
    title: string;
    results: CustMaster[];
}

interface MerchantDataState {
    suggestions: Results[];
    loading: boolean;    
}
/*
function getMatchingLanguages(value) {
    const escapedValue = escapeRegexCharacters(value.trim());

    if (escapedValue === '') {
        return [];
    }

    const regex = new RegExp('^' + escapedValue, 'i');

    return languages.filter(language => regex.test(language.name));
}
*/

// https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expression
// s#Using_Special_Characters
function escapeRegexCharacters(str: string): string {
    return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function getSuggestionValue(suggestion) {
    return suggestion.companyName;
}

/*function renderSuggestion(suggestion) {
    return (
        <span>{suggestion.companyName}</span>
    );
}*/

function renderSectionTitle(section: Results) {
    return (
        <strong>{section.title}</strong>
    );
}

function getSectionSuggestions(section: Results) {
    return section.results;
}

function renderSuggestion(suggestion: CustMaster, { query }) {
    const matches = match(suggestion.companyName, query);
    const parts = parse(suggestion.companyName, matches);
    return (
        <span>
            {parts.map((part, index) => {
                const className = part.highlight ? 'react-autosuggest__suggestion-match' : null;

                return (
                    <span className={className} key={index}>
                        {part.text}
                    </span>
                );
            })}
        </span>
    );
}

function onSuggestionSelected(event, { suggestion, suggestionValue, suggestionIndex, sectionIndex, method })
{
    alert('CompanyName :'+suggestion.companyName + ' CustID : '+suggestion.custID)
}

export class SearchBox extends React.Component<any, any> {

    constructor() {
        super();

        this.state = {
            value: '',
            suggestions: [],
            isLoading: false
        };

        // this.lastRequestId = null;
    }


    loadSuggestions(value) {
        // Cancel the previous request       

        /*this.setState({
            isLoading: true
        });*/

        fetch('/api/Merchant/GetSearchMerchantsTest?prefix=' + value, { method: 'GET', headers: { 'Authorization': Const.Key } })
            .then(response => response.json() as Promise<Results[]>)
            .then(data => {
                this.setState({ suggestions: data, loading: false });
            });
    }

    onChange = (event, { newValue, method }) => {        
        this.setState({
            value: newValue
        });
    };

    onSuggestionsFetchRequested = ({ value }) => {
        this.loadSuggestions(value);
    };

    onSuggestionsClearRequested = () => {
        this.setState({
            suggestions: []
        });
    };
    
    render() {
        const { value, suggestions, isLoading } = this.state;
        const inputProps = {
            placeholder: "Search...",
            value,
            onChange: this.onChange
        };
        //const status = (isLoading ? 'Loading...' : 'Type to load suggestions');

        {/*const theme = {
            input: 'react-autosuggest__input',
            container: 'react-autosuggest__container',
            suggestionFocused: 'active',
            suggestionFirst: ''
        };*/}

        return (
            <div>
                
                <Autosuggest
                    suggestions={suggestions}
                    highlightFirstSuggestion={true}
                    onSuggestionSelected={onSuggestionSelected}
                    onSuggestionsFetchRequested={this.onSuggestionsFetchRequested}
                    onSuggestionsClearRequested={this.onSuggestionsClearRequested}
                    getSuggestionValue={getSuggestionValue}
                    renderSuggestion={renderSuggestion}
                    inputProps={inputProps}
                    renderSectionTitle={renderSectionTitle}
                    multiSection={true}
                    getSectionSuggestions={getSectionSuggestions}
                />
            </div>
        );
    }
}

```

**Comment by moroshko** [comment]
What exactly is not working?
Could you create a Codepen that demonstrates the issue?

**Comment by vkampouris** [comment]
Thanks for your prompt reply.Sorry for the delay it took me some time but i figured out a mistake on my code with the API now with the same above code it repeats the section. So for every result it will put the same section title. For this `[
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 12310,
        "companyName": "Beddinginn.com",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  },
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 11018,
        "companyName": "BeddingStyle",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  },
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 11878,
        "companyName": "Bedford Fair",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  },
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 10091,
        "companyName": "BedHead Pajamas",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  },
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 12322,
        "companyName": "Drommabed",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  },
  {
    "title": "Merchants",
    "results": [
      {
        "priorityID": null,
        "userID": null,
        "custID": 11014,
        "companyName": "VisionBedding",
        "displayUrl": null,
        "folderUrl": null,
        "businessType": null,
        "firstName": null,
        "lastName": null,
        "address1": null,
        "address2": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "phone": null,
        "fax": null,
        "email": null,
        "website": null,
        "storeLocator": null,
        "couponExpire": null,
        "autoRenew": null,
        "acceptsEmail": false,
        "acceptsPrint": false,
        "acceptsSMS": false,
        "specialty": null,
        "description": null,
        "salesRep": null,
        "recentUpdate": null,
        "prodCat": null,
        "primarySource": null,
        "secondarySource": null,
        "ogTitle": null,
        "ogDescription": null,
        "createdDate": "0001-01-01T00:00:00",
        "createdBy": null,
        "modifiedDate": null,
        "modifiedBy": null,
        "merchantID": null,
        "networkID": null,
        "merchantIDPS": null,
        "merchantIDRS": null,
        "account_ManagerID": null,
        "createdByUser": 0,
        "modifiedByUser": 0
      }
    ]
  }
]` it will return correctly the results but with each of it having the title Merchants on them. This is my main problem now. The code above is the same

**Comment by vkampouris** [comment]
Sorry I couldnt make a proper example in Codepen for the problem i have (I am pretty new to ReactJS) and I had some problems with the exports in Codepen. Sorry, But i assume i have a mistake here `function renderSectionTitle(section: Results) {
    return (
        <strong>{section.title}</strong>
    );
}

function getSectionSuggestions(section: Results) {
    return section.results;
}`

**Comment by vkampouris** [comment]
Found the issue. It was my fault thanks. :) The result must come back already sieved. Thanks in advance
