### ISSUE TITLE
Dismiss auto suggest

### ISSUE THREAD

**Issue by joevo2** [moroshko/react-autosuggest#459]
Sorry but how do i dismiss the auto suggest's suggestion list? It is not listed in the API docs

**Comment by joevo2** [comment]
I tried to implement `document.getElementById("custom-autosuggest-input").blur()` doesn't seems to work as well... is it because the input has been modified? doesnt accept normal blur command? doing `document.getElementById("custom-autosuggest-input").value = 'something'` seems fine though.

**Comment by moroshko** [comment]
What's your use case?

**Comment by joevo2** [comment]
@moroshko i just want to dismiss the dropdown with the press of a button 
![screen shot 2017-10-24 at 11 42 30 am](https://user-images.githubusercontent.com/697155/31923945-7445a60c-b8b0-11e7-9b78-b930a62c3359.png)

I've implemented the button in the suggestion container
```
renderSuggestionsContainer = ({ containerProps, children, query }) => {
    return (
      <div {...containerProps}>
        <div
          onClick={() => {
            // dismiss auto suggest
            (document.getElementById("custom-autosuggest-input") as any).blur()
          }}
          style={{
            backgroundColor: '#E57373',
            cursor: 'pointer',
            padding: '10px 20px',
            borderTop: '1px solid rgba(255, 255, 255, 0.1)',
            borderRightColor: 'rgba(255, 255, 255, 0.1)',
            borderBottomColor: 'rgba(255, 255, 255, 0.1)',
            borderLeftColor: 'rgba(255, 255, 255, 0.1)'
          }}>
          Dismiss auto suggest
        </div>
        {children}
      </div >
    );
  }
```
```
  const inputProps = {
      id: 'custom-autosuggest-input',
      placeholder: this.props.placeholder,
      value,
      onChange: this.onChange
    }
```

**Comment by moroshko** [comment]
Why do you need this dismiss button in the first place?

**Comment by joevo2** [comment]
In mobile the touch target (outside the auto suggest) is a bit too small. Plus we want to "indicate" to the user that it is ok not to choose the auto suggested list of options. So we decide to have the dismiss button. Thanks and sorry for the trouble 😄  didnt realise you where the creator of this repo until now 👍

**Comment by moroshko** [comment]
No worries :)
There is no API method to close the suggestions, but you can just set `suggestions` to `[]`. [Example](https://codepen.io/moroshko/pen/dVEwWv?editors=0010)

**Comment by joevo2** [comment]
wow awesome @moroshko thanks a lot! 😄

**Comment by joevo2** [comment]
Silly me.... the `onSuggestionsClearRequested` is already been defined in the example 😑
