### ISSUE TITLE
How do I import 'AutosuggestHighlightMatch' and 'AutosuggestHighlightParse'?

### ISSUE THREAD

**Issue by SuperManEver** [moroshko/react-autosuggest#468]
I try to implement suggestions with highlight using example from here https://codepen.io/moroshko/pen/PZWbzK?editors=0010

If you take a look at the code you will find the usage of 'AutosuggestHighlightMatch' and 'AutosuggestHighlightParse'. 

I don't understand how to import them. Could you help me, please?

**Comment by moroshko** [comment]
You need to include [`autosuggest-highlight`](https://github.com/moroshko/autosuggest-highlight).

(If you inspect the JavaScript files that are included in this Codepen, you'll see that it uses `autosuggest-highlight`.)

**Comment by SuperManEver** [comment]
@moroshko it does work. Thank you for help. 
I think the issue can be closed.

**Comment by WDV329** [comment]
It was a lot of help.
Thanks!

**Comment by antoniobrandao** [comment]
Having the same problem

    import { AutosuggestHighlightMatch, AutosuggestHighlightParse } from 'autosuggest-highlight'

Results in

    Module not found: Can't resolve 'autosuggest-highlight'

What's the correct way to include it. @moroshko I don't see where the files are included in the related CodePen:

![image](https://user-images.githubusercontent.com/464121/34735001-c0584b3e-f565-11e7-8923-9917f6942383.png)


from https://codepen.io/moroshko/pen/OpPqxY

**Comment by antoniobrandao** [comment]
ok I got it

    import AutosuggestHighlightMatch from 'autosuggest-highlight/match'
    import AutosuggestHighlightParse from 'autosuggest-highlight/parse'

**Comment by jpggvilaca** [comment]
The example could state that it's including a 3rd party...
