### ISSUE TITLE
Fire event after user selects value from list

### ISSUE THREAD

**Issue by MokoPolo** [moroshko/react-autosuggest#471]
I closed this previously I thought I found the answer. Sorry for the confusion.

If I wanted to call logic to update a database once the user selects an item from the renderSuggestion which of your handlers would I need to implement?

So for example:
const languages = [
{
name: 'C',
year: 1972,
id: 1
}

If a user selects C then I want to store this choice in a database using the id which handler would this logic go into?

**Comment by AwolDes** [comment]
[Not the author] 

I'm using [onSuggestionSelected](https://github.com/moroshko/react-autosuggest#onSuggestionSelectedProp) which returns the object you select. From there you just add the call to your database :smile:
