### ISSUE TITLE
Search on array with element with multiples word

### ISSUE THREAD

**Issue by Skodddy** [moroshko/react-autosuggest#472]
I've been trying to make the auto-suggest works on array like this one (elements with multiple word separated by space):

```
const an_array= [
  {
    f_name: 'Bob Joe',
    year: Mark
  },
  {
    f_name: 'Mike John',
    l_year: 2005
  }
];
```

I want the autosuggest to suggest me 'Bob Joe' when I enter 'Bob' (default behavior) but also when I type 'Joe'. Any idea how to do that?

Thanks.

**Comment by moroshko** [comment]
Check the "Custom render" example on the [Homepage](http://react-autosuggest.js.org/).

**Comment by Skodddy** [comment]
Thank you I saw this example. It's close to what I'm searching for but not exactly. The example search two string that are on two different elements.

Searching Brown would work on this:
```
const people = [
  {
    first: 'Charlie',
    last: 'Brown',
  },
```
but not on 
```
const people = [
  {
    name: 'Charlie Brown',
  },
```

**Comment by moroshko** [comment]
Selecting the matching suggestions is done outside of Autosuggest.
It's completely in your control.
You'll have to modify the `getSuggestions` function to match your needs.
You might find [autosuggest-trie](https://github.com/moroshko/autosuggest-trie) useful.

**Comment by Skodddy** [comment]
I was mistaken, it seem like the example do exactly what I want, I just have another issue.

I believe i'm importing correctly 

`import React from 'react';
import ReactDOM from 'react-DOM';
import Autosuggest from 'react-autosuggest';
import match from 'autosuggest-highlight/match';
import parse from 'autosuggest-highlight/parse';

const people = [
  {
    first: 'Charlie Bob',
    last: 'Brown',
    twitter: 'dancounsell'
  },
  {
    first: 'Charlotte',
    last: 'White Bob',
    twitter: 'mtnmissy'
  },
  {
    first: 'Chloe',
    last: 'Bob Jones',
    twitter: 'ladylexy'
  },
  {
    first: 'Cooper',
    last: 'King',
    twitter: 'steveodom'
  }
];

//Regular_Expressions#Using_Special_Characters
const escapeRegexCharacters = str => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

	
// Teach Autosuggest how to calculate suggestions for any given input value.
const getSuggestions = value => {
	const escapedValue = escapeRegexCharacters(value.trim());
	if (escapedValue === '') {
		return [];
	}
	const regex = new RegExp('\\b' + escapedValue, 'i');
	return people.filter(person => regex.test(getSuggestionValue(person)));
};

const getSuggestionValue = suggestion => (`${suggestion.first} ${suggestion.last}`);

const renderSuggestion = (suggestion, {query}) => {
	const suggestionText = `${suggestion.first} ${suggestion.last}`;
	const matches = AutosuggestHighlightMatch(suggestionText, query);
	const parts = AutosuggestHighlightParse(suggestionText, matches);
	
	return (
		<span className={'suggestion-content ' + suggestion.twitter}>
			<span className="name">
			{
			  parts.map((part, index) => {
				const className = part.highlight ? 'highlight' : null;

				return (
				  <span className={className} key={index}>{part.text}</span>
				);
			  })
			}
		  </span>
		</span>
	);
}

class App extends React.Component {
	constructor() {
	super();

	this.state = {
	  value: '',
	  suggestions: []
	};
	}

	onChange = (event, { newValue, method }) => {
		this.setState({
		  value: newValue
		});
	};
	
	onSuggestionsFetchRequested = ({ value }) => {
		this.setState({
			suggestions: getSuggestions(value)
		});
	};

  onSuggestionsClearRequested = () => {
    this.setState({
      suggestions: []
    });
  };

  render() {
	const { value, suggestions } = this.state;
	const inputProps = {
	  placeholder: "Type 'c'",
	  value,
	  onChange: this.onChange
	};

    // Finally, render it!
    return (
     <Autosuggest 
        suggestions={suggestions}
        onSuggestionsFetchRequested={this.onSuggestionsFetchRequested}
        onSuggestionsClearRequested={this.onSuggestionsClearRequested}
        getSuggestionValue={getSuggestionValue}
        renderSuggestion={renderSuggestion}
        inputProps={inputProps} />
    );
  }
}

ReactDOM.render(<App />, document.querySelector('.container'));`

but I got this error when entering something in the input element (after executing npm install autosuggest-highlight --save too_.

`ReferenceError: AutosuggestHighlightMatch is not defined
TypeError: internalInstance is null
`

**Comment by moroshko** [comment]
Check out [the examples](https://github.com/moroshko/autosuggest-highlight#examples) to see how to import. `AutosuggestHighlightMatch` is available only if you use the UMD build.

**Comment by Skodddy** [comment]
import AutosuggestHighlightMatch from 'autosuggest-highlight/umd/match';
import AutosuggestHighlightParse from 'autosuggest-highlight/umd/parse'; 

worked
