### ISSUE TITLE
Dropdown without input value

### ISSUE THREAD

**Issue by philjackson** [moroshko/react-autosuggest#48]
We'd love to be able to dropdown the suggestions on input focus *even* when there's no value. Looking through the source, it seems that might be impossible at the moment - is that the case?

**Comment by moroshko** [comment]
@philjackson Interesting. Could you describe your use case please? Have you seen others that behave this way? Link please?

**Comment by philjackson** [comment]
@moroshko What we're really looking for is a combobox-style input. We need to allow the user to input arbitrary text or use one of a few suggestions we can give them. However, we have a preference for them selecting one of our predefined options, so would like them to see it as soon as possible.

**Comment by moroshko** [comment]
@philjackson I wonder whether autosuggest is the best tool for this. Are you still interested in the filtering behaviour, i.e. as user starts typing the list becomes smaller? How many suggestions do you have when the input is empty?

Maybe something like [react-combobox](http://kbakba.github.io/reactjs-combobox/examples.html) is more suitable for you? Have a looks also [here](http://react.rocks/tag/Dropdown).

**Comment by philjackson** [comment]
Still interested in the filtering, definitely. The number of items will vary, but will always be small enough that presenting all of the options wouldn't be a poor ux/network experience.

react-combobox looks good, but we'd like to keep the look and feel consistent (we use your control further up the page to complete large datasets).

**Comment by moroshko** [comment]
@philjackson Thanks for the explanation. I think your use case makes sense.

After some digging I found that it was a bug. All fixed now. If you use version 1.18.2 you should be able to use `showWhen={() => true}`. Let me know how you go.

BTW, will the page you're working on be publicly available? If yes, and you don't mind I can include your site in the "Used by" section in the README (doesn't exist yet).

**Comment by philjackson** [comment]
@moroshko That's great - thank you very much. We'll try it now.

We're not public yet, but will be soon(ish). I'll try and remember to ping you when we're up!

**Comment by moroshko** [comment]
@philjackson Great, thanks!

**Comment by philjackson** [comment]
Tested - seems to work fine. Thanks again.

:+1:
