### ISSUE TITLE
Reference to highlighted suggestion in renderSuggestionsContainer

### ISSUE THREAD

**Issue by stanley90** [moroshko/react-autosuggest#480]
I need to apply different styling to the suggestions container depending of whether a suggestion is highlighted or not. I tried to access it through a stored `ref` but that's often `null` (not sure that's even correct). Also, I tried to store a reference to the highlighted suggestion in `onSuggestionHighlighted`, but that's called _later_ than `renderSuggestionsContainer`.
Is there currently a way to do this?
Thanks

**Comment by stanley90** [comment]
Additionally, I'm rendering an "Add new: <query>" on the bottom of the container, which I'd like to 
1) hide if the query equals one of the displayed suggestions (so that it's not shown twice)
2) be clickable, calling `addTag`
Or better to do the whole "Add new" footer as a special suggestion type, instead of adding it in the container?

<img width="537" alt="image" src="https://user-images.githubusercontent.com/48182/33315417-f008fbe0-d430-11e7-8017-6e83ada2b499.png">

**Comment by moroshko** [comment]
At the moment, we don't have access to the highlighted suggestion in `renderSuggestionsContainer`. We could pass it in, however, similarly to how it's done in [`inputProps.onBlur`](https://github.com/moroshko/react-autosuggest#inputPropsOnBlur).

Regarding the "Add new" button, you could do something like [this](https://codepen.io/moroshko/pen/GOeKwB?editors=0010).

**Comment by stanley90** [comment]
Thanks for the example, that should work for me, I just have to actually put the current suggestions to state (with `tagsinput`, I didn't really need to).
I thought to use the highlighted suggestion in `renderSuggestionsContainer` to add highlight to the "Add new" part (I don't have a button there, just a row) so it has visual indication for keyboard navigation (which actually works fine, Enter adds new item when no suggestion is selected).

**Comment by moroshko** [comment]
Sorry, I'm probably missing something. Don't you want "Add new" to always be highlighted? Or, do you have a case where "Add new" is visible, but not highlighted?

**Comment by stanley90** [comment]
So I type a letter which opens the dropdown, no option is highlighted. Then I keep pressing the Down arrow on keyboard, and the highlight goes from the first suggestion down (pressing Enter would select the highlighted suggestion), then disappears (pressing Enter now would add the new tag, so the functionality is okay). 
I want to add the highlight style to the "Add new" part when no suggestion is highlighted.

![highlight](https://user-images.githubusercontent.com/48182/33596873-b6b96ec0-d99d-11e7-9a02-e498a9bb991e.gif)

**Comment by moroshko** [comment]
Oh, I see what you are trying to do now.
Although I'm not an accessibility expect, I feel like this might not be the best approach, since when no suggestion is highlighted you won't have `'aria-activedescendant'` on the input pointing to the "Add new" option.

Have you considered adding "Add new" as the last suggestion?

**Comment by stanley90** [comment]
Yes, I have considered that, but didn't want to dive into the refactor until I run out of options with `renderSuggestionsContainer` 😁 But if you think that's a better approach, then I can do that.

**Comment by moroshko** [comment]
Yeah, I think it's probably better because you get the accessibility aspect for free.
Check out [this Codepen](https://codepen.io/moroshko/pen/vpBzMr?editors=0010).

**Comment by stanley90** [comment]
Yeah, I'll try something along this. I'll close the issue then. Thanks.

**Comment by chiragv508** [comment]
@moroshko how can we add footer on each section ? like header using renderSectionTitle..
