### ISSUE TITLE
Differentiate onSuggestionSelected from onKeyDown

### ISSUE THREAD

**Issue by Sorgrum** [moroshko/react-autosuggest#483]
## Are you making a feature request?

* Please describe your use case from user journey point of view, e.g.:

  > I'd like to take a separate action when a user presses enter on the input vs. when a user selects a suggestion

I have the following: 
```js
                onSuggestionSelected={evt => {
                  console.log(evt, evt.type);
                }}
```
and 
```js
    const inputProps = {
      ...
      onKeyDown: evt => this.props.runCommand(evt),
    };
    ...
    runCommand = async (evt, more) => {
      if (evt.which === ENTER_CHAR_CODE) {
        console.log(evt, evt.type);
        if (evt.suggestion) {
        } else {
          evt.preventDefault();
          await this.child.handleSubmit(evt);
          this.setState({ command: '' });
        }
      } else if (evt.which === TAB_CHAR_CODE) {
        evt.preventDefault();
        this.setState({ command: this.child.attemptAutocomplete() });
      }
    };
```
but the events they are sending are the exact same. I cant differentiate a suggestion being selected vs an event in which the enter key is pressed on the input.

The idea is if someone presses enter in the input I'd like to run the runCommand function but if they select the suggestion I'd like the input value to have the value of the suggestion.

**Comment by moroshko** [comment]
You could do something like [this](https://codepen.io/moroshko/pen/rYRNGw).

**Comment by Sorgrum** [comment]
Thank you @moroshko!
