### ISSUE TITLE
Feature Request / Use case clarification

### ISSUE THREAD

**Issue by davidfurlong** [moroshko/react-autosuggest#488]
I want to be able to render a message in the dropdown when there are no results. 
I tried using the `renderSuggestionsContainer` prop, however it seems that the dropdown is closed upon no results. There's probably a way to do this with the existing props, but theres so many ways to do this.

----

Potential solutions:

A) Could add an explicit prop `closeOnNoResults` which defaults to true, but when set to false will not close the dropdown upon no results.
B) Some sort of weird css class fix on my side (seems really messy)
C) Make the component such that if there are no results it's still invisible, unless you are defined `renderSuggestionsContainer` to render other items. (tricky as container padding etc would mess things up)
D) Making the state of the popover controllable by the end user (me) and having simple steps to do this.

Seeming solutions which aren't:
- Using `alwaysRenderSuggestions` - as I still want  to hide it `onBlur`, and preserve the other functionality

**Comment by moroshko** [comment]
You could implement "no results" outside of the Autosuggest: [Codepen](https://codepen.io/moroshko/pen/wMRmmM?editors=0010)

**Comment by davidfurlong** [comment]
> You could implement "no results" outside of the Autosuggest: Codepen

I suppose so, but thats not really the same UX

**Comment by moroshko** [comment]
Do you mean that the experience that the end user gets is not the same? How?

**Comment by davidfurlong** [comment]
> Do you mean that the experience that the end user gets is not the same? How?

The message is not in the results dropdown. I suppose I could make a second dropdown that opens with the no results message, and try and style it the same, but doesn't seem ideal

**Comment by james-ff** [comment]
I managed to achieve this effect via a workaround. I used a boolean in state to track when suggestions should be shown and should not. When text is entered and results should not be shown (ie. no results message should be shown), set suggestions to anything so that it displays the dropdown and in the function "renderSuggestionsContainer" don't display the children contents (which will contain the suggestions that you entered just to make the dropdown show). Code below to illustrate:

`renderSuggestionsContainer = ({ containerProps, children, query }) => {
    const resultsHeader = (
      <div style={{ margin: "9px 20px", fontSize: "14px", color: "#777" }}>
        Select a Single Card to Compare
      </div>
    );
    const noResultsHeader = (
      <div style={{ margin: "9px 20px", fontSize: "14px", color: "#777" }}>
        No card names contain "{query}"
      </div>
    );
    return (
      <div {...containerProps}>
        {!this.state.noSuggestions && resultsHeader}
        {!this.state.noSuggestions && children}
        {this.state.noSuggestions && noResultsHeader}
      </div>
    );
  }`

**Comment by davidfurlong** [comment]
Thats a creative solution, thanks for sharing @james-ff
