### ISSUE TITLE
Using another input element?

### ISSUE THREAD

**Issue by binarykitchen** [moroshko/react-autosuggest#49]
Is there an option where I can refer to another input element? Because our app relies heavily on react-bootstrap which comes with a nice set of predefined inputs.

To avoid ugly hacks or forks, it would be nice if this module would accept a reference to another existing input. Does such an option already exist or do you think you could add that?

**Comment by moroshko** [comment]
@binarykitchen I'm not sure what you mean. What's your use case for react-autosuggest? What are you trying to achieve with this new option?

**Comment by binarykitchen** [comment]
I want to use these input elements instead
http://react-bootstrap.github.io/components.html

**Comment by moroshko** [comment]
@binarykitchen I haven't used `react-bootstrap` before, and not familiar with it's `<Input />` behaviour. I can't immediately see how to integrate `react-autosuggest` with `react-bootstrap`, but if you have an idea how this could work, feel free to submit a Pull Request (with a working example, please).

**Comment by sapegin** [comment]
I also need this. Will try to make a PR if I have time.
