### ISSUE TITLE
Initial value is not set

### ISSUE THREAD

**Issue by renebliesenbach** [moroshko/react-autosuggest#5]
I have a problem concerning the initial value, which is never set. The initial value is setted via props. Here is my Component:
module.exports = React.createClass({

  getDefaultProps: function() {
    return {
      initial: '',
      id: '',
      name: '',
      className: 'form-control',
      placeholder: 'Chose customer...'

    }
  },
  getInitialState: function() {
    return {
      CUSTOMERS: [],
      initial: this.props.initial
    };
  },
  componentWillReceiveProps: function(nextProps) {
    this.fetchData();
    this.setState({
      initial: nextProps.initial
    });
  },
  getSuggestions: function(input, callback) {
    var customerArray = this.state.CUSTOMERS;
    var regex = new RegExp('^' + input, 'i');
    setTimeout(function() {
      callback(null, customerArray.filter(name=> regex.test(name)));
    }, 300);
  },
  componentWillMount: function() {
    this.fetchData();
  },
  fetchData: function() {
    var fetched = [];
    $.get('/dataserveprovider/rest/data/customer/all', function(result) {
      for (var i = 0; i < result.length; i++) {
        fetched[i] = result[i].name;
      }
    });
    this.setState({
      CUSTOMERS: fetched
    });
  },
  render: function() {
    var inputAttributes = {
      id: this.props.id,
      name: this.props.name,
      className: 'this.props.className',
      placeholder: this.props.placeholder,
      value: this.state.initial
    };
    return (
      <div>
        <Autosuggest inputAttributes={inputAttributes}
                     suggestions={this.getSuggestions}
                     />
      </div>
    );
  }
});

**Comment by moroshko** [comment]
@renebliesenbach Could you please show where you instantiate `<Autosuggest />`, and where you instantiate the component above? 

Could you also try and change

    var inputAttributes = {
      ...
      value: this.state.initial
    };

to

    var inputAttributes = {
      ...
      value: 'My fancy initial value'
    };

and let me know if you see the initial value?

Formatted code would he highly appreciated.

**Comment by renebliesenbach** [comment]
In autocompleteComponent.jsx (Code above):
'use strict';
var React = require('react');
var Autosuggest = require('react-autosuggest');
...

In my FormComponent:

var Autocomplete = require('./autocompleteComponent.jsx');
< div className = "row" >
     < div className = "col-md-4" > 
     <Autocomplete ref="customer" initial={this.state.dokument.customer}/>
     </div>
</div> 
If i debugg the render function of AutocompleteComponent  the value is setted correctly, but the input does not show it.
I also tried to set the inputAttributes value as outlined above, but it also does not work :-(
I builded the component with browserify. Here my package.jason

{
  "name": "React_Browserify",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "compile": "browserify -t reactify src/app.jsx -o build/bundle.js",
    "watch": "browserify -w -t reactify src/app.jsx -o build/bundle.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "reactify": "^1.1.0"
  },
  "dependencies": {
    "backbone": "^1.1.2",
    "backbone-react-ui": "^0.1.8",
    "backbone.paginator": "^2.0.2",
    "express": "^4.12.3",
    "griddle-react": "^0.2.12",
    "lodash": "^3.6.0",
    "moment": "^2.9.0",
    "react-autosuggest": "^1.7.1",
    "react-bootstrap": "^0.20.2",
    "react-data-components": "^0.3.0",
    "react-daterange-picker": "^0.5.3",
    "react-router": "^0.13.2",
    "react-skylight": "^0.2.0",
    "react-table-view": "0.0.3",
    "underscore": "^1.8.2"
  }
}

**Comment by moroshko** [comment]
@renebliesenbach Can you show how you use `<Autosuggest />` in `autocompleteComponent.jsx`? The code in your first comment seems truncated. I can't see all the props you pass to `<Autosuggest />`.

**Comment by renebliesenbach** [comment]
```javascript
 'use strict';
var React = require('react');
var Autosuggest = require('react-autosuggest');

module.exports = React.createClass({

  getDefaultProps: function() {
    return {
      initial: '',
      id: '',
      name: '',
      className: 'form-control',
      placeholder: 'Kunde auswählen...'

    }
  },
  getInitialState: function() {
    return {
      CUSTOMERS: [],
      initial: this.props.initial
    };
  },
  componentWillReceiveProps: function(nextProps) {
    this.fetchData();
    this.setState({
      initial: nextProps.initial
    });
  },
  getSuggestions: function(input, callback) {
    var customerArray = this.state.CUSTOMERS;
    console.log('getSuggestions customerArray ' + customerArray);
    var regex = new RegExp('^' + input, 'i');

    setTimeout(function() {
      callback(null, customerArray.filter(bezeichnung => regex.test(bezeichnung)));
    }, 300);
  },
  componentWillMount: function() {
    this.fetchData();
  },
  fetchData: function() {
    var fetched = [];
    $.get('/dataserveprovider/rest/data/kunden/all', function(result) {
      for (var i = 0; i < result.length; i++) {
        fetched[i] = result[i].bezeichnung;
      }
    });
    this.setState({
      CUSTOMERS: fetched
    });
  },
  render: function() {
    var inputAttributes = {
      id: this.props.id,
      name: this.props.name,
      className: 'this.props.className',
      placeholder: this.props.placeholder,
      value: this.props.initial
    };
    return (
      <div>
        <Autosuggest inputAttributes={inputAttributes}
                     suggestions={this.getSuggestions}
                     />
      </div>
    );
  }
});

**Comment by moroshko** [comment]
@renebliesenbach Thanks for the formatting! It's much easier to help you this way. This code looks ok. Could you show which props you are passing to `autocompleteComponent.jsx`?

If you could create a repo that I can clone and recreate the issue that would be helpful.

**Comment by moroshko** [comment]
@renebliesenbach Are you still experiencing the issue? If yes, please create an reproducible example.

**Comment by moroshko** [comment]
@renebliesenbach Please check if the latest version still have this issue, and if yes, please create a reproducible example.
