### ISSUE TITLE
Scaling?

### ISSUE THREAD

**Issue by EricWarnke** [moroshko/react-autosuggest#50]
Any idea how this performs with list of 2,000 entries? 5,000?

**Comment by moroshko** [comment]
@EricWarnke I haven't tried it with large lists, but feel free to try and report back.

I wonder, however, what's your use case to have so many suggestions? One could argue that from UX point of view it's not that helpful to see so many suggestions.

**Comment by EricWarnke** [comment]
I'll maybe give it a shot.

We're trying to let enterprise customers match up emails from one service to another. Sometimes there are thousands of emails that need to get mapped and the customer would simply search for the username and match it. We'd never display thousands of options at once.

**Comment by moroshko** [comment]
Please open a new issue if you experience any issues with large data sets.
