### ISSUE TITLE
Inconsistent behaviour of renderSuggestion query

### ISSUE THREAD

**Issue by jgresty** [moroshko/react-autosuggest#504]
There is inconsistency about the `query` argument passed to `renderSuggestion`, when there is a value in the input then it works as expected. However when the input field is empty then it receives the value of whichever selection is highlighted.

See codepen: https://codepen.io/anon/pen/wyKgOp

  1. Allow `shouldRenderSuggestions` with empty input
  2. Focus on the input field
  3. Press <kbd>Down</kbd> a few times and observe the query argument passed
  4. Clear input and enter a character
  5. Press <kbd>Down</kbd> a few times and observe the query argument passed

  **Observed behaviour:** Query argument passed is value of selected suggestion when no input is initially empty
  **Expected behaviour:** Query argument passed is empty string when input is initially empty

**Comment by moroshko** [comment]
Thanks for reporting!
[Fixed](https://github.com/moroshko/react-autosuggest/commit/05ce8adaa95d86a30dc67e8535e703d5071cc71d) and [published](https://github.com/moroshko/react-autosuggest/releases/tag/v9.3.3).
