### ISSUE TITLE
renderInputComponent not working with styled-components or rea

### ISSUE THREAD

**Issue by mackbrowne** [moroshko/react-autosuggest#506]
Apologies, I tried to make a codepen but am at work and unfamiliar with the tool and failed at it.  I can try again this weekend when I'm not at work if anyone requests for it.

TLDR: styled-components, the popular react css library seems to be conflicting with react-autosuggest.

I've isolated the problem and it seems that the suggestions list is not rendered when using 'renderInputComponent', here is my exact prop that I'm using:

```
renderInputComponent={inputProps => <AddUser {...inputProps} />}
```

'AddUser' is a custom styled-component that is wrapping around the reactstrap Input component.  I've already determined that it works with a vanilla Reactstrap Input, and the html standard input.  Only styled component custom input components are broken.

As a workaround I've found that the prop 'alwaysRenderSuggestions' set to true will actually display the suggestions.  I'm currently using this prop to show/hide the suggestions, but I'm fairly certain this is not the correct way to do things.

```
  alwaysRenderSuggestions={!!users.length}
```

**Comment by francomendoza** [comment]
did you recently install package via NPM? I also had issues with ```renderInputComponent```

Then I realized NPM loaded v3.9.0, which is way behind.  Anyhow, may be the cause, may be something else completely.

**Comment by mackbrowne** [comment]
Figured it out, my 'AddUser" component needed to pass { ...inputProps }, it was only passing down onChange to the actual input element

**Comment by aniket07sudo** [comment]
So whats the Solution

**Comment by aniket07sudo** [comment]
'?
