### ISSUE TITLE
ComboBox-like behavior

### ISSUE THREAD

**Issue by anatoliyarkhipov** [moroshko/react-autosuggest#51]
Hi. I use the component with small datasets (like user roles, for example, 4-5 records) and I want to open the suggestions list with all roles in it when user clicks in the input. The `getSuggestions` callback already designed to return the whole list if the `input` arg is empty, but I can not figure out how to force the component to do this.

**Comment by moroshko** [comment]
@anatoliyarkhipov Try `showWhen={() => true}`

**Comment by anatoliyarkhipov** [comment]
I already tried that, but it did not help the first time. After your response I digged into this a little bit further and figured out how to do what I want. 

Only two problems here.

The `renderSuggestions()` method:

```
  renderSuggestions() {
    if (this.state.value === '' || this.state.suggestions === null) {
      return null;
    }
    // ...
```
This - `this.state.value === ''` - blocks rendering of suggestions if the input is empty. I just decorated this method:

```
    renderSuggestions() {

        const value = this.state.value

        this.state.value = true

        const result = super.renderSuggestions()

        this.state.value = value

        return result
    }
```

The second problem is that I want to open the suggestions box when input is focused (or clicked). For this I completely replaced the original `render` method to be able to trigger the `onInputChange` handler when the input is focused:

```
    render() {

        const ariaActivedescendant =
            this.getSuggestionId(this.state.focusedSectionIndex, this.state.focusedSuggestionIndex);

        return (
            <div className="react-autosuggest">
                <input {...this.props.inputAttributes}
                    type="text"
                    value={this.state.value}
                    autoComplete="off"
                    role="combobox"
                    aria-autocomplete="list"
                    aria-owns={'react-autosuggest-' + this.props.id}
                    aria-expanded={this.state.suggestions !== null}
                    aria-activedescendant={ariaActivedescendant}
                    ref="input"
                    onFocus={this.onInputChange} // <-----
                    onChange={this.onInputChange}
                    onKeyDown={this.onInputKeyDown}
                    onBlur={this.onInputBlur} />
                {this.renderSuggestions()}
            </div>
        );
    }
```

Now it works.

**Comment by moroshko** [comment]
@anatoliyarkhipov From your code it looks like you are using an old version of `react-autosuggest`. If you use `1.18.3`, you don't need any hacks.

**Comment by anatoliyarkhipov** [comment]
You are right. My current version is 1.14.1. Thank you for help, @moroshko !
