### ISSUE TITLE
Can I Pass Additional Props?

### ISSUE THREAD

**Issue by pythoncreate** [moroshko/react-autosuggest#511]
Two questions:

My Suggestion data looks like this:

 "name": "Bitcoin",  "symbol": "BTC"

I'm passing the symbol in my data to the 'value' variable in react-autosuggest.

First question--IS there an easy way to also in my case, pass the 'name' variable as props when the form is submitted?

Second question--how do i get it so that my autosuggest is searching both my name and symbol components?   Similar to on finance.google.com---if a user enters BTC or a user enters Bitcoin, the right value would appear in the input box.

Thanks!

**Comment by ggglyke** [comment]
Hi! Did you find a way ? I'm looking to do this too.
