### ISSUE TITLE
Preventing default up/down key behavior even when no suggestions are available.

### ISSUE THREAD

**Issue by ShibumiGrant** [moroshko/react-autosuggest#517]
Default behavior for pressing the <kbd>up</kbd> and <kbd>down</kbd> keys is being `preventDefault`'ed, even in cases where the autosuggest does not need to be using special handling for them. In `input` elements, this manifests as not being able to quickly jump to the beginning and end of an input using these keys, and in `textarea` and `contenteditable` elements it prevents jumping between lines.

Single-line Input Reproduction Steps: (Use the [Basic example](http://codepen.io/moroshko/pen/LGNJMy))
  1. Focus the input field.
  2. Type `asdf`.
  3. Make sure there are no suggestions available.
  4. Press <kbd>up</kbd>.

  **Observed Behavior:** The cursor does not move.

  **Expected Behavior:** The cursor moves to be in front of the first character in the input.

Multi-line Input Reproduction Steps: (Use this [codepen](https://codepen.io/ShibumiGrant/pen/ZrwEQG))
  1. Focus the input field.
  2. Type `asdf`.
  3. Press enter to create a new line.
  4. Type `asdf` again.
  5. Make sure there are no suggestions available.
  6. Press <kbd>up</kbd>.

  **Observed Behavior:** The cursor does not move.

  **Expected Behavior:** The cursor moves to the line above.

**Comment by moroshko** [comment]
Sounds reasonable. Would you like to contribute a PR?

**Comment by ShibumiGrant** [comment]
Gladly! Let me know if any changes should be made.
Any idea when the next release will be?

**Comment by cozmy** [comment]
@moroshko, do you know when you'd have time to merge @ShibumiGrant's changes? I also have the same issue and the proposed changes work.

**Comment by MUmer01** [comment]
Is the any progress in Preventing default up/down key behavior?
