### ISSUE TITLE
Dont scroll when highlightedItemIndex is last

### ISSUE THREAD

**Issue by zjoin** [moroshko/react-autosuggest#519]
Now on keydown/up is a infinite scroll.  How stop on last item?

**Comment by moroshko** [comment]
What you suggest goes against the [accessibility guidelines](https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#autocomplete):

> Note that the arrows will wrap through the text box when the top or bottom of the list is reached. For example, pressing the down arrow when the last choice is highlighted will move focus back to the text box, pressing down again will move focus to the first item in the list. Likewise, with focus in the text box and the list displayed, pressing up arrow will move focus to the last item in the list.
