### ISSUE TITLE
Input value does not update when props change

### ISSUE THREAD

**Issue by ben-ng** [moroshko/react-autosuggest#52]
`componentWillReceiveProps` is not implemented. This means that the value of the input can't be set by the parent component. Quite annoying in a realtime system! I had to hack around it by setting the state directly from the parent.

**Comment by moroshko** [comment]
@ben-ng We are going to add support for controlled components in 2.0.
Feel free to check out the 2.0 branch.

**Comment by donaldparker** [comment]
@ben-ng care to share your text, I am setting the value of the text field in the parent component, however as soon as the field gets focus the value is restored.

**Comment by ben-ng** [comment]
@donaldparker I put a ref on the autosuggest component and did this from the parent

```
this.refs.autosuggest.setState({value: 'something'})
```

**Comment by moroshko** [comment]
@ben-ng @donaldparker I just released react-autosuggest 2.0 which supports controlled behaviour. Sorry it took so long..
