### ISSUE TITLE
Wrapping the input in a container div?

### ISSUE THREAD

**Issue by taykcrane** [moroshko/react-autosuggest#524]
Anybody have advice on how I can wrap the input field in it's own container div? Currently, when <Autosuggest /> is rendered, the structure is as follows:

```
<div class="container">
    <input />
    <div class="suggestions-container">
    </div>
</div>
```

But I need:

```
<div class="container">
    <div class="input-container">
        <input />
    </div>
    <div class="suggestions-container">
    </div>
</div>
```

This is because I have very complicated styling requirements on my input that will only work with it's own isolated container. Any help would be greatly appreciated!

**Comment by moroshko** [comment]
Have you tried [`renderInputComponent`](https://github.com/moroshko/react-autosuggest#renderinputcomponent-optional)?

**Comment by taykcrane** [comment]
Wow, I knew I was missing something obvious when I couldn't find this option. Thanks for the help. Closing ticket.
