### ISSUE TITLE
Peer Dependency error.

### ISSUE THREAD

**Issue by ngyangjo** [moroshko/react-autosuggest#531]
Hi,
While doing a npm install, I'm getting "The package react does not satisfy its siblings' peerDependencies requirements!" error.

Full Error Stack
`npm WARN unmet dependency which is version 0.14.7
npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/abiraj/.nvm/versions/v0.12.0/bin/node" "/Users/abiraj/.nvm/versions/v0.12.0/bin/npm" "install" "react-autosuggest" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer flux@3.1.3 wants react@^15.0.2 || ^16.0.0-beta || ^16.0.0
npm ERR! peerinvalid Peer formik@0.10.5 wants react@>=15
npm ERR! peerinvalid Peer muicss@0.9.28 wants react@^0.14.0 || ^15.0.0 || ^16.0.0
npm ERR! peerinvalid Peer radium@0.19.6 wants react@^15.3.0 || ^16.0.0
npm ERR! peerinvalid Peer react-day-picker@7.0.5 wants react@~0.13.x || ~0.14.x || ^15.0.0 || ^16.0.0
npm ERR! peerinvalid Peer react-dom@16.0.0 wants react@^16.0.0-beta.5
npm ERR! peerinvalid Peer react-helmet@5.2.0 wants react@>=15.0.0
npm ERR! peerinvalid Peer react-intl@2.4.0 wants react@^0.14.9 || ^15.0.0 || ^16.0.0
npm ERR! peerinvalid Peer react-responsive-modal@2.0.0 wants react@^15.0.0 || ^16.0.0
npm ERR! peerinvalid Peer react-router-dom@4.2.2 wants react@>=15
npm ERR! peerinvalid Peer react-tooltip@3.4.0 wants react@>=0.14
npm ERR! peerinvalid Peer react-intl-formatted-duration@1.1.0 wants react@>= 15.0
**npm ERR! peerinvalid Peer react-autosuggest@9.3.4 wants react@>=0.14.7**
npm ERR! peerinvalid Peer react-router@2.8.1 wants react@^0.14.0 || ^15.0.0`

My package.json has react^16.0.0. Is there a way to make it work for react^16.0.0. As per the error, it requires react@0.14.7.  Installing react@0.14.7 didn't work too.

**Comment by ngyangjo** [comment]
Seems to be a problem in my dev environment. I deleted the node modules folder and ran
`npm install`
`npm update`

and it works now.

**Comment by inform880** [comment]
@ngyangjo I'm getting this same error, but your fix didn't seem fix it. Any ideas?
