### ISSUE TITLE
Using React-Router <Link> deactivated enter press

### ISSUE THREAD

**Issue by DavidSSchwartz** [moroshko/react-autosuggest#543]
Used to be: when I press enter a new component opens up.
Now: I made the autosuggest component render a <Link> tag from react-router-dom.  When I click on a suggestion the Link works and redirects, but when I press enter all that happens is the suggestions disappear, it does not change the parameters in the top bar, as it should, and as it does when I click on it.
Here is the relevant code:

       renderSuggestion = suggestion => (
		  
			  <div className="suggestion">
			  	
			  		 <Link to={`/topic/${suggestion._id}`}>{suggestion._id}</Link>
				  	
			</div>
					
nothing else changed,  
it used to be :

            <div className="suggestion">
			  	
			  		{suggestion._id}
				  	
				</div>

**Comment by DavidSSchwartz** [comment]
I figured it out...
used on key down and the react-router-dom Redirect.

**Comment by TanyaM** [comment]
@DavidSSchwartz : Appreciate if you could post how you got it working

**Comment by TanyaM** [comment]
Got it working as follows.

 onSuggestionSelected(event, { suggestion }) {
        if (event.key === 'Enter') {
            const path = 'path constructed using suggestion param';
            this.props.history.push(path);
       }

And above event is bound at the AutoSuggest as follows.

<Autosuggest
                // other events goes here
                onSuggestionSelected={this.onSuggestionSelected}
                }}
            />

**Comment by milind2945** [comment]
@TanyaM could you please help me out.

 onSuggestionSelected = (event, { suggestion }) => {
    console.log(event)
    this.setState({
      query: suggestion.ROMAN,
    });
  };

i need to route to anothe page from here how can i do that
