### ISSUE TITLE
Is there a delay/debounce parameter?

### ISSUE THREAD

**Issue by jjvattamattom** [moroshko/react-autosuggest#55]
Is the suggester called for each change or can we set a delay between requests?

**Comment by moroshko** [comment]
@jjvattamattom At the moment, there is a default debounce of 100ms on the [`suggestions`](https://github.com/moroshko/react-autosuggest#suggestionsOption) function. If this default behaviour is not what you need, I'll be happy to review a Pull Request :)

**Comment by jjvattamattom** [comment]
Its good. Thanks!

**Comment by avindra** [comment]
Linking #76 for reference
