### ISSUE TITLE
Force open autosuggest on input click

### ISSUE THREAD

**Issue by ericbiewener** [moroshko/react-autosuggest#559]
## Are you making a feature request?

I have created an `AutoSuggestMulti` component that allows the user to select multiple values. I also have a wrapping `StaticAutoSuggestMulti` component that provides the autosuggest with a fixed set of suggestions, filtered by the query. Therefore, when the query is empty, it provides the full list of suggestions.

Currently, when the user makes a selection, the suggestions become hidden and the `StaticAutoSuggestMulti`'s input remains focused. This is all desirable. At this point, the user can reveal the the suggestions again in a few ways:

1. Blur and re-focus the input
2. Start typing
3. Press the key down 

I'd like the user to be able to simply click the input again to reveal the suggestions. This is how you'd reveal the options in a normal `<select>` field, so clicking is a likely way the user will try to get the suggestions to show up again.

Currently, I've got a hack in place that sets an `onClick` handler on the input which simply calls `setState()` with a copy of the suggestions:
```js
this.setState({ suggestions: this.state.suggestions.map(s => ({ ...s })) });
```

I'd like the API to officially support this behavior, such as via a `revealSuggestionsOnClick` boolean prop.

**Comment by The-Code-Monkey** [comment]
@ericbiewener I am struggling with this issue right now I need it so that when i focus the input field it displays the full list below if there is nothing typed are you able to display the full code of what you did to get this to work struggling. 

I plus one this as a feature for the next version

**Comment by ericbiewener** [comment]
@The-Code-Monkey I think you can accomplish this with the current API. I'm guessing you just need to make [`shouldRenderSuggestions`](https://github.com/moroshko/react-autosuggest#shouldRenderSuggestionsProp) always return `true`.

**Comment by The-Code-Monkey** [comment]
Perfect thank you works as intended
