### ISSUE TITLE
Is it possible to use it with textarea?

### ISSUE THREAD

**Issue by PetrSnobelt** [moroshko/react-autosuggest#56]
Hi, I'm looking for autosuggest for textarea, is it possible to use react-autosuggest with textarea and if so can you add example?

Thanks

**Comment by moroshko** [comment]
@PetrSnobelt Could you describe your use case?

**Comment by PetrSnobelt** [comment]
I have textarea for supplier full name and address. 
When someone start typing supplier name I'd like to allow them to use previously inserted supplier.

In past I use http://bassistance.de/jquery-plugins/jquery-plugin-autocomplete/ for this, but I'm looking for react/nojquery alternative

**Comment by moroshko** [comment]
@PetrSnobelt It's not possible to achieve what you want with this component. `react-autosuggest` always renders an `<input>` element.
