### ISSUE TITLE
9.4.1 introduces mousedown/mouseup bug on click to select

### ISSUE THREAD

**Issue by lvpro** [moroshko/react-autosuggest#568]
## Are you reporting a bug?
Yes.

https://codepen.io/anon/pen/KxQovE

(Note, this required changing the loaded version on Codepen to 9.4.1).

  1. Focus on the autosuggestion input field.
  2. Type `c`, and wait for suggestions to appear
  3. CLICK on a suggestion.
  4. Now click on the second input box below.

  **Observed behavior:** 
Focus goes back to autosuggestion.

  **Expected behavior:**
Focus should not go back to autosuggestion.  This began in 9.4.1 today.

**Comment by moroshko** [comment]
@lvpro Thanks for reporting this!

@aberezkin Mind taking a look at this regression?

**Comment by stefangu** [comment]
We are having the same problem, started recently. We are using the standalone UMD build.

**Comment by maxkolyanov** [comment]
@aberezkin @moroshko 
There's another regression related to unwanted input focus, coming from code in `v9.4.1`.
`focusInputOnSuggestionClick` prop seems to be ignored now inside `onBlur` handler, as it will still  call `input.focus()`. 

This might actually warrant renaming a prop slightly or introducing a prop, but in any case seems like an unwanted behavior. 
Will be rolling back to `v9.4.0` for now as well.

**Comment by lvpro** [comment]
Can we get this pushed to npm?

**Comment by moroshko** [comment]
@maxkolyanov Could you provide a repro for the regression you found in 9.4.1, and open a new issue?
