### ISSUE TITLE
Dynamically switch suggestions-property

### ISSUE THREAD

**Issue by DERIIIFranz** [moroshko/react-autosuggest#57]
When I try to switch Autosuggest's suggestions-property on runTime, it seems the initial suggestions-function keeps on getting invoked instead of the new one.

How to achieve the expected behavior?

**Comment by moroshko** [comment]
@DERIIIFranz At the moment, unfortunately, this is not possible. This will be possible in v3.0 (see 3.0 branch).

**Comment by DERIIIFranz** [comment]
do you know a workaround to get there?

**Comment by moroshko** [comment]
@DERIIIFranz You'll probably have to fork the repo, and update `suggestions` in `componentWillReceiveProps()`.

**Comment by DERIIIFranz** [comment]
If it's that simple, why isn't it just pushed to master-branch?

**Comment by moroshko** [comment]
@DERIIIFranz I didn't say it's simple ;) We already have `componentWillReceiveProps()` in the `2.0` branch which will be released soon. At the moment, it allows you to update input's value on the fly. You are more than welcome to submit a Pull Request (to the `2.0` branch) that allows to update `suggestions`.

**Comment by moroshko** [comment]
@DERIIIFranz Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save
