### ISSUE TITLE
Suggestions dropdown reopens when clicking anywhere in document after a suggestion was selected

### ISSUE THREAD

**Issue by MaciekFulara** [moroshko/react-autosuggest#575]
Steps to reproduce:
  1. Focus on the input field.
  2. Type anything, and wait for suggestions to appear.
  3. Select one of the suggestions.
  4. Click anywhere in the document.

  **Observed behaviour:** Suggestions dropdown reopens.

  **Expected behaviour:** Suggestions should stay closed or there should be an option to disable reopening suggestions dropdown in this case.

**Comment by dannycochran** [comment]
Seeing this as of 9.4.1.

**Comment by marcoromag** [comment]
yes, I've noticed the same. Actually this happens because somehow the focus gets back on the input field, making this behaviour.
The root cause appears to be with the focus...

**Comment by marcoromag** [comment]
I just tested on master, and it is also fixed with commit  72c6824
Therefore, it will be in the next tag (hoping it will be released soon :) )

**Comment by pobidowski** [comment]
We got the same problem. Waiting on next tag.

**Comment by moroshko** [comment]
v9.4.2 that fixes it is on npm now.
