### ISSUE TITLE
No Results feedback

### ISSUE THREAD

**Issue by DERIIIFranz** [moroshko/react-autosuggest#58]
It would be nice being able to give the user feedback in case there's no result found.

**Comment by moroshko** [comment]
@DERIIIFranz I just released react-autosuggest 2.0 which supports a controlled behaviour. You

**Comment by moroshko** [comment]
This will be possible in 3.0. Check out the 3.0 branch for work in progress, if interested.

**Comment by moroshko** [comment]
@DERIIIFranz  Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save

**Comment by hughlomas** [comment]
@moroshko Heya, is this possible yet? I am using 3.0.0.

**Comment by moroshko** [comment]
@hughlomas It's not built-in, but you can easily [implement this yourself](http://codepen.io/moroshko/pen/wMRmmM).

**Comment by hughlomas** [comment]
@moroshko Thank you for the example, that worked nicely.
