### ISSUE TITLE
onChange not fired when user presses Enter

### ISSUE THREAD

**Issue by hillc5** [moroshko/react-autosuggest#584]
### Description
when a user types a suggestion, highlights an option with up/down keys, then presses enter, the selection should trigger the onChange method in the inputProps object, as referenced here: https://www.npmjs.com/package/react-autosuggest#inputpropsonchange-required

### Reproduction Steps
  1. Open Dev Tools on Codepen
  2. Type `c`, and wait for suggestions to appear
  3. Press <kbd>Down</kbd> to highlight selection
  4. Preass <kbd>Enter</dbd> to select

  **Observed behaviour:**  Nothing happens and nothing logs to the console

  **Expected behaviour:** onChange should be called and 'enter' should be logged to the console

**Comment by moroshko** [comment]
`onChange` is called only when the input value changes.
In your repro, the input value changes when you press Down, but not when you press Enter.

It will be called with `method === "enter"` if you hover a suggestion with a mouse (this doesn't change the input value), and then press Enter.

You might want to use [`onSuggestionSelected`](https://github.com/moroshko/react-autosuggest#onSuggestionSelectedProp).
