### ISSUE TITLE
Prevent values that are not from suggestions

### ISSUE THREAD

**Issue by jmachnik** [moroshko/react-autosuggest#599]
In my application when user is entering something into input I want to prevent getting value that is not a selected suggestion. I wonder if that is possible without implementing custom input element? 

This functionality can be described as allowSuggestionsOnly or something like this. It's from preventing . 

Is there a possibility to distinct if value in input came from user's input or suggestion selection?

**Comment by sabbin** [comment]
I'm looking for the same functionality is it implemented in any way?

**Comment by moroshko** [comment]
What you are describing sounds more like a select component, not autosuggest.
Have a look at [react-select](https://github.com/JedWatson/react-select).
