### ISSUE TITLE
How import another component with a company list?

### ISSUE THREAD

**Issue by zjoin** [moroshko/react-autosuggest#60]
I have a company list:
import CompanyList from 'Company/List/CompanyList';

import css from './SearchField.styl';
import React, { Component } from 'react';

import Svgo from 'Element/Svgo/ElementSvgo';
import CN from 'classnames';
import Select from 'react-select';
import CompanyList from 'Company/List/CompanyList';
import Autosuggest from 'react-autosuggest';

const suburbs = ['Cheltenham', 'Mill Park', 'Mordialloc', 'Nunawading'];
import { getCompanies } from 'actions/CompanyActions';

import CompanyPanel from 'Company/Panel/CompanyPanel';

export default class SearchInput extends Component {

  render() {

    function getSuggestions(input, callback) {
      const regex = new RegExp('^' + input, 'i');
      const suggestions = suburbs.filter(suburb => regex.test(suburb));

        setTimeout(() => callback(null, suggestions), 300); // Emulate API call
}

    return (

      <div className={CN(css.selectLive)}>
        <Autosuggest suggestions={getSuggestions} />
      </div>
    );
  }
};

**Comment by moroshko** [comment]
Sorry, I don't understand the question. Can you explain what the issue is?
