### ISSUE TITLE
programatically setting the autosuggest input value won't update and show the suggestions

### ISSUE THREAD

**Issue by JackLeiLing** [moroshko/react-autosuggest#626]
## programatically setting the autosuggest input value won't update and show the suggestions

* background 
  I have a user case where the autosuggest input value needs to be changed programmatically such as on a button click. Looks like the onSuggestionsFetchRequested is not called if the input value is set programmatically. 

* Codepen https://codepen.io/anon/pen/ywqgxo?editors=0011

* The steps to reproduce the issue, e.g.:
  1. click one of the buttons on top of the input
  2. the input value updates accordingly but the suggestions are not showing up
  3. click in to the input, the suggestions show up. 

  **Observed behaviour:** Suggestions not showing up on input value change

  **Expected behaviour:** Suggestions should automatically show without clicking into the input after the input value change.

Any suggestion/solution for this issue is appreciated.

**Comment by andribo** [comment]
@JackLeiLing You can manually set a focus on the input.
In your code-example just replace the 141 line with the following:
```js
onClick={()=>this.setState({value:"c"}, () => this.input.focus())} 
```

**Comment by JackLeiLing** [comment]
@andribo , many thanks for your solution! it is working like a charm. I did try this.input.focus() as 
`onClick={()=>{
this.setState({value:"c"};
this.input.focus()
}} `
Obviously, I forgot setState's asynchronous nature. 
Once again, thank you!
