### ISSUE TITLE
focus autosuggest input programmatically using ref?

### ISSUE THREAD

**Issue by eldyvoon** [moroshko/react-autosuggest#629]
I have this Wrapper component
```
<Autosuggest
  getInputValue={this.getInputValue}
  placeholder={placeholder}
  inputRef={this.props.inputRef}
/>
```
and I have parent a component that does createRef() and pass in inputRef as props to above Wrapper, I thought I can do this.inputRef.current.focus() in the parent component but I seems can't target the input ref of Autosuggest this way.

Any clue?

**Comment by eldyvoon** [comment]
meanwhile, I'm passing a flag from props then pass it to inputProps, it worked.

```
<Autosuggest
  inputProps={autoFocus: this.props.autoFocusInput}
/>
```

**Comment by LuisSaybe** [comment]
is there no way to pass a ref using `useRef()` to the input component returned by renderInputComponent via inputProps ?

**Comment by aberezkin** [comment]
Now you can pass `ref` in `inputProps`. Update to v10.0.1
