### ISSUE TITLE
Double space adds a "." (period) to the value of the texbox.

### ISSUE THREAD

**Issue by jgarcia77** [moroshko/react-autosuggest#635]
If you quickly hit the space bar twice (for double space), the component adds a period to the value of the textbox.

![image](https://user-images.githubusercontent.com/7825380/57002352-6708dd00-6b84-11e9-89a0-abdc87e9e007.png)

**Comment by moroshko** [comment]
What device are you experiencing this on?
Isn't this a feature of the device keyboard?

**Comment by jgarcia77** [comment]
I am using a Mac and you are correct it is a keyboard setting that I just disabled and your component works like a charm.  I really love this component and the client I am working with is extremely happy.

**Comment by moroshko** [comment]
Glad to hear that!
Closing this issue.
