### ISSUE TITLE
How to get section title for each suggestion item? (React Autosuggest Multiple Section)

### ISSUE THREAD

**Issue by saddamhbb** [moroshko/react-autosuggest#660]
In my application I am using **Multiple Section Autosuggest**, I'd like to get section title in **renderSuggestion** function, How can I achieve that? 

I am using this shape of data:

```
const languages = [
  {
    title: '1970s',
    languages: [
      {
        name: 'C',
        year: 1972
      }
    ]
  },
  {
    title: '1980s',
    languages: [
      {
        name: 'C++',
        year: 1983
      },
    ]
  },
  {
    title: '2010s',
    languages: [
      {
        name: 'Elm',
        year: 2012
      }
    ]
  }
];

```

**Comment by DisplacedTexan** [comment]
This [codepen](https://codepen.io/moroshko/pen/qbRNjV) shows how to use multiple sections. You'll need to use `renderSectionTitle` as well.
