### ISSUE TITLE
need cursor position to generate suggestions

### ISSUE THREAD

**Issue by acthp** [moroshko/react-autosuggest#67]
For multi-word inputs the cursor position is necessary for generating the list of suggestions. This might be accomplished by passing it in the suggestions callback, by passing the ref for the input element, or by exposing the refs on the AutoSuggest class so the caller can inspect the cursor position.

**Comment by moroshko** [comment]
@acthp The input element has `ref="input"`, so you should be able to access the input like that:

    <Autosuggest ref="autosuggest" ... />

and then:

    this.refs.autosuggest.refs.input
