### ISSUE TITLE
Prevent selecting to update the input value

### ISSUE THREAD

**Issue by angrybacon** [moroshko/react-autosuggest#671]
I'm using `react-autosuggest` to fetch suggestions from an API based on user's input. Ideally I would have `input` keep track of the input value, that is updated whenever the user types. And `query` should be the value to debounce upon and to trigger the API call.

The below implementation partially works in that `onChange` is fired when selecting a suggestion candidate with the keyboard as well. How can I prevent this behavior?

The goal for me is to have the suggestions fetched from the API 500ms after the user is done typing, but not when the user browses the results with the keyboard.

```jsx
import { useDebounce } from 'react-use';
import api from '../path/to/my/api/bindings';


export default function Search() {

  const [ query, setQuery ] = React.useState('');
  const [ input, setInput ] = React.useState('');
  const [ suggestions, setSuggestions ] = React.useState([]);
  const [ thinking, setThinking ] = React.useState(false);

  const onChange = (event, { newValue }) => {
    setThinking(true);
    setInput(newValue);
    setQuery(newValue);
  };

  const onReset = () => {
    setSuggestions([]);
    setThinking(false);
  };

  const search = value => {
    if (value) {
      setThinking(true);
      api.search(value).then(response => {
        setSuggestions(response);
        setThinking(false);
      });
    }
  };

  const inputProps = {
    autoFocus: true,
    onChange,
    value: input,
  };

  useDebounce(() => search(query), 500, [query]);

  return (
    <Autosuggest
      getSuggestionValue={it => it.name}
      inputProps={inputProps}
      onSuggestionsClearRequested={onReset}
      onSuggestionsFetchRequested={() => {}}
      suggestions={suggestions}
    />
  );
}
```

**Comment by dsaw** [comment]
Hi @angrybacon , from the implementation it might be advisable to move the debounced function to `onSuggestionsFetchRequested` and try checking after that. (can refer to [https://codepen.io/devsaw/pen/wvMWWNm](https://codepen.io/devsaw/pen/wvMWWNm)). `onSuggestionsFetchRequested` will be fired some event happens like event focus, key strokes etc. You can add any filtering logic if needed in that.

**Comment by angrybacon** [comment]
@dsaw Sorry for not getting back to you sooner! My code has changed a little, enough that I can't reproduce the misbehaviour I was facing at the time. I'll keep that issue bookmarked just in case though. Thanks :-)
