### ISSUE TITLE
Add touch support for mobile devices

### ISSUE THREAD

**Issue by moroshko** [moroshko/react-autosuggest#68]
See: 602ebeedd4fe29a6f6c2c5c3c68d75ff749a17e1

**Comment by nitelite** [comment]
I suspect this bug might explain the problem I am having with iOS devices. When I click / press one of the suggestions, the suggestions list disappears, but the proper event for onSelectionClicked doesn't fire. Does this match the behavior you are seeing ?

**Comment by moroshko** [comment]
@nitelite Yeah, I think it's the same. Should be fixed now in 2.1.0. Let me know if you still experience issues.

**Comment by nitelite** [comment]
Just wanted to add that upgrading to 2.1.0 fixed the issue for me. Thanks alot. I can now switch over from the old hacked together jquery thing on your website to the new react-based component. Oh, the joy :D
