### ISSUE TITLE
It seems that autosuggestion doesn't work with another language other than English

### ISSUE THREAD

**Issue by venix** [moroshko/react-autosuggest#692]
I am loading data for autosuggestion and works perfectly with English, but when the data are in another language autosuggestion while typing doesn't work. Am I doing something wrong?

**Comment by fantonangeli** [comment]
Will you please give us a code example to test? 
A Codepen like [this](https://codepen.io/moroshko/pen/LGNJMy) would be much better.
What browser are you using?

**Comment by forvenus** [comment]
New to react-autosuggest, good job!
Tried Chinese, and works fine.
![image](https://user-images.githubusercontent.com/7394636/69507551-e8371f80-0f6d-11ea-8da4-76f6879a167d.png)

**Comment by venix** [comment]
Hi sorry for the delay. 

If the response from the API is like this? What am I doing wrong when I load the data? 

`{name": "\u03a3\u03a4\u0391\u03a5\u03a1\u039f\u03a3 \u03a7\u0391\u03a1\u0391\u039b\u0391\u039c\u03a0\u039f\u03a5\u03a3 ", other: "data"}`

Is this a API response problem or is this how is supposed to be returned and I have to decode it in the front-end? 

Thanks, 
Michael

**Comment by venix** [comment]
> New to react-autosuggest, good job!
> Tried Chinese, and works fine.
> ![image](https://user-images.githubusercontent.com/7394636/69507551-e8371f80-0f6d-11ea-8da4-76f6879a167d.png)

Works yes like this, but not when I load the data from the API response which is as my comment above.

**Comment by venix** [comment]
Resolved, it seems that I was using the regex wrongly when I was getting the suggestions and I had to also include the unicode characters for the languages I need. 
`const regex = new RegExp('[\u0370-\u03FF]*' + escapedValue, 'i');`

**Comment by venix** [comment]
Resolved, it seems that I was using the regex wrongly when I was getting the suggestions and I had to also include the unicode characters for the languages I need. 
`const regex = new RegExp('[\u0370-\u03FF]*' + escapedValue, 'i');`
