### ISSUE TITLE
ignore comma in highlighting

### ISSUE THREAD

**Issue by thian4** [moroshko/react-autosuggest#693]
## Are you reporting a bug?
No It's not a bug, I'm facing an issue. If the name has comma, how can I ignore the comma and still let it match when the user didn't type in the comma?
https://codepen.io/eldyvoon/pen/KKwPPoK

If I type ```C, C++``` it matched but it's not coming when I type ```C C++```

**Comment by aberezkin** [comment]
Implement a `fuzzy-search` algorithm in your `onSuggestionsFetchRequested` callback.
