### ISSUE TITLE
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by SMaverick78** [moroshko/react-autosuggest#695]
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Autosuggest, Autowhatever.
Could you please update the component according to this message in console.log.

**Comment by ronaklalwaniii** [comment]
Yeah, Please merge this [pull request](https://github.com/moroshko/react-autosuggest/pull/681#issue-328009006) ASAP.

**Comment by SMaverick78** [comment]
Я попросил сделать это в пакете react-autosuggest. У меня доступов к исходникам пакета  react-autosuggest нету.

**Comment by SMaverick78** [comment]
I looked at pull request. These are the changes that are needed. And I don't need to add pull request. Thanks for the quick response. I will wait for the package update

**Comment by SMaverick78** [comment]
I see the thread has merge in master. And when will the changes appear in the package?

**Comment by YuriMB** [comment]
Note: **This breaks react <16.3 support.**

**Comment by danbergelt** [comment]
+1 also waiting on updated package.

**Comment by ronaklalwaniii** [comment]
+1

**Comment by bliitzkrieg** [comment]
+1

**Comment by webdev24** [comment]
+1

**Comment by a-x-** [comment]
Is react-autosuggest dead?

**Comment by aberezkin** [comment]
Fixed in #681
