### ISSUE TITLE
How can I disable rendersuggestion? 

### ISSUE THREAD

**Issue by Prottoy2938** [moroshko/react-autosuggest#704]
renderSuggestion in Autosuggestion is breaking the styling of my page. How do I disable it?
It's adding a bullet like a li. It seems like renderSuggestion has a parent ul.

I saved the data in my state and I would be using it in another component.
So is there any way that I can disable renderSuggestion? Or display nothing?

**Comment by aberezkin** [comment]
Don't quite understand what are you trying to do. Can you please clarify?

**Comment by Prottoy2938** [comment]
You are 3 months late. I'm sorry, but I have completely forgot why did I open this issue. The only thing I remember, I used this package for [outline](https://prottoy2938.github.io/) project.
