### ISSUE TITLE
Making Async Autosuggest controlled by parent components breaks things

### ISSUE THREAD

**Issue by MutatedGamer** [moroshko/react-autosuggest#705]
In my project I pass a value and onChange to a wrapper around an async Autosuggest. I observed when clicking a suggestion I get weird errors and my app crashes. The error I am getting is different from the one in [my codepen](https://codepen.io/mutatedgamer/pen/povpRoR), but I suspect they're related.

You can reproduce this simply by typing anything into the input and then clicking on any suggestion. Errors get logged in the console and the input doesn't respond.

Am I doing something wrong?

**Comment by johollmann** [comment]
same issue here, have you found a solution?

**Comment by aberezkin** [comment]
Can you please clarify which errors you get and give detailed explanation of what are you trying to do with code examples?

**Comment by aberezkin** [comment]
Closing as stale
