### ISSUE TITLE
Please tag 9.4.4

### ISSUE THREAD

**Issue by deanc** [moroshko/react-autosuggest#707]
Hey @moroshko could you tag the latest commit so we can reliably upgrade to it :)

**Comment by deanc** [comment]
I'm not quite sure why, but even pointing directly to this commit results in the library not being available:

`yarn add https://github.com/moroshko/react-autosuggest.git#4490f98ad41e7b3d386ba3541fc0394a509404e5`

And then when running:

`Can't resolve 'react-autosuggest' in '/path/to/src/components/forms'`

I presume it's related to the bundling that happens when publishing a new version :)

**Comment by webdev24** [comment]
+1

**Comment by jChris85** [comment]
Also the UNSAFE renaming changes would be nice to have as a new tag.

+1

**Comment by deanc** [comment]
> Also the UNSAFE renaming changes would be nice to have as a new tag.
> 
> +1

They are part of the latest changes on master. If master is now tagged, and built properly you will be able to get rid of the warnings (until the methods are officially deprecated).

**Comment by bgoerdt** [comment]
This project needs a maintainer: https://twitter.com/kopseng/status/1201491459930763265
I doubt anything will happen until someone picks it up.

**Comment by johollmann** [comment]
+1

**Comment by aberezkin** [comment]
You can upgrade to `v10.0.0` now
