### ISSUE TITLE
passing suggestions directly into Autosuggest? 

### ISSUE THREAD

**Issue by matthewmueller** [moroshko/react-autosuggest#71]
Is it possible to do something like this:

```js
<Autosuggest suggestions={["a", "b", "c"]} />
```

this is helpful for systems like redux, where the suggestions would be in a store

**Comment by ksmth** [comment]
@matthewmueller:
As a temporary fix:
```
class ControlledAutosuggest extends Autosuggest {
  componentWillReceiveProps(props: Object) {
    super.componentWillReceiveProps(props);
    this.showSuggestions(props.value || '', props.suggestions);
  }
  showSuggestions(input, suggestions) {
    if (!this.props.showWhen(input)) {
      this.setSuggestionsState(null);
    } else {
      this.setSuggestionsState(suggestions || this.props.suggestions);
    }
  }
}

ControlledAutosuggest.propTypes = {
  ...Autosuggest.propTypes,
  suggestions : PropTypes.array
};
```

**Comment by moroshko** [comment]
@matthewmueller I'm rebuilding react-autosuggest at the moment to support flux architectures including redux. Check out this [redux example](https://github.com/moroshko/react-autosuggest/blob/3.0/demo/src/components/App/components/Example1/Example1.js#L81). You are more than welcome to contribute to the design of the new API.

@ksmth Thanks for the suggested workaround.

**Comment by moroshko** [comment]
As I mentioned above, flux architecture will be supported in 3.0.

**Comment by moroshko** [comment]
@matthewmueller @ksmth Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save
