### ISSUE TITLE
Module build failed when run build command 

### ISSUE THREAD

**Issue by dizefurkan** [moroshko/react-autosuggest#712]
## Are you reporting a bug?
I think yes. Cause i didn't change anything. I just install the npm packages then run build command.

* Provide the steps to reproduce the issue, e.g.:
  1. Clone the repo
  2. Install the npm packages with npm or yarn
  3. Run build command (npm run build _or_ yarn run build)

![Screen Shot 2020-01-13 at 16 32 05](https://user-images.githubusercontent.com/28892291/72260198-608f9800-3623-11ea-8a58-5a2bfd27ee7a.png)

  **Observed behaviour:** Build failed
  **Expected behaviour:** Build should be succesfull

npm version: 6.13.4 || yarn version: 1.21.1
node version 10.18.0

Hello,
The problem is when i clone the repo than install the npm packages and run build command it's crash when build step. I don't know what is wrong with it. By the way i need clone the repo because of the react-whatever package version. I need to fix it. Cause it will crash our production app (cause of react lifecycle method renaming...)

Thanks for help...

**Comment by dizefurkan** [comment]
Hello, i don't understand the problem.
Does anybody clone the repo than install the npm packages with (npm install or yarn install) and then run build command (npm run build or yarn run build) without any problem?
![Screen Shot 2020-01-22 at 13 53 19](https://user-images.githubusercontent.com/28892291/72889378-9d911400-3d20-11ea-8995-4223c118f82e.png)

**Comment by aberezkin** [comment]
Fixed.
