### ISSUE TITLE
How to manually focus a child textarea element

### ISSUE THREAD

**Issue by angrybacon** [moroshko/react-autosuggest#713]
https://codesandbox.io/s/elegant-moore-5igmb

1. Click the "Focus" button

**Observed behaviour:** Textarea element is not focused

**Expected behaviour:** Textarea should be focused

I'm not sure the issue is about me misusing refs or `Autowhatever` not passing down the ref property.

**Comment by angrybacon** [comment]
Looking closer at `react-autowhatever` code I just noticed that `ref` is always overwritten here: https://github.com/moroshko/react-autowhatever/blob/master/src/Autowhatever.js#L323-L341

But I fail to see how to make use of `storeInputReference`. Is this by design?
I could create an issue over `react-autowhatever` instead if you prefer :-)

**Comment by aberezkin** [comment]
Yeah, this is a problem. There's a PR to `react-autowhatever` that solves that https://github.com/moroshko/react-autowhatever/pull/46. I'm planning on merging `react-autowhatever` in this repo soon and make it possible to pass your own ref to the input.

**Comment by aberezkin** [comment]
Done (#736). You can pass ref in inputProps now. Update to v10.0.1.
