### ISSUE TITLE
Suggestion container does not open until pressing Down button

### ISSUE THREAD

**Issue by platico** [moroshko/react-autosuggest#718]
I am implementing the Basic functionality of the Autosuggest and I am fetching data from an external API using `onSuggestionsFetchRequested`. The results are fetched but the container with the suggestions does not open until the <kbd>Down</kbd> button is pressed. What am I doing wrong?

* Please create a Codepen that demonstrates your issue. You can start from the [Basic example](http://codepen.io/moroshko/pen/LGNJMy).

https://codepen.io/platico/pen/yLNYbGy?editors=1111

* Provide the steps to reproduce the issue, e.g.:
  1. Type a number (eg. 1)
  2. Press <kbd>Down button</kbd>

  **Observed behaviour:** The suggestions container does not open after results are fetched

  **Expected behaviour:** The suggestions container **should be opened** after results are fetched

**Comment by Kishore-p-98** [comment]
axios call is an asynchronous, you have to set the state only after the call is resolved. Add **async** and **await** in the function. It is not an issue with the onSuggestionsFetchRequested.
```
onSuggestionsFetchRequested = async ({ value }) => {
       // your setup

        await axios.get(url)
            .then(function (response) {
                         // form your array
                        });
                });

            })
            .catch(function (error) {
            });

        this.setState({
            suggestions: rooms
        });    
  };
```
