### ISSUE TITLE
useState error in renderInputComponent

### ISSUE THREAD

**Issue by hosein74** [moroshko/react-autosuggest#721]
when use useState in the renderInputComponent show this error:

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**Comment by aberezkin** [comment]
This error is not about `react-autosuggest`. Please read [rules of hooks](https://reactjs.org/docs/hooks-rules.html).
