### ISSUE TITLE
onChange callback when enter can not get enter method.

### ISSUE THREAD

**Issue by hieusmiths** [moroshko/react-autosuggest#722]
## Are you reporting a bug?

* Provide the steps to reproduce the issue, e.g.:
  1. Input value
  2. Type `c`, and wait for suggestions to appear
  3. Press <kbd>Enter</kbd>
  4. onChange function can't return Enter when enter pressed.

  Thank so much

**Comment by matrix4123** [comment]
I am seeing this as well.

**Comment by hieusmiths** [comment]
> I am seeing this as well.
Can you check it at right for me.

https://codepen.io/moroshko/pen/LGNJMy?editors=1111

At onChange function i print method but not run.
I want enter and go to get event is Enter and call API.

Thank so much

**Comment by eliasturbay** [comment]
Yes @hieusmiths, I'm facing the same issue. Any clue on this @moroshko ?
Thanks in advance!

**Comment by eliasturbay** [comment]
@moroshko I found your comment here regarding this issue: https://github.com/moroshko/react-autosuggest/issues/584

If that's the case, then the documentation is wrong:

https://github.com/moroshko/react-autosuggest/blob/master/README.md#inputpropsonchange-required

> method - string describing how the change has occurred. The possible values are:
> 'down' - user pressed Down
> 'up' - user pressed Up
> 'escape' - user pressed Escape
> 'enter' - user pressed Enter

**Comment by aberezkin** [comment]
`onChange` called only when value actually changes. There's no value change after pressing `enter` so `onChange` not even called. (see https://github.com/moroshko/react-autosuggest/issues/584#issuecomment-429118487)

@eliasturbay, documentation is correct you can change value by pressing `enter` if you selected it before (for example by hovering a suggestion).
