### ISSUE TITLE
How to sparator bettween enter text plain and enter when select item suggestion.

### ISSUE THREAD

**Issue by hieusmiths** [moroshko/react-autosuggest#725]
1. Focus on the input field
  2. I'm type C then i wana call API when user Enter.
  3. I'm type C then i select item by type Enter.
  4. I don't want when Enter item will run 2 action same the time.

Thank so much <3

**Comment by aberezkin** [comment]
Can you please clarify with code examples?

**Comment by aberezkin** [comment]
Closing as stale
