### ISSUE TITLE
New release for npm

### ISSUE THREAD

**Issue by mikaelhalen** [moroshko/react-autosuggest#731]
I see that there have been a bunch of updates to this package lately but no npm releases. Would it be possible for a new version to be released soon?

**Comment by aberezkin** [comment]
Yes. There's a plan to release a new version soon. Maybe this week. See https://github.com/moroshko/react-autosuggest/issues/672#issuecomment-599450516

**Comment by mikaelhalen** [comment]
Frickin' awesome! Thank you for the swift reply!

**Comment by akaSybe** [comment]
Waiting for this too

**Comment by aberezkin** [comment]
done
