### ISSUE TITLE
Doesn't work with the latest React version

### ISSUE THREAD

**Issue by emorozov** [moroshko/react-autosuggest#74]
Hello,
I've upgraded react to 0.14.0 and react-autosuggest  to 2.1.0. Now my application spews exceptions to the debug console:
```
Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.
You might be adding a ref to a component that was not created inside a component's `render` 
method, or you have multiple copies of React loaded
(details: https://fb.me/react-refs-must-have-owner).
```

**Comment by moroshko** [comment]
@emorozov Are you sure you don't have multiple copies of React loaded? I cannot see this error in the when running the examples (`npm start`). Can you provide a repo that demonstrates the issue?

**Comment by emorozov** [comment]
I'm a novice in JS/React/Nuclear development, and my setup is very peculiar. It would be hard to create a small reproducible repo, because it's a huge Django/React-Nuclear project that is slowly migrating from traditional architecture to React/Nuclear.

Here's the code I use:
```
export default Radium(React.createClass({
  render() {
    return (
      <div style={[styles.base]}>
        <form>
          <select name="scope" style={[styles.scope]}>
            <option name="all">All</option>
            <option name="my-lessons">My Lessons</option>
            <option name="my-imports">My Imports</option>
            <option name="my-archives">My Archives</option>
          </select>
          <Autosuggest suggestions={getSuggestions}
                       suggestionRenderer={renderSuggestion}
                       suggestionValue={suggestion => suggestion.title}
                       onSuggestionSelected={(suggestion, event) => history.replaceState(null, '/lesson/456/w/1')}
                       inputAttributes={{placeholder: "Search"}}
          />
        </form>
        <div style={[styles.clear]}></div>
      </div>
    )
  }
}))
```

If this doesn't help, I'll try to create a small repoducible example as a separate project. And no, there's no multiple copies of React in the output of `npm ls`.

**Comment by antonklava** [comment]
I had the same error and was running multiple `react` copies. Make sure that you only have a single entry for react when you run `npm ls`. Reinstalling node modules fixed it for me.

**Comment by moroshko** [comment]
@emorozov Does deleting and reinstalling node_modules help? If not, please recreate a minimal reproducible example.

**Comment by emorozov** [comment]
@moroshko You can close the issue, it was a configuration error on our side that was indeed causing duplicate instances of React loaded. Sorry I didn't say that earlier.

**Comment by sheltonial** [comment]
@emorozov what was your configuration error? I'm trying to figure out a solution to this one and currently stuck.

**Comment by sheltonial** [comment]
My issue ended up being around using `npm prune --production`. https://github.com/npm/npm/issues/10442

**Comment by rdubrock** [comment]
If anyone is using jspm and runs into this issue, I fixed it using `jspm resolve --only npm:react@[versionnumber]`
