### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by loopmode** [moroshko/react-autosuggest#77]
Sometimes, mostly when there is no input :), I get an error in the showSuggestions() method:

    Uncaught TypeError: Cannot read property 'toLowerCase' of null
    showSuggestions @     bundle.js:42954
    onInputFocus @   bundle.js:43241
    ReactErrorUtils.invokeGuardedCallback 
    ...

Which is this line:

    var cacheKey = input.toLowerCase();

Mmaybe a simple check á la `(input && input.toLowerCase()) || ''` will do. Or bailing out early. However, I do not fully understand the cause, so the suggestion might be just a workaround and not a solution.

**Comment by moroshko** [comment]
@loopmode I don't want to put hacks without understanding the root cause. Please share a reproducible example, if you can.

**Comment by loopmode** [comment]
Totally agree! Will investigate further on.

**Comment by loopmode** [comment]
Okay, this is a non-issue. It is related to webpack hot reloading, stuff gets replaced behind the back of react-autosuggest.

**Comment by apatel-gpsw** [comment]
If _input_ is a string, try this:
var cacheKey = input.toString().toLowerCase();

**Comment by loopmode** [comment]
Hehe, well that wouldn't help much if Input was `null` instead of a string, and it wouldn't be neccessary if it was a string :)

**Comment by loopmode** [comment]
@x5engine I'm really sorry but I really don't remember.. it's many projects and several employers ago...
