### ISSUE TITLE
Bug | If suggestions property is undefined, willRenderSuggestions errors out

### ISSUE THREAD

**Issue by travisbashor** [moroshko/react-autosuggest#777]
https://github.com/moroshko/react-autosuggest/blob/f42a549c5b380740a6b8a45d00a4501a13e6f768/src/Autosuggest.js#L347

Suggest falsy checking in a guard clause.

**Comment by pimterry** [comment]
Ah, but `suggestions` must not be undefined. There's more info in [the docs](https://github.com/moroshko/react-autosuggest#suggestions-prop): it's a required parameter and it should always be an array. If you'd like to show no suggestions, it should be an empty array.

There's an argument though that we should validate this, and error earlier and more clearly. I'd happily accept a PR to do so if you're interested? Either way, I'm going to close this for now, this is (more or less) correct behaviour.
