### ISSUE TITLE
Dropdown closes when attempting to scroll (IE11)

### ISSUE THREAD

**Issue by jlc467** [moroshko/react-autosuggest#78]
Using this example: http://moroshko.github.io/react-autosuggest/#Custom%20renderer

With IE11 browser, try to scroll results. It will close the dropdown.

For some reason clicking scroll bar triggers blur event.

**Comment by moroshko** [comment]
@jlc467 Thanks for submitting the issue, and sorry for getting back to you only now. I was busy with the 3.0 release, which comes with the brand new website. I assume we can close this issue.

http://react-autosuggest.js.org/
