### ISSUE TITLE
Auto suggest not working in mobile

### ISSUE THREAD

**Issue by phuongmn** [moroshko/react-autosuggest#79]
Hi friend.
I have problem with your plugin when using standalone mode.
Your plugin work well at my desktop but in mobile not rendering textbox for enter.
No have idea. Please let me know  if you know where i wrong.
Great work
Thanks,

**Comment by moroshko** [comment]
@phuongmn Could you please provide a repo that demonstrates the issue?

**Comment by phuongmn** [comment]
Oops... Thank you for soon answer, i was miss added react dom when depoy to my server, all work well now,
sorry for the inconvenience.
Great support.
Thanks.
