### ISSUE TITLE
Passing the additional elements to <Autosuggest /> and wrapping it content to another

### ISSUE THREAD

**Issue by newsiberian** [moroshko/react-autosuggest#82]
Hello @moroshko, thanks for the great package.

I'm working with Semantic UI, and I need to implement something like [this](http://semantic-ui.com/modules/search.html) with additional "search icon" or maybe a "loading icon". To achieve this I need to repeat the following structure:
```
[1]<div class="ui search">
[2]  <div class="ui icon input">
[3]    <input class="prompt" placeholder="Common passwords..." type="text">
[4]    <i class="search icon"></i>
[5]  </div>
[6]  <div class="results"></div>
[7]</div>
```
As you can see here, seems the is no way now to wrap input in div [2, 5] and pass the \<i>[4] element to it. Or maybe there is a way to do it?

**Comment by moroshko** [comment]
@newsiberian Sorry, there is no easy way to do this. You could probably try and dynamically add the missing elements, but I think it would make more sense to clone the repo and modify it to your needs. Can I ask why would you like to use react-autosuggest and not the Search component provided by Semantic UI?

**Comment by newsiberian** [comment]
Because, I'm avoiding JQuery in project. Ok, anyway, thanks for a fast response:)
