### ISSUE TITLE
Do not close Suggestion when button/icon click

### ISSUE THREAD

**Issue by monski** [moroshko/react-autosuggest#832]
Hi guys, just wanted some help.

is there a way i can make it like, when i click the button on my custom render suggestion.. the suggestion should not close, and just remove it from list.

* Provide the steps to reproduce the issue, e.g.:
  1. Focus on the input field
  2. Type `test`, and wait for suggestions to appear
  3. click on the button icon (left side)

  **Observed behaviour:** Suggestions  closed

  **Expected behaviour:** Suggestions stay open

sample image

![Screen Shot 2021-10-23 at 4 01 34 PM](https://user-images.githubusercontent.com/2107437/138548219-e868d746-de0b-4c10-b853-da53136ce1d9.png)

thanks in advance

**Comment by harvey56** [comment]
@monski can you please elaborate how you did this ? With a codepen link for example if you don't mind. I'm trying to build the same thing as on your screenshot
