### ISSUE TITLE
Override state value

### ISSUE THREAD

**Issue by jadonald72** [moroshko/react-autosuggest#85]
I have added value={this.state.autosuggestValue} to the autosuggest control.  I thought that this would allow me to set and change the state of the control, however it does not let me do this. When I set the initial state using getInitialState() I can call it outside the autosuggest control like {this.state.autosuggestValue} and it displays fine, but it does not set the value of the autosuggest control.  Can anyone help with this?

**Comment by web2style** [comment]
Same question.

**Comment by moroshko** [comment]
Have you checked out the [Controlled Component example](https://github.com/moroshko/react-autosuggest/blob/master/examples/src/ControlledComponent/ControlledComponent.js)? Can you share some code/gist that demonstrates the issue?

**Comment by web2style** [comment]
@moroshko I described my question in detail here: https://github.com/moroshko/react-autosuggest/issues/84#issuecomment-154967347
