### ISSUE TITLE
No way to "pass by value" for suggestions list

### ISSUE THREAD

**Issue by idolize** [moroshko/react-autosuggest#88]
The current implementation has a requirement that the suggestions come from a function with a callback.

This approach works fine if you want to do your AJAX call inside your component, but if you want to just simply pass through a list of suggestions (which are being fetched outside of the function - such as in a Flux application architecture) then it is very difficult.

My first instinct was to simply write a "no-op" type of function to pass through data via a closure. Something like this:

```js
const { options } = this.props;
const { value } = this.state;
return (
  <Autosuggest
      suggestions={(input, callback) => {
        // Load the new suggestions via Flux action
        loadSuggestions(input);
        // Pass through options via closure
        return callback(null, options);
      }}
      value={value} />
);
```

This didn't work, but I thought perhaps it was due to the closure hanging on to the old reference, so I tried this:

```js
const { options } = this.props;
const { value } = this.state;
return (
  <Autosuggest
      suggestions={(opts => (input, callback) => {
        // Load the new suggestions via Flux action
        loadSuggestions(input);
        // Pass through options via closure
        return callback(null, opts);
      })(options)}
      value={value} />
);
```

But still showing the old results. :cry: 

Then, I realized the problem is [this line here](https://github.com/moroshko/react-autosuggest/blob/master/src/Autosuggest.js#L63). `this.suggestionsFn` only ever points to the initial function passed in, and thus when `props.suggestions` changes to a different function, the `<Autosuggest>` instance completely ignores it and continues to use the old function, which is bound to the old value.

**Comment by moroshko** [comment]
@idolize You are right. At the moment, we don't have good support for flux architecture. But, I already started to work on exactly that! Have a look at the [3.0 branch](https://github.com/moroshko/react-autosuggest/tree/3.0). It is a complete rewrite of react-autosuggest, which has a flux support out of the box. Check out [the redux examples](https://github.com/moroshko/react-autosuggest/tree/3.0/demo/src/components/App/components). It would be great to get your feedback on the API, or if you are keen to help to push 3.0 forward you are more than welcome!

**Comment by idolize** [comment]
Awesome. @moroshko you are always one step ahead :stuck_out_tongue_winking_eye:

**Comment by moroshko** [comment]
@idolize Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save
