### ISSUE TITLE
Controlled example problem

### ISSUE THREAD

**Issue by darrylivan** [moroshko/react-autosuggest#89]
Great component!  I am having one issue however.  I need to clear the input after a user selects a suggestion so they can add another after that (much like your https://github.com/moroshko/react-autosuggest/issues/84#issuecomment-154967347 ).  However, when I add the value attribute to my Autosuggest , I get the dreaded first child error during load time:

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'firstChild' of undefined

Here is the https://gist.github.com/darrylivan/e1f0a6c1ce92fd5e1db8 for my container class I use for my autosuggest component.  When I remove the value attribute it all works great - no errors; except for the fact that I can't clear the input after a suggestion is selected.    

thanks for any help!  Appreciate your fine work!

**Comment by moroshko** [comment]
This error might mean that you have two instances of React. See [this](http://stackoverflow.com/a/29817920/247243).

To validate this theory, try to recreate the issue using a clean environment. You can use [this](http://jsbin.com/fojijazoxi/1/edit) as a starting point. I suspect that your example will work fine there.

Let us know how you go.

**Comment by darrylivan** [comment]
unsurprisingly, you were correct.  There was an entire (extra) copy of react in an a minified file.  Thanks for your quick response!
