### ISSUE TITLE
Input setState different when onSuggestionSelected using keyboard or mouse

### ISSUE THREAD

**Issue by suite22** [moroshko/react-autosuggest#90]
My use case might be outside your intended plans for the component, but I want the input to reset to an empty string instead of displaying the selected suggestion. Within onSuggestionSelected I'm using 
```this.setState({ value: "" }) ``` to reset the input to an empty string. However, that only works if I make the selection using the keyboard. If the user clicks the suggestion the input value remains set to the selected suggestion.

I put together a quick example to illustrate the issue - http://codepen.io/suite22/pen/vNPqZX or https://gist.github.com/suite22/981a9c73dc7113d88283

I forked the repo to quickly get the behavior I need 4138bab, but I'm curious if this is expected behavior. I didn't make my change a PR because it does fail several of the asserts related to mouse selection behavior.

**Comment by moroshko** [comment]
@suite22 Yep, current version has some issues with controlled behaviour. But, hold tight, version 3.0 is on its way. It will support nicely flux architecture (including redux), and you'll be able to differentiate between pressing Enter and mouse click in `onSuggestionSelected`. I plan to release it in the next couple of weeks.

**Comment by suite22** [comment]
Awesome! Sounds great. Thanks!

**Comment by moroshko** [comment]
@suite22 Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save

**Comment by suite22** [comment]
Great! Thanks @moroshko
