### ISSUE TITLE
Rendering in 3.0 development branch causes dependency problems in webpack

### ISSUE THREAD

**Issue by lxanders** [moroshko/react-autosuggest#96]
I'm currently testing the 3.0 development branch on [commit 8934f12d32d05da464e27071d6df143957389001](https://github.com/moroshko/react-autosuggest/commit/8934f12d32d05da464e27071d6df143957389001), installing it by defining this in my dependency definitions in `package.json`: `"react-autosuggest": "moroshko/react-autosuggest#8934f12d32d05da464e27071d6df143957389001",`.

I'm getting this error in my webpack bundling step and as a result my application is not working anymore:

```
ERROR in ./~/react-autosuggest/~/react-redux/lib/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/myProject/node_modules/react-autosuggest/node_modules/react-redux/lib/index.js'
    at Error (native)
 @ ./~/react-autosuggest/dist/Autosuggest.js 15:18-40

ERROR in ./~/react-autosuggest/~/react-autowhatever/dist/Autowhatever.js
Module build failed: Error: ENOENT: no such file or directory, open '/myProject/node_modules/react-autosuggest/node_modules/react-autowhatever/dist/Autowhatever.js'
    at Error (native)
 @ ./~/react-autosuggest/dist/Autosuggest.js 19:25-54
```

This is how I integrated the autosuggesting component in my `render` method:

```
const suggestions = [ { name: 'A' }, { name: 'B' }, { name: 'C' } ];
const inputProps = { value: 'FooBar', onChange: console.log.bind(null, 'Foo') };

...
<Autosuggest
    suggestions={suggestions}
    inputProps={inputProps}
    getSuggestionValue={getSuggestionValue}
    renderSuggestion={renderSuggestion} />
...
```

I'm using this in a [fluxible application](https://github.com/yahoo/fluxible) and it is rendered on the server side. So it is definitely note-worthy, that the component where I added the code snippet uses fluxible stores. I however reduced the code to a level where the store data updating etc. is in no way involved in preparing data for react-autosuggest - as you can see above it only uses static data.

I'm absolutely willing to help investigating on this so please let me know if you need more information. To me it seems as if either the dependency definition is not correct (e.g. that a required dependency is missing in react-autosuggest's `package.json`) or a sideeffect leaks out from fluxible or react-redux). These however are just my first thoughts and might be totally wrong :-).

Do you have an idea what is happening here and how it can be solved?

**Comment by moroshko** [comment]
@lxanders The error says that it cannot find `react-redux` and `react-autowhatever`. These two are indeed dependencies of `react-autosuggest`, and [they are listed in `package.json`](https://github.com/moroshko/react-autosuggest/blob/3.0/package.json#L24-L25). 

Which `npm` version do you use?

Could you try to delete `node_modules`, then `npm install` again and see if it helps?

If it doesn't, could you please create a small repo that reproduces the issue, so that I could run and investigate it locally?

**Comment by lxanders** [comment]
@moroshko Yes, this is somewhat strange. I did all the typical stuff as deleting the `node_modules`, reinstalling them, installing twice and `npm cache clean`. I'm currently using npm version 3.3.12 and node 5.1.1.

I will try to create a minimal example (that unfortunately won't be very small as fluxible requires a bit more in terms of files and configuration than a simple client side rendered react application).

**Comment by lxanders** [comment]
I'm sorry that I bothered you with this. I really don't know why (until now) but it seems the problem is gone (without changing my code or the used version of your component). For now I will close this and ask new questions if they come up. Thanks!

**Comment by moroshko** [comment]
@lxanders Glad to hear you are not blocked anymore :)

**Comment by moroshko** [comment]
@lxanders Just wanted to let you know that 3.0 alpha version is available on npm:

    npm install react-autosuggest@3.0.0-alpha.1 --save

**Comment by lxanders** [comment]
Very cool :+1: :beer:! Thanks for your work!
