### ISSUE TITLE
Acquisition of 'Controlled Component' status is unclear

### ISSUE THREAD

**Issue by Mr-Wallet** [moroshko/react-autosuggest#99]
Just spent some time wrestling with my Autosuggest component not responding to changes to the `value` prop. It wasn't until I dug into the source that I found out about the `isControlledComponent` property and that it's only set at component construction. The issue was that I was constructing without a value and only defining the value once the user interacted with it or I needed to respond to some outside event.

I would expect the component to act in a controlled manner _whenever_ it has props with a defined `value`. If there's any issues with such an implementation, then at the very least the documentation should be clear that the component must have a `value` prop when first constructed.

Thanks for the cool component!

**Comment by kromit** [comment]
Setting `props.value` as undefined or null variable during construction should also be possible. Currently i am forced to set `value=""` if i want the component to be controlled. 

Also #100 prevents the component to be controlled.

**Comment by moroshko** [comment]
@Mr-Wallet 3.0 shouldn't have this issue. Let me know if this is not the case.

    npm install react-autosuggest@3.0-latest --save
